### ISSUE TITLE
deactivate internal PDF Viewer

### ISSUE THREAD

**Issue by dornech** [florentbr/SeleniumBasic#1]
not quite an issue but is there a chance to disable the internal Chrome PDF viewer plugin programmatically ?

**Comment by florentbr** [comment]
Sure:

    Dim driver As New ChromeDriver
    
    Dim pl_flash As New Dictionary
    pl_flash.Add "name", "Adobe Flash Player"
    pl_flash.Add "enabled", False
    
    Dim pl_pdf As New Dictionary
    pl_pdf.Add "name", "Chrome PDF Viewer"
    pl_pdf.Add "enabled", False
    
    Dim pl_list As New Dictionary
    pl_list.Add "plugins_list", Array(pl_flash, pl_pdf, pl_native, pl_remote)
    
    driver.SetPreference "plugins", pl_list
    driver.Get "about:plugins"

**Comment by dornech** [comment]
thanks for the hint. I found the respective section in the preferences JSON file but did not now how to access it from within VBA. However, using the dictionary class to genreate the hierarchical structure is generally helpful.

I solved the issue another way and woud like to share my solution:

   s_URL = objSelenium.url
   objSelenium.get "chrome://plugins"
      If objSelenium.IsElementPresent(objSeleniumBy.XPath("//td[div[@class='plugin-text']/div/span[.='Chrome PDF Viewer']]/div[@class='plugin-actions']/span/a[.='Deaktivieren']")) Then
      objSelenium.FindElementByXPath("//td[div[@class='plugin-text']/div/span[.='Chrome PDF Viewer']]/div[@class='plugin-actions']/span/a[.='Deaktivieren']").Click
   End If
   objSelenium.get s_URL

**Comment by florentbr** [comment]
Just found this one while writing the doc:

    Dim driver As New ChromeDriver
    driver.SetPreference "plugins.plugins_disabled", Array("Chrome PDF Viewer")
    driver.Get "https://www.google.co.uk"
    driver.Quit
