### ISSUE TITLE
I can't launch FirefoxDriver by Windows task scheduler

### ISSUE THREAD

**Issue by kawaihk** [florentbr/SeleniumBasic#10]
Hello!
I am porting from SeleniumVBA to SeleniumBasic.

Operating system : Windows7
Office Version : 2013
SeleniumWrapper version : 1.0.23
SeleniumBasic version : 2.0.2.0

I Run a batch file with Windows task scheduler every day.
This batch file defines  Excel + VBA(including Selenium) run.

((batch file))

SET EXCEL_EXE=C:\Program Files\Microsoft Office 13\root\office13\excel.exe
SET EXCEL_FILE1=C:\sample.xlsm

START "" "%EXCEL_EXE%" "%EXCEL_FILE1%"

VBA calls WebDriver below the code.

((SeleniumVBA))

Dim driver as SeleniumWrapper.WebDriver
Set driver = New SeleniumWrapper.WebDriver

driver.Start "firefox", "https://www.google.co.uk"

((SeleniumBasic))

Dim driver as FirefoxDriver
Set driver = New FirefoxDriver

driver.Start "https://www.google.co.uk"

When a batch file (VBA calls SeleniumVBA) run by Windows task scheduler, Both Excel and FirefoxDriver run.
But when a batch file (VBA calls SeleniumBasic) run by Windows task scheduler, Excel run and FirefoxDriver doesn't run!
Error message is "Object variable or With block variable not set (Error 91)".

When a batch file (VBA calls SeleniumBasic) run by logon user, Both Excel and FirefoxDriver run.

So Would you tell me how can I do porting  from SeleniumVBA to SeleniumBasic about Windows task scheduler settings?

Thanks.

**Comment by florentbr** [comment]
SeleniumBasic no longer requires elevated/admin privileges to be installed.
As a result, the execution can only be proceed by the user who installed it.

Solution 1:
In your scheduled task, define the account that has SeleniumBasic installed.
General > Security Options > Change user or group

Solution 2:
Install SeleniumBasic on the account that run the tasks by default.

**Comment by kawaihk** [comment]
According to your advice(Solution 1), I tried to solve this issue.
In windows task scheduler , the account that has SeleniumBasic installed had already been set.

So, by the following procedure, this issue has been resolved.
I do not know Why this issue is solved by this procedure ...
Anyway, Thank you very much. Please this issue is closed.

((procedure))

1: SeleniumBasic is installed by "Run as Administrator".

2: In windows task scheduler, check off checkbox labeled "Run with highest privileges"

Thanks.
