### ISSUE TITLE
Different wait options

### ISSUE THREAD

**Issue by nikhil410** [florentbr/SeleniumBasic#100]
Hi,

Could you please help me understand the different wait options listed below.

driver.Timeouts.Server = 120000 
driver.Timeouts.PageLoad = 20000 
driver.wait (5000) 
driver.FindElementById("myobject", timeout:=10000).Click

**Comment by florentbr** [comment]
> driver.Timeouts.Server = 120000 

Raises an error if the server that controls the browser doesn't respond within 120 seconds.

> driver.Timeouts.PageLoad = 20000 

Raises an error if the page in the browser is not loaded within 20 seconds.

> driver.Timeouts.ImplicitWait = 3000 

Raises an error if an element is not found in the page within 3 seconds. This implicit timeout is applied by default to all the findElement.

> driver.wait 5000)

Waits 5 seconds before executing the next command

> driver.FindElementById("myobject", timeout:=10000).Click

Clicks on "myobject" as soon as it is found or raises an error if  is not found in the page within 10 seconds.
