### ISSUE TITLE
I can't get the correct URL using url-property.

### ISSUE THREAD

**Issue by kawaihk** [florentbr/SeleniumBasic#101]
Dear florentbr!

I am using seleniumbasic 2.0.9.0. 
I access the webpage using ChromeDriver and get url using url-property.
First url is good, but second url is NG. The last letter of Domain is disappeared!
So, I'd like you to fix this bug.

<VBA>
Public Sub test()
    Dim driver As New Selenium.ChromeDriver
    driver.Get "https://uk.sports.yahoo.com/"
    Debug.Print " url = " & driver.url
    driver.Get "/formula-1/"
    Debug.Print " url = " & driver.url
End Sub

<Result>
 url = https://uk.sports.yahoo.com/
 url = https://uk.sports.yahoo.co/formula-1/

Thanks.

**Comment by balajisekar** [comment]
Hi Kawaihk,
Try the below given coding it is working correctly in my system.

Public Sub test()
Dim driver As New Selenium.ChromeDriver
driver.Get "https://uk.sports.yahoo.com"
Debug.Print " url = " & driver.url
driver.Get "/formula-1/"
Debug.Print " url = " & driver.url
End Sub

url = https://uk.sports.yahoo.com/
url = https://uk.sports.yahoo.co/formula-1/

**Comment by kawaihk** [comment]
Thanks for the quick response.
I attempted what you had suggested and I get the correct url! 
I Close this issue.
