### ISSUE TITLE
StaleElementReferenceError

### ISSUE THREAD

**Issue by longpants** [florentbr/SeleniumBasic#102]
Hi Florent,

I was wondering if there is a (simple) way to get around the StaleElementReferenceError:

> 10 StaleElementReferenceError
> stale element reference: element is not attached to the page document
>   (Session info: chrome=48.0.2564.116)
>   (Driver info: chromedriver=2.12.301325 (962dea43ddd90e7e4224a03fa3c36a421281abb7),platform=Windows NT 6.1 SP1 x86_64)

Considering the following situation where my tested element:
html element `<input class="text decimal kolomAdvies" type="text" name="IF23348_30433" id="IF23348_30433" size="10" maxlength="20" value="">`
Set element: `set e=driver.FindElementByXpath("/*[contains(@class,'kolomAdvies')"`

Need to set value '500,00'

First I clear value to be sure nothing is added to current text
        `e.Clear`

And set new value
        `e.SendKeys`

And validate value is set
`v = Verify.Equals("500,00", s.Attribute("value"))`

Now the problem is that the server is triggered by my actions and performs some jQuery script to validate field.
When I set timers in between, it won't matter, since somehow the element `e` has lost connection with driver. If I inspect this element in VBE, the attribute `isPresent` has value `FALSE`, other parameters are errored with this message.

Now the workaround is to set the element again `set e=driver.FindElementByXpath`, but needs to be implemented in between all 3 steps, not great for performance, not nice for coding.

So is there a way to 'reattach' the element again to the driver, without retrieving. Some kind of driver refresh action?

Kind regards,

Tom

**Comment by florentbr** [comment]
The stale element error means that the element is no longer present in the page, so there's no reason for trying to interract with it.

If you are concerned about the performance, then you should use a CSS selector:

``` vb
Set field = By.Css(".kolomAdvies")
driver.FindElement(field).Clear
driver.FindElement(field).SendKeys "500,00"
v = Verify.Equals("500,00", driver.FindElement(field).Value)

```
