### ISSUE TITLE
determine filename for autosave

### ISSUE THREAD

**Issue by dornech** [florentbr/SeleniumBasic#103]
Hi there,

I am struggling with downloading files from webpages if the download file is generated via a skript. 
In this case I do not have an href attribute containing the filename. However, I woud like to know the filename of a file downloaded automatically. In the past my solution was to create an HTTP request on my own but this does not work for all Webpages.
I would appreciate any input how to achive to get known the filename of a file saved automatically

Thanks in advance

**Comment by florentbr** [comment]
The best way to get the name of the new file is to first list all the files and then wait for a new file once the link is clicked:

``` vb
''
' Waits for a new file to be created in a folder
' @folder {String}  Folder where the file will be created
' Usage:
'   WaitNewFile "C:\download\*.pdf"
'   driver.FindElementById("...").Click
'   filename = WaitNewFile()
''
Public Function WaitNewFile(Optional target As String) As String
  Static files As Collection, filter$
  Dim file$, file_path$, i&
  If Len(target) Then
    ' Initialize the list of files and return
    filter = target
    Set files = New Collection
    file = Dir(filter, vbNormal)
    Do While Len(file)
      files.Add Empty, file
      file = Dir
    Loop
    Exit Function
  End If

  ' Waits for a file that is not in the list
  On Error GoTo WaitReady
  Do
    file = Dir(filter, vbNormal)
    Do While Len(file)
      files.Item file
      file = Dir
    Loop
    For i = 0 To 3000: DoEvents: Next
  Loop

WaitReady:
  ' Waits for the size to be superior to 0 and try to rename it
  file_path = Left$(filter, InStrRev(filter, "\")) & file
  Do
    If FileLen(file_path) Then
      On Error Resume Next
      Name file_path As file_path
      If Err = 0 Then Exit Do
    End If
    For i = 0 To 3000: DoEvents: Next
  Loop
  files.Add Empty, file
  WaitNewFile = file_path
End Function
```

**Comment by dornech** [comment]
Hi Florent,

thanks for your effort. I spent some thaughts in this direction already 
but was just hoping for a smart script injection idea or something like 
this.

Thanks again

Am 22.04.16 um 17:16 schrieb Florent Breheret:
