### ISSUE TITLE
Access Denied Error when trying to launch Chrome or Firefox

### ISSUE THREAD

**Issue by jjmanthei05** [florentbr/SeleniumBasic#11]
I keep getting Access is denied error in ProcessExt.CS when clicking the Verify Titles button on the excel example that is downloaded. Please let me know what I am doing incorrectly. 

Thanks,

Jason

![image](https://cloud.githubusercontent.com/assets/13916990/9423796/1e0da2aa-4899-11e5-846c-5a426f45bbbd.png)

**Comment by florentbr** [comment]
Can you provide the following information:
Windows version, Excel version/bitness, SeleniumBasic version.

Do you use a specific command/launcher to start Excel? 

Is there anything particular about your environment?
(Sandbox, Antivirus, specific security policies...)

This error is a feedback from Windows saying that the permission was denied to start a process.

**Comment by jjmanthei05** [comment]
I am using windows 7 with excel 2007 (12.0.6727.5000) SP3. I already have excel open and I am just running this through the debugger under Developer\visual basic. Nothing exceptional on the enviroment. UAC turned off, Account is admin, No Antivirus, Personal computer so no secuirty policies. The odd thing is after I hit debug, Then firefox loads but without the address in it. It is failing on the "driver.Get row("Link")" line. 

When I run the default scripts that come with the install, firefox opens fine, I get the Quit message and it closes. Let me know what else I need to check into. 

Jason

**Comment by florentbr** [comment]
The part that is falling is the creation of a Job on the created process (Firefox) to ensure the cleaning of the child processes.
After further investigation, I suspect that it is related to way Excel is started.

So, do you use a specific command/launcher to start Excel ?
Have you tried to open the file without Excel already started ?
Is your Excel 32bit or 64bit?

**Comment by jjmanthei05** [comment]
I don't use any kind of launcher. Generally launched from opening a file up. I closed all the excel docs and opened just the example. Still got the same error. I believe it is 32 bit. does it need to be 64? 

Jason

**Comment by florentbr** [comment]
Fixed in version v2.0.4.0
