### ISSUE TITLE
Fill In Hidden field 

### ISSUE THREAD

**Issue by jjmanthei05** [florentbr/SeleniumBasic#12]
What syntax would I use to fill in the following field? I tried the sendkeys but that fails because it's hidden. Sorry if this is the wrong spot for the question. 

<input type="hidden" name="los" value="" id="los">

Thanks,

Jason

**Comment by florentbr** [comment]
I wouldn'd recommend to use an hidden field as there's probably some underlying
merchanisme attached to it. You should try to emulate as close as possible what a real user would do. Now if you are still determined, it's relatively easy to inject some javascrit:

    Dim driver As New FirefoxDriver
    driver.Get "https://www.google.co.uk"
    driver.FindElementByName("q").ExecuteScript _
        "this.value=arguments[0];", "my value"
