### ISSUE TITLE
Error with chromedriver on win server2012

### ISSUE THREAD

**Issue by zeleveld** [florentbr/SeleniumBasic#122]
I am using server2012 and seleniumbasic 2.09 with chrome Version 52.0.2743.116 m (64-bit).

When I try to start up the driver in VBA, It just hangs or I get a popup "Chrome Automation Extension has crashed. Click this balloon to reload the extension."

VBA Code (Excel 2016)
    Set cBot = New Selenium.WebDriver
    cBot.Start "chrome", "http:\www.google.com"

Error messages:
![image](https://cloud.githubusercontent.com/assets/21287142/18031676/98643138-6ca9-11e6-991a-8d355dbddd42.png)
![image](https://cloud.githubusercontent.com/assets/21287142/18031679/a8822106-6ca9-11e6-9dc6-7b64e65a168b.png)

Thanks for your help with this.

Zack

**Comment by pweisgarber** [comment]
Although the extension was not crashing for me, I am not certain the Chrome Automation Extension is needed for using Selenium to automate Chrome.  When I use the following code snippet, the Selenium driver controls Chrome, and the "Disable developer mode extensions" warning is eliminated.

`

```
Browser = "chrome"
Set WebDriver = CreateObject("Selenium.WebDriver")
With WebDriver
    .AddArgument ("--no-sandbox")
    .AddArgument ("--disable-extensions")
    .Start Browser
```

`

I reported a separate issue (#121), in which Chromedriver loses its connection to Chrome after several thousand calls, but it is not related to using the "--disable-extensions" argument.

Good luck!

**Comment by zeleveld** [comment]
Thanks,

That did the trick. =)
