### ISSUE TITLE
Syntax for multiple arguments in executeScript

### ISSUE THREAD

**Issue by mhenson1** [florentbr/SeleniumBasic#13]
I'm trying to change the value of a slider using executeScript and the following code works
Set slider = selenium.findElementByName("sliceSlider")
selenium.executeScript "arguments[0].value = '2'", slider

I'm unsure of how to parameterize the value though so that I can pass two arguments, such as something like this
Set slider = selenium.findElementByName("sliceSlider")
sliderValue = 2
selenium.executeScript "arguments[0].value = arguments[1]", (slider, sliderValue)
So the basic question is what is the syntax or can you give me an example for how to use multiple arguments in executeScript.

Thanks

**Comment by florentbr** [comment]
You almost got it right. Use an array as 2nd parameter: 

    selenium.ExecuteScript "arguments[0].value = arguments[1]", Array(slider, sliderValue)

You cold also apply the script on the element:

    Set slider = selenium.findElementByName("sliceSlider")
    slider.ExecuteScript "this.value = arguments[0]", sliderValue
