### ISSUE TITLE
Why is parsing with SeleniumBasic so slow?

### ISSUE THREAD

**Issue by diracsbracket** [florentbr/SeleniumBasic#138]
Hi.
I am trying to load the text from a table of 40x7 text elements (of which I only need the first two columns), and put it in an excel sheet.

Although the page loads quickly, getting the data from it is slow, which I don't understand. I always thought the page loading part was the slowest.

The code I use is the following:

    Set Main = Driver.FindElementByClass("morf_hilight")
    Set NormalTbl = Driver.FindElementsByClass("morf_normal") 
    Str1 = Main.FindElementByXPath("td[1]").text
    Str2 = Main.FindElementByXPath("td[2]").text
  
    Sheets("Words").Cells(i, col).Value = Str1
    Sheets("Phonetic").Cells(i, col).Value = Str2

    For j = 1 To NormalTbl.Count
        col = col + 1
               
        Str1 = NormalTbl(j).FindElementByXPath("td[1]").text
        Str2 = NormalTbl(j).FindElementByXPath("td[2]").text

        Sheets("Words").Cells(i, col).Value = Str1
        Sheets("Phonetic").Cells(i, col).Value = Str2
    Next j

This is painstakingly slow, and I am considering just parsing the html source myself, which defeats the purpose of using Selenium of course...
I thought that once you got the element (in this case representing a moderately complex table), the parsing for its text elements would be fast, but this isn't the case? I don't know how Selenium works internally but just parsing the XML of the table part should be faster than that.

It is not clear how I can speed things up....
I tried to use the Microsoft build-in XML parser, but that only works on UTF-16 and UCS-2 encoded XML... (mine is UTF-8, the Microsoft XML parser refuses to load it with error: "Duplicate attribute")

**Comment by diracsbracket** [comment]
I'll stop whining I guess... and just close this.

**Comment by mogulman52** [comment]
You need to extract it as table and not cell by cell.  It is quit fast.

`Private Sub Handle_Table2()
  Dim driver As New FirefoxDriver
  driver.Get "http://the-internet.herokuapp.com/tables"
  
  Dim tbl As TableElement
  Set tbl = driver.FindElementByXPath("//table[@id='table1']").AsTable
  
  'Print all cells
  Dim data(): data = tbl.data
  For c = 1 To UBound(data, 1)
    For r = 1 To UBound(data, 2)
      Debug.Print data(c, r)
    Next
    Debug.Print Empty
  Next
  
  driver.Quit
End Sub`
