### ISSUE TITLE
Chrome driver error

### ISSUE THREAD

**Issue by rafaleo** [florentbr/SeleniumBasic#143]
I haven't seen Run-time error 0 here so I'm posting. Using Selenium 2.0.9.

The code:
```
Dim bot As New FirefoxDriver
bot.Start "chrome"
```
Throws:
Run-time error 0: WebRequestError, Connection stopped, Unexpected error 

It opens the Chrome browser, I've checked the version:
58.0.3029.81 (64-bit)

I guess it's still the same issue as with firefox - downgrade the driver. I'm not sure which version should I use n this case. I use RSelenium with RStudio and it works wit all versions on several browsers. Why this wrapper is worse that that?

**Comment by rafaleo** [comment]
Ok. I've had to install newest driver for chrome from 3-rd party unlike the FF. Sorry, haven't read all posts.

**Comment by ElkfnCC** [comment]
hi,rafaleo! 
I used Selenium for the first time , And I used in VBA .
After I install The EXE file(SeleniumBasic-2.0.9.0.exe), 
I referended the "Selenium Type Library" in VBA Project.
Then I run this code :
`Private Sub Use_Chrome()
  Dim driver As New ChromeDriver
  driver.Get "https://www.google.co.uk"
  driver.Quit
End Sub`
It opened Google's browser, Then pop-up prompts "chromedriver.exe stopped working",Address bar says "data;,"
And Program throws this error:
"Run-time error 0: WebRequestError , Underlying connection closed: error occurred while receiving"
My Chrome's Version is 59.0.3071.104 (32bit)
I really don't know how to handle it , I would appreciate it if you could tell me what to do.

**Comment by Jottie** [comment]
You may have a conflict between your version of Chrome and your version of
Chromedriver that came with SeleniumBasic-2.0.9.0 which is pretty old to
start with.
I would recommend you upgrade Chrome to the latest version (66.xxx) and
install the latest Chromedriver available at
https://sites.google.com/a/chromium.org/chromedriver/
To install the Chromedriver, just download the zip file and extract the
content (Chromedriver.exe) to your SeleniumBasic installation folder to
replace the existing file Chromedriver.exe

From time to time as my Chrome browser is updated, I also run into
unexpected issues with SeleniumBasic for functions that used to work fine.
But every time I have such issues, I simply update the Chromedriver.exe and
all works perfectly fine again.

**Comment by ElkfnCC** [comment]
@Jottie Thanks so much! You are right!
I downloaded the matching version driver and chrome,  and now , it work!
(I can't access your Web site, but I downloaded the chromedriver from other web site)
Thanks again~ : )

PS:The following is the version of chromeDriver to Chrome, and the chromedriver Download address. Hope to be useful to others.
http://chromedriver.storage.googleapis.com/index.html
ChromeDriver | Chrome
v2.39 | v66-68
v2.38 | v65-67
v2.37 | v64-66
v2.36 | v63-65
v2.35 | v62-64
v2.34 | v61-63
v2.33 | v60-62
v2.32 | v59-61
v2.31 | v58-60
v2.30 | v58-60
v2.29 | v56-58
v2.28 | v55-57
v2.27 | v54-56
v2.26 | v53-55
v2.25 | v53-55
v2.24 | v52-54
v2.23 | v51-53
v2.22 | v49-52
v2.21 | v46-50
v2.20 | v43-48
v2.19 | v43-47
v2.18 | v43-46
v2.17 | v42-43
v2.13 | v42-45
v2.15 | v40-43
v2.14 | v39-42
v2.13 | v38-41
v2.12 | v36-40
v2.11 | v36-40
v2.10 | v33-36
