### ISSUE TITLE
WebElement.Location and Point structure

### ISSUE THREAD

**Issue by mhenson1** [florentbr/SeleniumBasic#15]
Could you provide an example for how these should work? I start with
Set myObj = selenium.FindElementByID("TheObject")
myPoint = myObj.Location
and once I get to that part I'm unable to do anything with the point that I just created. The API says I can call myPoint.ToString but the intellisense doesn't recognize ToString as a valid function and it throws an error saying "Object required: 'myPoint'" when I try using it.

I would like to be able to use this function to see the x, y coordinates for any object on the page.

Thanks for all the great work you do on this project.

**Comment by florentbr** [comment]
The ToString shouldn't be in the doc. I'll remove it from for the next release.

To get the location of a WebElement:

    Set ele = driver.FindElementById("id")
    pt = ele.Location
    sz = ele.Size
    Debug.Print "x=" & pt.x & " y=" & pt.y & " w=" & sz.width & " h=" & sz.height

For the exact API, use the object explorer in VBA (F2).
The help file is generated from VB.Net which is close to VBA and VBScript

**Comment by mhenson1** [comment]
Thanks for the quick response.
I attempted this morning what you had suggested and I get this error on the MsgBox line "Object required: 'pt'"

Here's the code I executed
Set combo = selenium.FindElementById("stovTitleMode")
pt = combo.Location
MsgBox pt.x

If this is working for you could it have anything to do with the html I'm attempting to use this on not being well formed or missing important attributes?

Thanks

**Comment by florentbr** [comment]
I managed to reproduce it in a VBScript.
I'll fix it for for the next release. In the meantime here is a workaround:

    Set driver = CreateObject("Selenium.FirefoxDriver")

    'open the browser and the page
    driver.Get "https://en.wikipedia.org/wiki/Main_Page"

    Set d = driver.FindElementById("searchInput") _
        .ExecuteScript("return this.getBoundingClientRect()")

    WScript.Echo "x=" & d("x") & " y=" & d("y") & " w=" & d("width") & " h=" & d("height")
