### ISSUE TITLE
How to get the background color of a cell from a web page

### ISSUE THREAD

**Issue by Fanou31** [florentbr/SeleniumBasic#151]
Hello Florent
I use Seleniumwrapper 1.0.23.0 with Firefox 34.0 and Excel 2013. 
I can get the contents of a web table but I have a difficulty getting the background color of a cell.
Example: joueur = driver.getTable("//table[2].1.1")	     returns "MASSET Baptiste"
	      couleur = driver.getTable("//table[2].1.4")	     returns " "	

In the HTML code of the page, I can see the information (background='./images/rouge_dg.gif' or 
background='./images/vert_dg.gif') but I don’t know how write VBA code to deal with that.
Could you help me please? 
Many thanks by advance!

![screenshot at 2017-10-12 11 47 08](https://user-images.githubusercontent.com/32733165/31490538-92cff17e-af44-11e7-8f1f-dcbd3a115280.png)

    <td class="p_blanc">08/10/17</td>
    <td class="p_blanc">MASSET Baptiste</td>
    <td class="p_blanc" align="right">500 Pts</td>
    <td class="p_blanc">Chpt France par équipes masculin</td>
    <td class='p_blanc' background='./images/rouge_dg.gif'>&nbsp;</td>
    <td class="p_blanc">&nbsp;</td>
  
    <td class="p_blanc">08/10/17</td>
    <td class="p_blanc">Absent Absent</td>
    <td class="p_blanc" align="right">500 Pts</td>
    <td class="p_blanc">Chpt France par équipes masculin</td>
    <td class='p_blanc' background='./images/vert_dg.gif'>&nbsp;</td>
    <td class="p_blanc">*</td>

**Comment by FelipeTade** [comment]
Hello I believe that there is no color in the site, but an image.
so I believe you will have to get the picture.

**Comment by FelipeTade** [comment]
Hello I believe that there is no color in the site, but an image.
so I believe you will have to get the picture.

**Comment by Jottie** [comment]
In theory you could use "Selenium.Mouse.moveTo(Selenium.WebElement)" to
move the mouse cursor to the specific element on the screen.
You can then use VBA to extract the color of that pixel. Refer to the
following link for an example of getting the colour of a specific pixel:

https://www.experts-exchange.com/questions/29039024/In-excel-2010-VBA-how-to-get-the-colour-of-a-pixel-on-the-screen.html

**Comment by Fanou31** [comment]
Hello, thank you everybody for your help.
It was not easy for me but I found the solution with 2 lines:
Set couleur = driver.findElementByCssSelector("body > table:nth-child(8) > tbody:nth-child(1) > tr:nth-child(" & i & ") > td:nth-child(5)")
resultat = couleur.getAttribute("background")

**Comment by Fanou31** [comment]
Many thanks to Florent for this Selenium application, it is great !!!
And thank you everybody for your help.
