### ISSUE TITLE
Chrome driver session not created exception SessionNotCreatedError chromedriver=2.21.371459

### ISSUE THREAD

**Issue by Libana00** [florentbr/SeleniumBasic#158]
Recently I got the following error when I try to start chrome with VBA...
 33           SessionNotCreatedError
session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"4624.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 6.1 SP1 x86_64)
It has always worked with the following:

Dim selenium As Object
Set selenium = CreateObject("Selenium.ChromeDriver")
selenium.SetProfile "C:\Users\xxxxx\User Data"
selenium.Get "www.google.de"

I already downladed the new driver, set the path, but it is still not working. Any idea how to "set the driver" in code or any other solutions? I´d appreciate any help!!

**Comment by mogulman52** [comment]
The latest driver is 2.33 and is for Chrome 60-62.  Download the latest [chromedrive](https://chromedriver.storage.googleapis.com/2.33/chromedriver_win32.zip) and replace the one at "C:\Users--user--\AppData\Local\SeleniumBasic\chromedriver.exe". This should fix it. 

    `Private Sub Use_Chrome()
      Dim driver As New ChromeDriver
      driver.Get "https://www.google.co.uk"
      driver.Quit
    End Sub
    `

**Comment by Libana00** [comment]
Thanks for your reply, I already fixed it :-) !!, but thank you anyways...
