### ISSUE TITLE
Loss of opening parenthesis with SendKeys

### ISSUE THREAD

**Issue by Dnowakdn** [florentbr/SeleniumBasic#16]
Hi Florent,

First, thanks for you job and availability ! This tool is just great ^^

I just have a problem when I try to type a value with an opening parenthesis.

            MaSaisie = ActiveCell.Offset(0, 3).Value
            Selenium.FindElementBy(int_Strategie, MonAttendu).Clear
            Selenium.FindElementBy(int_Strategie, MonAttendu).SendKeys MaSaisie

The Value of the string variable "MaSaisie" is : "SOLBIATE/VA (005;001)" (I checked that with MsgBox just before the SendKeys).

But when this text is written, I see the following value on the screen : "SOLBIATE/VA 005;001)" (with the loss of the opening parenthesis).

I use the Release v2.0.4.0 of SeleniumBasic.
I use it with Mozilla Firefox 40.0.3.
I use Excel 2010.

Thank you for your support ^^

BR,
David.

**Comment by Dnowakdn** [comment]
![20150831 16h37m27 - formulaire rempli](https://cloud.githubusercontent.com/assets/14056116/9581276/c123a770-4ffe-11e5-9514-a22870f451cf.png)

**Comment by florentbr** [comment]
This is an issue in the Firefox driver used by this project:
https://github.com/SeleniumHQ/selenium/issues/674

Here is a workaround:

    Dim driver As New FirefoxDriver
    driver.Get "https://en.wikipedia.org/wiki/Main_Page"
    Set ele = driver.FindElementById("searchInput")
    ele.ExecuteScript "this.value=arguments[0]", "a(b)c"

**Comment by florentbr** [comment]
Bug non longer present in v2.0.8.0
