### ISSUE TITLE
Switching back to the parent window in Google Chrome using Selenium VBA

### ISSUE THREAD

**Issue by shettyrish** [florentbr/SeleniumBasic#165]
My code opens 2 child windows. Once I perform my operations on each I need to close the windows and switch back to the Parent window.

There is no option as driver.switchToParentWindow. There is only driver.switchToPreviousWindow.

Eg: I close the 2nd child window --> then driver.switchToPreviousWindow switches control back to 1st child window but when I close this window and do driver.SwitchToPreviousWindow, it searches for the recently closed 2nd child window whereas I want it to switch control to the parent window.

I have tried looking everywhere for a solution, but I can't seem to find one using Selenium VBA to switch back to Parent window.

Following is my code:

      For a = 9 To LastRow
      If Wb.Sheets(DestName).Cells(a, 3).Text = "Report Name" Then                    
      'Checking if cell has 'Report Name'
           StoreFile = Wb.Sheets(DestName).Cells(a, 4).Text
           Debug.Print StoreFile

        'Click on Report
        Set myelement = driver.FindElementByLinkText(StoreFile)          'Click on report by name
        Debug.Print myelement.Text
        If myelement Is Nothing Then
            GoTo endTry
        ElseIf StoreFile = "CBD_Yoplait" Then
           StoreFile = "CBD_Yoplait" & ".Category Buyer Dynamic"
           Debug.Print StoreFile
           Set myelement = driver.FindElementByLinkText(StoreFile)
           myelement.Click
       Else
           myelement.Click
       End If

      '1st child window opens
       driver.SwitchToNextWindow
       Application.Wait (Now + TimeValue("0:0:07"))

       'Click on 'Report Home'
       Set myelement = driver.FindElementByXPath("//* 
       [@id=""ribbonToolbarTabsListContainer""]/div[1]/table/tbody/tr/td[3]")
       If myelement Is Nothing Then
           MsgBox ("no element found")
       Else
           myelement.Click
       End If

       'Click on 'Export'
         Set myelement = driver.FindElementByXPath("//* 
          [@id=""RptHomeMenu_""]/tbody/tr/td/div/div[16]/a/div[2]")
          If myelement Is Nothing Then
              MsgBox ("no element found")
          Else
             myelement.Click
          End If

         'Click on 'Excel with Formatting'
         Set myelement = driver.FindElementByXPath("//* [@id=""RptHomeExportMenu_WEB- 
         INFxmllayoutsblocksHomeExportMenuLayoutxml""]/tbody/tr/td/div/div[8]/a/div[2]")
         If myelement Is Nothing Then
              MsgBox ("no element found")
         Else
             myelement.Click
         End If

         'Opens 2nd child window
          driver.SwitchToNextWindow
          Application.Wait (Now + TimeValue("0:0:05"))

         'Click on 'Export filter details'
          Set myelement = driver.FindElementById("exportFilterDetails")
          If myelement Is Nothing Then
                MsgBox ("no element found")
          Else
               myelement.Click
          End If

         'Click on Export button
           Set myelement = driver.FindElementById("3131")
          If myelement Is Nothing Then
               MsgBox ("no element found")
         Else
              myelement.Click
        End If

         Application.Wait (Now + TimeValue("0:0:08"))

         FileSpec = StoreFile & ".xls*"
         Debug.Print FileSpec
             FileName = Dir(MyDir & FileSpec)
            Debug.Print FileName
        If FileName <> "" Then
             MostRecentFile = FileName
             MostRecentDate = FileDateTime(MyDir & FileName)
            Do While FileName <> ""
                If FileDateTime(MyDir & FileName) > MostRecentDate Then
                MostRecentFile = FileName
                MostRecentDate = FileDateTime(MyDir & FileName)
            End If
        FileName = Dir
        Loop
        End If

        MyFile = MostRecentFile
        Debug.Print MyFile
        ChDir MyDir
         Set SrcWb = Workbooks.Open(MyDir + MyFile, UpdateLinks:=0)                   
        'Saving as xls workbook
         SrcWb.SaveAs DestFolder & MyFile, XlFileFormat.xlExcel8

        Application.Wait (Now + TimeValue("0:0:04"))

        Application.DisplayAlerts = True

        SrcWb.Close

       driver.Close
       driver.SwitchToPreviousWindow
       driver.Close
       driver.SwitchToPreviousWindow ( Want to switch back to parent window)
       Application.Wait (Now + TimeValue("0:0:08"))

      endTry:
                End If
          Next a

**Comment by RonanVico** [comment]
idk why is not working with u , bcoz i have done the same and worked with me 
Driver.close
driver.switchtoprevoiuswindow
driver.close

THAT WORKED FOR ME BUT , Maybe u can try that : 
Dim DriverAUX as WebDriver

driver.switchtonextwindow
set driveraux = driver
driver.switchtopreviouswindow
driveraux.close
driver.close
set driveraux  = nothing
set driver  = nothing

Idk if that will work , but aniway , talk to us if that work , if not i will try something else to you

**Comment by shettyrish** [comment]
Hi @RonanVico , I found a solution.  A simple one-line change:
Instead of driver.switchToPreviousWindow(), I used driver.SwitchToWindowByTitle("xxxx") and used the title of the parent page.

**Comment by Abhiabyss** [comment]
Use driver. Switchtodefaultcontent
It worked for me.

**Comment by Abhiabyss** [comment]
Use the following code

Driver. Windows. First
Driver. Switchtodefaultcontent
...
