### ISSUE TITLE
[SOLVED] Chromedriver frequently hangs when attempting to start a new session.

### ISSUE THREAD

**Issue by PS1Online** [florentbr/SeleniumBasic#167]
Referring to the problem # 87 present at the following link:
https://github.com/SeleniumHQ/docker-selenium/issues/87
the problem is also present on Windows in SeleniumBasic/ChromeDriver (vba/Excel).
SeleniumBasic WebDriver 2.0.9.0 (for vba) and latest Chrome Driver (2.37) (16/03/2018).
Windows 7 64-bit.

The first row:
`Option Explicit`
`Private Chrome As ChromeDriver`
`Sub ChromeAutomation()`
`Chrome.Start 'This row frequently hangs`
`Chrome.Get "https://www.google.it/"`
`End Sub`

**Comment by vbamagician** [comment]
try this code;

```
Public Sub TestingSelenium()
Dim bot As New WebDriver
bot.Start "chrome", "https://www.google.com"
bot.Window.Maximize
bot. wait 10000 'this will wait till 10 seconds
End sub
```

**Comment by PS1Online** [comment]
Also with this code frequently hangs.
![immagine](https://user-images.githubusercontent.com/28962652/37839820-b8ce7dc2-2ebb-11e8-9a18-e6d402858818.png)

**Comment by mogulman52** [comment]
I use this form all the time and don't have problem.

```
Private Sub Use_Chrome()
  Dim driver As New ChromeDriver
  driver.Get "https://www.google.co.uk"
  driver.Quit
End Sub
```
Try on a different PC.  Try disabling any addins you may have.  Maybe something is conflicting with .NET dll.

**Comment by PS1Online** [comment]
Not work anyway

**Comment by sanjoyforever** [comment]
I also had this issue, however it got fixed when I formatted my pc. Try 32 bit instead of 64

**Comment by PS1Online** [comment]
I have builded a modified setup of SeleniumBasic with necessary files for work better with Chrome, with new vbscript modified by me and new vba modules for around the problem. This is the link.
Now all resolved without any problem!!!
I'm italian, sorry for my bad English.
https://1drv.ms/u/s!AjmmMZQf10QEiRWepciUHg4P5ENo

**Comment by PS1Online** [comment]
This is very useful also for you, for all!

**Comment by ilrisa** [comment]
> This is very useful also for you, for all!

Buongiorno,
  Anche io molto spesso quando eseguo il comando Get si blocca. La tua modifica comprende anche la correzione per le istanze contemporanee eseguite in terminal server?
Grazie
