### ISSUE TITLE
File download not saved

### ISSUE THREAD

**Issue by rjwilliams9** [florentbr/SeleniumBasic#17]
I am trying to save screen images using Chrome and ctrl-s. I am using atu.utils.windows.handler.WindowHandler to enter data in the download window. I set the option to down load "Webpage Complete". This should send an html file and a directory with the same name to the download directory. The directory with all of the support files is saved but the html file is not. The download indicator on the screen says it is download but it apparently is getting deleted or is never downloaded.

**Comment by florentbr** [comment]
You are probably quitting the browser while it is still saving the page.
Try to add a delay:

    Private Sub Test()
        Dim driver As New ChromeDriver
        driver.Get "https://www.google.co.uk"
        
        Set wsh = CreateObject("WScript.Shell")
        wsh.SendKeys "^s"           'press Ctrl + s
        driver.Wait 500             'wait half a second
        wsh.SendKeys "test.html"    'write name
        wsh.SendKeys "{ENTER}"      'press enter
        driver.Wait 2000            'wait 2 seconds
        
        driver.Quit
    End Sub
