### ISSUE TITLE
Unable to run selenium

### ISSUE THREAD

**Issue by nikhil410** [florentbr/SeleniumBasic#173]
Hi,

I installed the latest version of SeleniumBasic (2.0.9.0), updated the chrome driver to 2.40 and added a reference in the macro to "Selenium Type Library" but cannot seem to run the attached code

Sub test()
    Dim driver As New ChromeDriver
    driver.Get "www.google.com"
End Sub

**Error message while executing driver.get**
![image](https://user-images.githubusercontent.com/15649073/43180680-07a60c70-8ff7-11e8-8410-f5ac75b379bb.png)

I am using a 64 bit windows 10 and Microsoft excel 2016 (32 bit). Please advise on where I am going wrong.

Thanks !!

**Comment by vbamagician** [comment]
Hi Nikhil, You're all doing wrong here. You're not initiating the driver and want a result!

Here is the code!

```
Sub TestGooglePage()
    Dim bot As New WebDriver
    bot.Start "chrome", "https://www.google.com"
    bot.Window.Maximize
    bot.Get "/"
    bot.Wait 10000
End Sub
```

All the best!

**Comment by nikhil410** [comment]
Hi Kamal, I tried running your code but get the same message. I have a feeling its because of the .Net framework i am using but dont know how to correct it :( Do you have any recommendations?

**Comment by nikhil410** [comment]
Hey, its working fine now. I just re-installed .net framework. Thanks Kamal !!!
