### ISSUE TITLE
Using "IsElementPresent"

### ISSUE THREAD

**Issue by nevokron** [florentbr/SeleniumBasic#18]
When using this command generated by the SeleniumIDE for Firefox in vb.NET:

    While Waiter.Not(driver.IsElementPresent(By.Id("_someidentifier"))) : End While

the editor marks "By.Id", giving the error: "Reference to a non-shared member requires an object reference". Where does the issue arise from?

Thanks,
Nev

**Comment by florentbr** [comment]
It's like it says, By is unknown.
You probably forgot the declaration line:
Dim By As New By, Assert As New Assert, Verify As New Verify, Waiter As New Waiter
