### ISSUE TITLE
chrome extension: error cannot base64 decode

### ISSUE THREAD

**Issue by dornech** [florentbr/SeleniumBasic#19]
I stored a local CRX file and tried to set this up for use in chrome. 
I receive the abovementioned error when starting the webdriver.

**Comment by dornech** [comment]
I think the issue is described here: https://github.com/angular/protractor/issues/175
However, I am afraid I missed the point how to apply the solution within SeleniumBasic or if SeleniumBasic could be improved.

**Comment by florentbr** [comment]
Fixed in v2.0.5.0

**Comment by dornech** [comment]
works fine now. thanks for the effort.
