### ISSUE TITLE
Error for using chrome selenium basic

### ISSUE THREAD

**Issue by MartinHCH** [florentbr/SeleniumBasic#195]
Below programme only works for ie but not for chrome

```
Sub driver()
    Dim Selenium As New Selenium.WebDriver

    Selenium.Start "chrome"
    Selenium.Get "http://google.com/"

End Sub
```

Errors show up as below.
![Capture](https://user-images.githubusercontent.com/53932820/62762395-91d7cb00-babb-11e9-9f47-9dd379cbfe56.PNG)

**Comment by Jottie** [comment]
I see you are using the latest version of Chrome. 
Are you using the latest Chromedriver as well?
You can get it here: https://sites.google.com/a/chromium.org/chromedriver/
Just unzip and replace the chromedriver.exe in the SeleniumBasic installation directory

**Comment by MartinHCH** [comment]
SessionNotCreatedError
session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"5BC9B2AA7D442F8C72014ACCC25897C7","isDefault":true,"type":"default"},"id":1,"name":"","origin":"://"}
  (Session info: chrome=76.0.3809.100)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 6.1 SP1 x86)

**Comment by MartinHCH** [comment]
Thx a lot!!!
Problem solved.
