### ISSUE TITLE
migration from version 1.x

### ISSUE THREAD

**Issue by dornech** [florentbr/SeleniumBasic#2]
unfortunately lot of changes require a migraiton of coding susing the Selenium Wrapper. Documentaiton what to change would be helpful.

**Comment by florentbr** [comment]
**Changes from the Selenium 1 methods:**
 All the methods from Selenium 1 have been removed.

**Changes from the Selenium 2 methods:**
 driver.getScreenShot -> driver.TakeScreenShoot
 driver.setImplicitWait -> driver.Timeouts.ImplicitWait
 driver.stop -> driver.Quit
 driver.open -> driver.Get
 driver.back -> driver.GoBack
 driver.forward -> driver.GoForward
 driver.WindowHandle, WindowHandles ->
    driver.Window.Handle
    driver.Windows
    driver.SwitchToNextWindow
    driver.SwitchToPreviousWindow
 ele.getAttribute(...) -> ele.Attribute(...)
 ele.getCssValue(...) -> ele.CssValue(...)
 
**To instantiate the browser :**
Dim driver = New FirefoxDriver
driver.Get "htttp:\\"
**Or**
Dim driver = New WebDriver
driver.Start "firefox"
driver.Get "htttp:\\"
