### ISSUE TITLE
chrome automation extension aborts

### ISSUE THREAD

**Issue by dornech** [florentbr/SeleniumBasic#20]
when starting chrome webdriver (local chrome installation) the sessions tops with a notificaiton that the chrome automation exetnsion aborted.

**Comment by dornech** [comment]
might be related to issue reported here:
https://code.google.com/p/selenium/issues/detail?id=6152

**Comment by dornech** [comment]
issue seems to be chrome version-related. problem occurs with latest chrome 45.0.2454.85 but not with 44.0.2403.125

I tried to replace the chromedriver.exe 2.16 included in the distribution package by 2.19 but error is not resolved.

**Comment by Jottie** [comment]
Same issue here. Using Chrome 45.0.2454.85 and chromedriver included in SeleniumBasic v2.0.4.0
Not sure if it helps but calling "driver.Get" generates the following log entry to debug.log in Chrome app directory:
[0908/165215:ERROR:client_util.cc(272)] Could not find exported function RelaunchChromeBrowserWithNewCommandLineIfNeeded

**Comment by dornech** [comment]
driver.AddArgument ("--no-sandbox") seems to work for me as well.

**Comment by florentbr** [comment]
Fixed in v2.0.5.0

**Comment by dornech** [comment]
works fine now. thanks for the effort.
