### ISSUE TITLE
In SeleniumBasic How to Create an Array on "div" Tags

### ISSUE THREAD

**Issue by rsherfey** [florentbr/SeleniumBasic#210]
I am scraping data from a Chrome webpage in Excel v.16 using SeleniumBasic.
Because this deal with patient data, I cannot provide a lot of information.
Originally, I wrote the code I needed using VBA in IE.

Here is the html:
 
![image](https://user-images.githubusercontent.com/67288933/90294699-eb47a800-de3b-11ea-9e8e-ac0a061d4818.png)

Here is my original VBA code, which worked just fine:

![image](https://user-images.githubusercontent.com/67288933/90294959-948e9e00-de3c-11ea-91e2-f66c7b96fd51.png)

    
In SeleniumBasic I am finding it difficult to grab the “div” data. I can access
![image](https://user-images.githubusercontent.com/67288933/90295026-bd169800-de3c-11ea-9baa-8b2ea1eadbe7.png
because it is an “id”.
But I need to know how to get the message elements within that “div id” (could be up to 10 messages) and load them into an array.
The "Messages" I am referring to are: 
![image](https://user-images.githubusercontent.com/67288933/90295092-e3d4ce80-de3c-11ea-9f91-5a4683fdb661.png)

Is there a way to accomplish using Selenium Basic what I did in VBA? 
Any help would be greatly appreciated!

**Comment by mogulman52** [comment]
To select elements use Xpath.  It is extremely powerful.  It takes a bit to understand it so be patient.  Search 'Xpath Tutorial Youtube' on Bing.

**Comment by rsherfey** [comment]
mogulman52, thank you for your recommendation. I think Xpath is what I was looking for.
