### ISSUE TITLE
How to convert pages to PDF or Print pages to PDF by VBA

### ISSUE THREAD

**Issue by Ivan2Hsu** [florentbr/SeleniumBasic#214]
I want to print or convert the pages to PDF. And the PDF file should not be a screenshot. 

There's a lot of example written in Phython or Java like below.

_
> Import json
> from selenium import webdriver
> chrome_options = WebDriver.ChromeOptions()
> settings = {"recentDestinations": [{"id": "Save as PDF", "origin": "local", "account": ""}], "selectedDestinationId": "Save as PDF", "version": 2}
> 
> prefs = {'printing.print_preview_sticky_settings.appState': json.dumps(settings)}
> chrome_options.add_experimental_option('prefs', prefs)
> chrome_options.add_argument('--kiosk-printing')
> browser = webdriver.Chrome(r"chromedriver.exe", options=chrome_options)
> browser.get ("https://google.com/")
> browser.execute_script('window.print();')
> browser.close()
_

But I found it's hard to get an example of the codes based on VBA w/ Seleniumbasic for me.
Is there anybody could help?

**Comment by GCuser99** [comment]
```vba
Sub test_kiosk_printing()
    Dim driver As New ChromeDriver
    Dim appState As String
    Dim d As New Dictionary
    'Dim settings As String
    
    driver.AddArgument "--kiosk-printing"
    
    appState = "{""recentDestinations"": [{""id"": ""Save as PDF"", ""origin"": ""local"", ""account"": """"}], ""selectedDestination"": ""Save as PDF"", ""version"": 2}"
    d.Add "appState", appState
    driver.SetPreference "printing.print_preview_sticky_settings", d
    
    'or alternatively...
    'settings = "{'appState': '{""recentDestinations"": [{""id"": ""Save as PDF"", ""origin"": ""local"", ""account"": """"}], ""selectedDestination"": ""Save as PDF"", ""version"": 2}'}"
    'driver.SetPreference "printing.print_preview_sticky_settings", settings

    driver.Start
    
    driver.Get "https://www.google.com/"
    
    driver.Wait 1000

    'sends pdf file to Downloads folder
    driver.ExecuteScript("window.print();")
    
    driver.Wait 2000
    
    driver.Close
    driver.Quit
End Sub
```

**Comment by wolflash666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
已经收到，等我看到了，立马回复。

**Comment by Ivan2Hsu** [comment]
> ```vbnet
> Sub test_kiosk_printing()
>     Dim driver As New ChromeDriver
>     Dim appState As String
>     Dim d As New Dictionary
>     'Dim settings As String
>     
>     driver.AddArgument "--kiosk-printing"
>     
>     appState = "{""recentDestinations"": [{""id"": ""Save as PDF"", ""origin"": ""local"", ""account"": """"}], ""selectedDestination"": ""Save as PDF"", ""version"": 2}"
>     d.Add "appState", appState
>     driver.SetPreference "printing.print_preview_sticky_settings", d
>     
>     'or alternatively...
>     'settings = "{'appState': '{""recentDestinations"": [{""id"": ""Save as PDF"", ""origin"": ""local"", ""account"": """"}], ""selectedDestination"": ""Save as PDF"", ""version"": 2}'}"
>     'driver.SetPreference "printing.print_preview_sticky_settings", settings
> 
>     driver.Start
>     
>     driver.Get "https://www.google.com/"
>     
>     driver.Wait 1000
> 
>     'sends pdf file to Downloads folder
>     driver.ExecuteScript("window.print();")
>     
>     driver.Wait 2000
>     
>     driver.Close
>     driver.Quit
> End Sub
> ```

GC, thanks a lot. It works well.

**Comment by DiQuintino** [comment]
how can we set the folder that we need to save the files and rename the file?

**Comment by dornech** [comment]
Hi,

this depends on the browser.

I use specific routines to prepare different sets of config settings
depending on the browser type and then set them during driver
initialisation.



'------------------------------------------------------------------------------------
' routine to start Selenium Driver
'
' stealth settings here (but only Chrome):
'
https://stackoverflow.com/questions/53039551/selenium-webdriver-modifying-navigator-webdriver-flag-to-prevent-selenium-detec
'
https://piprogramming.org/articles/How-to-make-Selenium-undetectable-and-stealth--7-Ways-to-hide-your-Bot-Automation-from-Detection-0000000017.html
'------------------------------------------------------------------------------------

Sub initializeSeleniumDriver( _
    ByRef objSelenium As Selenium.WebDriver, _
    ByVal s_WebdriverBrowser As String, _
    Optional ByVal s_URL As String, _
    Optional ByVal s_Arguments As String, _
    Optional ByVal s_BrowserExtensions As Variant, _
    Optional ByVal s_BrowserPrefs As Variant, _
    Optional ByVal i_RetryWaitSec As Integer = 0, _
    Optional ByVal i_RetryCounterMax As Integer = 0, _
    Optional ByVal s_StartSearch_BrowserBinary As String = vbNullString, _
    Optional ByVal b_Stealth As Boolean = True, _
    Optional ByVal b_optScraping As Boolean = True, _
    Optional ByVal b_reCAPTCHA As Boolean = True _
)

...

'  set requested browser preferences
    If IsArray(s_BrowserPrefs) Then
       For i_Idx = LBound(s_BrowserPrefs) To UBound(s_BrowserPrefs)
          If (s_BrowserPrefs(i_Idx)(0) <> vbNullString) Then
             objSelenium.SetPreference s_BrowserPrefs(i_Idx)(0),
s_BrowserPrefs(i_Idx)(1)
          End If
       Next
    End If

...

End sub


' generate array-constant with necessary browser parameters -> for new
Selenium WebDriver starter

Function BrowserPrefs_directDownload(ByVal s_WebdriverBrowser As String,
ByRef s_Path As String) As Variant

'  check/determine path for direct download
    If (s_Path = vbNullString) Or Not DirExists(s_Path) Then
       s_Path = TempDir()
    End If

'  set array with browser preferences
    If (s_WebdriverBrowser = s_WebdriverBrowser_Chrome) Then
       BrowserPrefs_directDownload = Array( _
          Array("download.default_directory", s_Path), _
          Array("download.prompt_for_download", False), _
          Array("plugins.plugins_disabled", Array("Chrome PDF Viewer")), _
          Array("plugins.always_open_pdf_externally", True) _
       )
    ElseIf (s_WebdriverBrowser = s_WebdriverBrowser_FireFox) Then
       BrowserPrefs_directDownload = Array( _
          Array("browser.download.folderList", 2), _
          Array("browser.download.dir", s_Path), _
          Array("browser.download.manager.showWhenStarting", False), _
          Array("browser.helperApps.alwaysAsk.force", False), _
          Array("browser.helperApps.neverAsk.saveToDisk",
"application/pdf,text/csv"), _
          Array("pdfjs.disabled", True) _
       )
    End If

End Function




Am 03.06.2023 um 05:18 schrieb DiQuintino:

**Comment by GCuser99** [comment]
see my response in [issue 264](https://github.com/florentbr/SeleniumBasic/issues/264#issuecomment-1574960505)

**Comment by DiQuintino** [comment]
Whats the difference betweenn Webdriver and Basic?  Im using basic rn. Do u recommend that I start using Webdriver instead? I always saw webdriver for python, java, etc. but not for VBA...

TY for the answers :)

**Comment by GCuser99** [comment]
Two different things, if I understand your question - SeleniumBasic is a VB.Net, VBA and VBScript wrapper for controlling the Selenium WebDrivers (ChromeDriver.exe, MSEdgeDriver.exe, GeckoDriver.exe, and IEDriverServer.exe). Hope that helps...

**Comment by DiQuintino** [comment]
The problem that I have now is that all the pages that I wan to safe, have the same title, just the data change. Im thinking of rename after save, based on the name of the copy. 
like the saved files:

Document.pdf
Document (1).pdf
Document (2).pdf

And i have the sort and the correct filename at worksheet that fill tha forms...

ty again for answering :)

**Comment by DiQuintino** [comment]
Hey, it was working well. But since this week, the window prompt to save is now waiting for a name. Before it was automatic saving as WebDriver.Title Property... I didnt change the code...

**Comment by wolflash666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
已经收到，等我看到了，立马回复。

**Comment by DiQuintino** [comment]
How?

**Comment by DiQuintino** [comment]
The only way that I can integrate VBA and Selenium its using SeleniumBasic, right?
