### ISSUE TITLE
Excel VBA Error on Microsoft Surface

### ISSUE THREAD

**Issue by mgjoshi07** [florentbr/SeleniumBasic#218]
Hello All

Have no issue with using Selenium on a HP Desktop.  However, on my Microsoft Surface laptop, I get the following error ...
---
Microsoft Visual Basic

Run time error '-2146232576 (80131700)'
Automation error
---
Note: Both my laptop (MS Surface Pro) and desktop (HP) have an Intel i7 processor with 16 MB RAM

Any assistance in troubleshooting will be much appreciated.  Thank you, MGJ

**Comment by Jottie** [comment]
Make sure you have .NET Framework 3.5 enabled. It is installed but disabled by default on Win10 
Update: To enable, click start, in the search box, enter "OptionalFeatures.exe" and press Enter
Search for .NET Framework 3.5 in the list and make sure it is ticked.

**Comment by mgjoshi07** [comment]
Jottie - cannot thank you enough!  Your solution was spot on. :-)
