### ISSUE TITLE
Element not visible

### ISSUE THREAD

**Issue by paololrs** [florentbr/SeleniumBasic#22]
Hello,

I'm triyng to insert text in input tag using VBA and Chrome with SeleniumWrapper and this code:
driver.findElementByName("value").SendKeys "value"

But it generate this error: "element not visible..."

I tried to use code found in other issue:
driver.findElementByName("value").executeScript _
     "this.value=arguments[0];", "my value"

but it's not working.

How can I resolve this?

**Comment by florentbr** [comment]
> But it generate this error: "element not visible..."
This means that the element is found, but it is not visible at the time you are executing SendKeys.
You could try:
driver.findElementByName("value").WaitDisplayed().SendKeys "value"

> I tried to use code found in other issue:
> driver.findElementByName("value").executeScript _
> "this.value=arguments[0];", "my value"
> but it's not working.
Could you be more specific and provide a reproducible example?

**Comment by paololrs** [comment]
Thank you for the answer.

The element is found, in fact, for example, the method ISELEMENTPRESENT get it.
Unfortunatally the solutions you suggest doesn't work, the result is: "Error run-time '438' - Method not supported".

This is the Html code: 
<input type="text" class="text" name="CODICE_CENTRO" value="" size="25" maxlength="25" onblur="this.value=this.value.toUpperCase()">

The html tag is in a iframe, I don't know if it's important.

Any other idea please?

**Comment by paololrs** [comment]
Html code:
input type="text" class="text" name="CODICE_CENTRO" value="" size="25" maxlength="25" onblur="this.value=this.value.toUpperCase()"

**Comment by florentbr** [comment]
It looks like you are still using SeleniumWrapper which is no longer supported.
Have you tried with the last version of SeleniumBasic?
https://github.com/florentbr/SeleniumBasic/releases

**Comment by paololrs** [comment]
I downloaded SeleniumBasic.
Now the command 
driver.findElementByName("value").WaitDisplayed().SendKeys "value"
works, but the result is an "Error run-time '21' - TimeOutError".

**Comment by paololrs** [comment]
This is the website where is the element I can't fill:
http://www.tutelafiscale.it/live-caf-web/

and this is the input element:
input type="text" class="text" name="CODICE_CENTRO" value="" size="25" maxlength="25" onblur="this.value=this.value.toUpperCase()"

Any help please?

**Comment by paololrs** [comment]
It's possibile to use only Chrome. 
With IE and VBA I can fill the input element but I can not log in cause only Chrome is admitted.

**Comment by paololrs** [comment]
I understood the problem: in the page there are 2 input elements with the same name.
The first is hideen while the second (that I need) I can get only with a loop.
Do you know a code for a loop I can use? :)

**Comment by florentbr** [comment]
The fields of interest are in a frame which is a webpage page inside a webpage.
To work with a frame, you need to change the context of the driver:

    Dim driver As New ChromeDriver
    driver.Get "http://www.tutelafiscale.it/live-caf-web"

    ' Change the context to the first Frame
    driver.SwitchToFrame 0

    driver.FindElementByName("CODICE_CENTRO").SendKeys "codis centro"
    driver.FindElementByName("CODICE_SPORTELLO").SendKeys "codis sportello"
    driver.FindElementByName("PASSWORD").SendKeys "password"

    driver.FindElementByXPath("//input[@value='Accedi']").Click

    ' Get back to the main context
    driver.SwitchToDefaultContent

**Comment by paololrs** [comment]
Thank you very much!
