### ISSUE TITLE
Argument Error VB.Net

### ISSUE THREAD

**Issue by nevokron** [florentbr/SeleniumBasic#23]
Hi!
Today I installed the last version of Selenium Basic, and since then I get the error as per subject (view picture attached). Previously the code was working flawlessly. What happened?
Thanks,
Nev

![argumenterror](https://cloud.githubusercontent.com/assets/13818637/9835964/9a01ac2c-5a04-11e5-85ba-9056dd09d34c.jpg)

**Comment by florentbr** [comment]
The message couldn't be more explicit.
The file firefoxdriver.xpi is certainly missing in your Debug directory.
You should add a post build event in your project properties to automatically add it:

    xcopy /D /Y %USERPROFILE%\AppData\Local\SeleniumBasic\firefoxdriver.xpi

Now the reason it was probably working before is that the previous version was caching this file in the TEMP folder.

FYI, the Start method is no longer required as Get call will launch the browser if it hasn't been.
