### ISSUE TITLE
Windows 11?

### ISSUE THREAD

**Issue by GCuser99** [florentbr/SeleniumBasic#232]
Has anyone had success getting SeleniumBasic to work on Windows 11, Excel 365 VBA? I have it working in Windows 10, but am getting an automation error when trying to do anything with the ChromeDriver object in Windows 11. In both OS's, am using v96.0.4664.45 of Chrome web browser.

Thanks!

**Comment by GCuser99** [comment]
I found the following obscure resource that I was able to get to work in Windows 11 - it's a pure VBA solution for automating Chrome and Edge using Selenium. At this point it is rough and not nearly as comprehensive as SeleniumBasic, but it represents a great starting point!

https://github.com/uezo/TinySeleniumVBA

**Comment by wolflash666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
已经收到，等我看到了，立马回复。

**Comment by GCuser99** [comment]
I was able to get SeleniumBasic to work in Windows 11. My problem was that .Net Framework 3.5 wasn't installed yet.
