### ISSUE TITLE
Missing method after upgrading from 1/0/23/0

### ISSUE THREAD

**Issue by kdebarb63** [florentbr/SeleniumBasic#25]
Here after partial code used in 1.0.23.0 on Firefox.

I've migrated wih last version due to Firefox upgrade for security
With last version I got error due to missing method.
My code get data from html table; and I can't use vba code to extract table now.
What solution can you propose as workaround or integration of missing method.

  Dim MyDriver As New FirefoxDriver
  MyDriver.Get "https://www.server.com" 'my https server.

  MyDriver.setTimeout ("120000")
  MyDriver.setImplicitWait (30000)
  MyDriver.waitForTitle "Title"
  MyDriver.waitForText "Text to be present"
  MyArray(0) = MyDriver.getTable("css=table.name.1.1")

**Comment by florentbr** [comment]
> MyDriver.setTimeout ("120000")
> MyDriver.setImplicitWait (30000)

To set the timeouts:
Dim driver As FirefoxDriver
driver.Timeouts.PageLoad = x
driver.Timeouts.ImplicitWait = x
driver.Timeouts.Script = x
driver.Timeouts.Server = x

Note that ImplicitWait is acivated by default with a 3 second timeout.
I recommend to not change this value and to use a specific timeout on the FinElement when required.
To try to locate an element for 12 seconds:
Set ele = driver.FindElementById("id", 12000)

> MyDriver.waitForTitle "Title"

Dim Waiter As New Waiter
While Waiter.Not(driver.Title = "expected"): Wend

> MyDriver.waitForText "Text to be present"

driver.FindElementById("id").WaitText "expected"
or
Dim Waiter As New Waiter
Set ele = driver.FindElementById("id")
While Waiter.Not(ele.Text = "expected"): Wend

> MyArray(0) = MyDriver.getTable("css=table.name.1.1")

You can use an XPath to retreive a sepecific cell.
To get the third cell on the second row:
txt = driver.FindElementByXPath("table/body/tr[2]/td[3]").Text

You can also pull all the table to an array:
Dim data()
data = driver.FindElementByCss("table").AsTable.data
txt = data(2, 3)
