### ISSUE TITLE
Runtime Error -2146232576 (80131700)' for each driver. - commands

### ISSUE THREAD

**Issue by luigivandetti** [florentbr/SeleniumBasic#251]
Hello, unfortunately every time I try to control a browser I get the error 

Runtime Error -2146232576 (80131700)'

I have tried with Edge and Chrome. In both cases the same scenario. I have updated the drivers in the C:\...\AppData\Local\SeleniumBasic directory. 

How can I fix the error? 

![image](https://user-images.githubusercontent.com/77322961/166883328-8976f5c4-e467-4caa-b606-8dab377e027c.png)

**Comment by GCuser99** [comment]
Is  .Net Framework 3.5 installed on your computer?

**Comment by luigivandetti** [comment]
> Is .Net Framework 3.5 installed on your computer?

No, but .Net Framework 4.8. I guess that doesn't work with it?

**Comment by GCuser99** [comment]
I don't know if there is backward compatibility. I have both .Net Framework versions installed and it works fine for me. 

Also for Edge and Chrome, make sure the driver and browser major version matches (the numbers to the left of first period in the version strings).

**Comment by luigivandetti** [comment]
After I installed the .Net Framework 3.5, now all seems to work :) Thank you!
