### ISSUE TITLE
Is it working on Windows Server 2012?

### ISSUE THREAD

**Issue by Delphima** [florentbr/SeleniumBasic#262]
Hello,
I have followed the video of  www.wiseowl.com to install SeleniumBasic on my desktop Windows 10 + Excel 2016 and made some scraping code, which is working as expected. The issue happens when I run the Excel file at VPS with Windows Server 2012 + Excel 2013, the code is not working anymore. The error occurs as below:
![image](https://user-images.githubusercontent.com/30689213/212783020-73a16b7b-1a6a-4967-be29-1e17327bab05.png)

I'm sure the SeleniumBasic v2.0.9.0 has been installed correctly to _'C:\Program Files\SeleniumBasic'_
And the correct version of _'ChromeDriver 109.0.5414.74, chromedriver_win32.zip'_, has been extracted to the above directory.
And I didn't forget to make a reference to Selenium Type Library, in VBE menu Tools -> References

Please advise, if I should do anything else to make it run correctly.
Thanks,

**Comment by Delphima** [comment]
This issue has been discussed by post: https://github.com/danwagnerco/selenium-vba/issues/166
Install .net Framework 3.5, will fix this problem.
:)

**Comment by wolflash666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
已经收到，等我看到了，立马回复。
