### ISSUE TITLE
Actions.DragAndDropByOffset doesn't take zero as an offset parameter

### ISSUE THREAD

**Issue by mhenson1** [florentbr/SeleniumBasic#27]
When I execute this code
Set selenium = CreateObject("Selenium.ChromeDriver")
selenium.SetCapability "debuggerAddress", "127.0.0.1:38947"
selenium.Start

set myObj = selenium.FindElementByID("aWebElement*")
selenium.Actions.DragAndDropByOffset(myObj, 25, 0).Perform

I get this error
UnknownError
unknown error: at least an element or offset should be set
  (Session info: content shell=)
  (Driver info: chromedriver=2.19.346078 (6f1f0cde889532d48ce8242342d0b84f94b114a1),platform=Windows NT 6.1 SP1 x86_64)

If I passed the parameters as (myObj, 25, 1) then it works fine. Every value seems to work (including negative numbers) except for passing zero. I searched around and couldn't find anywhere that said this was just a general Selenium limitation so I thought I'd see if you had any ideas.

Thanks always for the awesome help

**Comment by florentbr** [comment]
Fixed in v2.0.6.0
