### ISSUE TITLE
Help! I am getting this error when script tries to open ie browser "unexpected error launching internet explorer ielaunchurl() returned hresult 80070005"

### ISSUE THREAD

**Issue by bleeet** [florentbr/SeleniumBasic#28]
![image](https://cloud.githubusercontent.com/assets/12282986/10641648/17deaaf4-77e8-11e5-8355-c70fc7249377.png)

hi guys
when I try to run my script I am getting this error when it tries to open the ie browser.
"unexpected error launching internet explorer ielaunchurl() returned hresult 80070005"
From my searches this seems to be a frequent issue that has happened to a lot of people. Is there a fix for this? I have set all the permissions to unchecked in each zone in the ie security tab but still get this error.

I am using ie 10

**Comment by bleeet** [comment]
Also I am using the example  excel file that is provided in the seleniumbasic.exe

**Comment by florentbr** [comment]
I couldn't reproduce your issue. It should come from a specific setting.
What you can try is to first reset your internet explorer settings:
 Options > Advanced > Reset

Then close IE, install the latest version (v2.0.6.0) and restart your computer.
Finally make sure that:
 * All 4 zones have the "Enable Protected Mode" unchecked in "Advanced"
 * In "Advanced", "Enable Enhanced Protected Mode" is unchecked 
 * In "Advanced", "Enable 64-bit processes for Enhanced Protected Mode" is unchecked
