### ISSUE TITLE
Selenium VBA + AutoIT Integration

### ISSUE THREAD

**Issue by Coolguy29** [florentbr/SeleniumBasic#29]
Hi Florentbr,

i want to know, in this current version will i be able to use Selenium with AutoIT.
I want to automate a pop-up window which works only when i integrate Selenium with AutoIT.

i have to call an .exe file of AutoIT in selenium code.

whether i will be able to use the same code in Selenium VBA.

if yes can you help me with the code.

**Comment by florentbr** [comment]
To use SeleniumBasic in an AutoIt script:

    Dim $driver = ObjCreate("Selenium.FirefoxDriver")
    $driver.Get("https://en.wikipedia.org/wiki/Main_Page")
    ...

To use AutoIt in a VBS or VBA script:

    Set autoit = CreateObject("AutoItX3.Control")
    autoit.Send "{ENTER}"
    ...
