### ISSUE TITLE
Selenium IDE formatter and Wrapper 2.0

### ISSUE THREAD

**Issue by dornech** [florentbr/SeleniumBasic#3]
as far as I understood the Selenium IDE commands are not any more supported completly. furthermore syntactical changes require a new formatter setup. Is there a new VBA formatter coming up ?

**Comment by florentbr** [comment]
The included formatters have always supported the Selenium 1 and Selenium 2 commands.
From now on it's only possible to export the recorded test case to the Selenium 2 format:
VBA / WebDriver
VBS / WebDriver

And yes it includes the latest syntactical changes.
