### ISSUE TITLE
handling Windows and IFrames

### ISSUE THREAD

**Issue by Coolguy29** [florentbr/SeleniumBasic#30]
can we have functions to how to handle Window pop-up and IFrames in webpage.

if yes please share the  code.

thanks

**Comment by florentbr** [comment]
These are the related methods:

    driver.SwitchToFrame "id"       'Sets the context on a frame
    driver.SwitchToDefaultContent   'Sets the default context

    driver.SwitchToNextWindow      'Sets the context on the next window
    driver.SwitchToPreviousWindow  'Sets the context on the previous activated window

    Set allwindows = driver.Windows   'Gets all windows
    Set savedWindow = driver.Window   'Gets the current window
    savedWindow.Activate              'Activates a specific window

I invite you to have a look at the API help file in "Selenium.chm" and at the examples in Examples.xlsm
