### ISSUE TITLE
getPerformanceTiming logic

### ISSUE THREAD

**Issue by Coolguy29** [florentbr/SeleniumBasic#31]
Please can you explain the logic of getPerformanceTiming logic which you have mentioned in the example below:-
.
Function NextRow() As Range  
    Static i As Integer
    i = IIf(i = 0, 1, i + 1)    'Increments the row index
    Set NextRow = Range("A:I").Rows(i)  'Returns the next row
End Function

Public Sub GetPerformanceTiming()
    Dim driver As New SeleniumWrapper.WebDriver
    driver.Start "firefox", "http://uk.news.yahoo.com"  'Starts firefox
    
    'Writes the titles on the first row
    NextRow() = Array("Page Url", "Page load", "Redirect", "DNS", "Connecting", "Waiting", "Receiving", "DOM", "Events")
    
    'Opens each page and copies the metrics in the WorkSheet ( 1 row for each page opened)
    driver.Open "tech"
      NextRow() = driver.getPerformanceTiming()
    driver.Open "world"
      NextRow() = driver.getPerformanceTiming()
    driver.Open "opinion"
      NextRow() = driver.getPerformanceTiming()
    driver.Open "business"
      NextRow() = driver.getPerformanceTiming()
    
    driver.stop 'Closes Firefox
End Sub

**Comment by florentbr** [comment]
The "getPerformanceTiming" method was not ported to this project. It was using the Javascript "performance.timing" API to create the metrics:
https://developer.mozilla.org/en/docs/Web/API/Navigation_timing_API
http://www.html5rocks.com/en/tutorials/webperformance/basics
http://www.w3.org/TR/navigation-timing

You can still craft your own one with a Javascript call:

    Const script = "var t=performance.timing;return [t.responseEnd-t.navigationStart,t.loadEventEnd-t.responseEnd];"

    Dim driver As New FirefoxDriver
    driver.Get "https://en.wikipedia.org/wiki/Main_Page"
    times = driver.ExecuteScript(script).Values

**Comment by Coolguy29** [comment]
Hi Florentbr,
I have prepared a macro to pull the performance of my project page.
its working fine but with Errors.
Also its generating a lot of Log & Junk files in my system. 
Is it due to i'm making Variable i as Static?
Here is the error:-

![image](https://cloud.githubusercontent.com/assets/15376695/10962708/51c80a38-83c0-11e5-9004-59d7cf9a3451.png)


![arithematic error](https://cloud.githubusercontent.com/assets/15376695/10962756/b1ac1980-83c0-11e5-8de8-63c13a41b23b.png)


Allthough when i click on "Debug" and again Run the script it works fine.

But it storing a lot of Junk files. Can you say what may be the possible reason?
its slowing down my system.
May be because i'm making variable i as Static? i'm not sure.?
Any method to release the memory space which the variable is reserving?
How can we implement this?

Here is my Complete code which i'm using. Any improvement suggested will be very much Welcome.

Private Sub CommandButton21_Click()
Dim driver As New SeleniumWrapper.WebDriver
 Set pdf = CreateObject("SeleniumWrapper.PdfFile")
 Dim By As New By, Assert As New Assert, Verify As New Verify, Waiter As New Waiter
  Dim path, url
  Dim wndhand
  Dim perf
  Dim m As Integer, n As Integer
  'Writes the titles on the first row
   ' NextRow() = Array("Page Url", "Page load", "Redirect", "DNS", "Connecting", "Waiting", "Receiving", "DOM", "Events")
   Worksheets("Input").Activate
   Sheets("Input").Select
    path = Range("B3").Value
  url = Range("B2").Value
  browser = Range("B4").Value
  MsgBox path
  MsgBox url
  MsgBox browser
 
  Shell (path + "\\PRM Login1.exe")
  Set selenium = CreateObject("SeleniumWrapper.WebDriver")
  Set pdf = CreateObject("SeleniumWrapper.PdfFile")
  'pdf.addImage selenium.getScreenshot()
  
driver.Start browser, url
  
driver.setImplicitWait 5000
driver.maximizeWindow
 
 driver.get "/"
  pdf.addImage selenium.getScreenshot()
 'driver.setImplicitWait 5000
'  NextRow() = driver.getPerformanceTiming()
 driver.setImplicitWait 50000
 pdf.addImage selenium.getScreenshot()
 windowhandle
'wndhand = driver.getAllWindowTitles
'MsgBox wndhand(0)
'MsgBox wndhand(1)
'driver.Focus (wndhand(1))
'driver.switchToWindow (1)
'driver.switchToDefaultContent
driver.setImplicitWait 50000
  driver.findElementById("butBegin").Click
 ' pdf.addImage selenium.getScreenshot()
  driver.switchToWindow (0)
  driver.setImplicitWait 5000
  pdf.addImage selenium.getScreenshot()
 ' Worksheets("Page Performance").Activate
  'Sheets("Page Performance").Select
   ' Sheets("Page Performance").Activate
  'Sheets("Sheet2").Activate
 ' For m = 1 To 9
   ' For n = 1 To 9
   'driver.setImplicitWait 5000
    NextRow() = driver.getPerformanceTiming
   ' driver.setImplicitWait 5000
  ' perf(10, 10) = driver.getPerformanceTiming
 ' Next n
 ' Next m
  
 ' MsgBox perf(1, 1)
  'MsgBox perf(1, 2)
 ' MsgBox perf(1, 3)
 ' MsgBox perf(1, 4)
  
  'NextRow() = perf
 ' NextRow() = driver.getPerformanceTiming()
  'MsgBox NextRow(0)
  
   'Writes the titles on the first row
    'NextRow() = Array("Page Url", "Page load", "Redirect", "DNS", "Connecting", "Waiting", "Receiving", "DOM", "Events")
 'driver.setImplicitWait 5000
 driver.waitForAlertNotPresent
 ' ERROR: Caught exception [ERROR: Unsupported command [waitForPopUp | _self | 30000]]
 
 'driver.findElementByCssSelector("nobr.ms-crm-NavBar-Area-Title").Click
 
 'driver.findElementByCssSelector("#nav_accts > nobr.ms-crm-NavBar-Subarea-Title").Click
 pdf.SaveAs "C:\Users\407484\Desktop\Performance Tool\Screenshots\sscapture.pdf"
 
  driver.stop
End Sub
Function NextRow() As Range
    Static i As Integer
    'i = 1
      ' MsgBox i
      ' Worksheets("Sheet2").Activate
       'Sheets("Sheet2").Activate
       'Sheets("Page Performance").Activate
       Worksheets("Page Performance").Activate
       If i = 0 Then
       i = 2
       Else
       i = i + 1
       End If
       
       
    'i = IIf(i = 0, 1, i + 1)    'Increments the row index
     MsgBox i
    Set NextRow = Worksheets("Page Performance").Range("A:I").Rows(i)  'Returns the next row
    'Range("K(i)").Value = Now
    Worksheets("Page Performance").Cells(i, "K").Value = Now
    'NextRow.Cells(i, "K").Value = Now
  Worksheets("Page Performance").Rows(i).Select
   ' Exit Function
    
    'MsgBox NextRow(0)
End Function
Function windowhandle() As Windows
 Dim driver As New SeleniumWrapper.WebDriver
 
 Dim By As New By, Assert As New Assert, Verify As New Verify, Waiter As New Waiter
  
  
Dim wndhand, cnt


wndhand = driver.getAllWindowTitles

'pdf.addImage selenium.getScreenshot()
'MsgBox wndhand(0)
'MsgBox wndhand(1)
'driver.Focus (wndhand(1))
driver.switchToWindow (1)
End Function

Thanks in Advance

**Comment by florentbr** [comment]
Your exemple is from the SeleniumWrapper project which is no longer supported.
You should consider switching to SeleniumBasic:
https://github.com/florentbr/SeleniumBasic/releases

**Comment by Coolguy29** [comment]
ok. Thanks,

i have downloaded the Selenium Basics and working on that. I am facing a lot of issues:-
1. How to Maximize & Minimize the window?
2.How i will implement getperformanceTiming() logic here, do we have any function like this here or API?
3.Putting Screenshots in a .pdf file 

Thanks in advance.

**Comment by florentbr** [comment]
> 1. How to Maximize & Minimize the window?

To maximize a window:

    driver.Window.Maximize
    
Minimizing the window is not supported by Selenium. If your purpose is to hide it, then you can position it off-screen:

    driver.Window.SetPosition -2000, 0

> 2.How i will implement getperformanceTiming() logic here, do we have any function like this here or API?

This was already answered in comment 2.

> 3.Putting Screenshots in a .pdf file

https://github.com/florentbr/SeleniumBasic/blob/master/Examples/VBScript/CaptureToPdf(Firefox).vbs
