### ISSUE TITLE
beginner question: I used the old selenium wrapper and just downloaded the new seleniumbasic release I am having trouble navigating sites because the syntax changed. 

### ISSUE THREAD

**Issue by bleeet** [florentbr/SeleniumBasic#32]
Hi guys this is probably a foolish question but it may help a lot of people that are not experts like me may come in here asking the same thing and prevent them from asking this again.

  I uninstalled the old selenium wrapper v 1.0.23.0 and installed the new seleniumbasic.

a lot of my old syntax does not work is this supposed to happen?
like for example 

<code>
selenium.Type "id= userbaser", "hello"

</code>

I am getting errors like missing object

**Comment by florentbr** [comment]
This project only implements the Selenium 2 API. The "Type" command is from the old Selenium RC API (Selenium 1) and is deprecated now by the official project.

In your case the right syntax would be:

    selenium.FindElementById("userbaser").SendKeys "hello"
