### ISSUE TITLE
how do I select items in a drop down menu and iterate through a table?

### ISSUE THREAD

**Issue by bleeet** [florentbr/SeleniumBasic#33]
Hi 

I used to use the old selenium 1 and I am new to selenium 2.0. I am have difficulties selecting items in a drop down menu. what is the syntax to do this?

also how to I iterate through a table?

Does anyone happen to know a helpful website where I can find the proper vba  syntax for selenium 2?

thanks

**Comment by florentbr** [comment]
> I am have difficulties selecting items in a drop down menu. what is the syntax to do this?

    Private Sub Handle_Dropdown_List()
        Dim driver As New FirefoxDriver, Assert As New Assert
        driver.Get "http://the-internet.herokuapp.com/dropdown"
        
        Dim ele As SelectElement
        Set ele = driver.FindElementById("dropdown").AsSelect
        ele.SelectByText "Option 2"
        Assert.Equals "Option 2", ele.SelectedOption.Text
        
        driver.Quit
    End Sub


> also how to I iterate through a table?

    Private Sub Iterate_A_Table()
        Dim driver As New FirefoxDriver, Assert As New Assert
        driver.Get "http://the-internet.herokuapp.com/tables"
        
        'Print all cells from the second column
        Dim ele As WebElement
        For Each ele In driver.FindElementsByCss("#table1 tbody tr td:nth-child(2)")
            Debug.Print ele.Text
        Next
        
        driver.Quit
    End Sub

    Private Sub Iterate_A_Table2()
        Dim driver As New FirefoxDriver, Assert As New Assert
        driver.Get "http://the-internet.herokuapp.com/tables"
        
        Dim tbl As TableElement
        Set tbl = driver.FindElementByCss("#table1").AsTable
        
        Dim Data()
        Data = tbl.Data
        For c = 1 To UBound(Data, 1)
          For r = 1 To UBound(Data, 1)
            Debug.Print Data(r, c)
          Next
          Debug.Print Empty
        Next
        
        driver.Quit
    End Sub

> Does anyone happen to know a helpful website where I can find the proper vba syntax for selenium 2?

The usage is very similar to the other language binding which are well documented.
Moreover the API is light and the complexity using Selenium is more about creating the right selector and dealing with timing issues.
