### ISSUE TITLE
Not able to call a new macro

### ISSUE THREAD

**Issue by nikhil410** [florentbr/SeleniumBasic#34]
Hi,

I have a macro which does certain steps on a browser using selenium and calls another macro toward the end depending on a few conditions I have given. This macro seems to be working fine but as soon as the second macro starts I am getting an error.

![capture](https://cloud.githubusercontent.com/assets/15649073/10935756/44f00db8-830e-11e5-9cb0-5e749786dc2c.PNG)

I have used this macro on my laptop previously and did not have any issues. Not sure why i am getting this error when i use the same codes on a desktop. Please help !!

**Comment by florentbr** [comment]
For issues please provide a concise reproducible test case.

**Comment by nikhil410** [comment]
please find below an example of what i am talking

Sub macro1
     Dim Driver As New SeleniumWrapper.WebDriver
    Dim key As New SeleniumWrapper.Keys
    Driver.Start "chrome", "https://www.amazon.com"
    Driver.Open "http://www.amazon.com"
    Driver.Wait (7000)
    
    Driver.findElementById("twotabsearchtextbox").Click
    Driver.SendKeys (ActiveCell.Value)
    Driver.SendKeys key.Enter
    Driver.Wait (7000)
    Driver.SendKeys key.End
    If Driver.isElementPresent("id=noResultsTitle") = True Then
    Call next_keyword
    Else
    'it will do some steps on the search result and then call next_keyword
End sub


sub next_keyword
    Dim Driver As New SeleniumWrapper.WebDriver
    Dim key As New SeleniumWrapper.Keys
    Worksheets("Keyword").Select
    Range("B" & ActiveCell.Row + 1).Select
    if activecell.value <> vbnullstring then
    Driver.Open "http://www.amazon.com"
    Driver.Wait (7000)
    
    Driver.findElementById("twotabsearchtextbox").Click
    Driver.SendKeys (ActiveCell.Value)
    Driver.SendKeys key.Enter
    Driver.Wait (7000)
    Driver.SendKeys key.End
    ' do some steps etc, etc
    end if
end sub

The macro1 will run fine and then when it calls macro next_keyword, I get the error message given in the screenshot above.

I have used this exact same excel file on my laptop earlier and it was working fine but I want to use it on a desktop now. Any leads on  why this might not be working would be much appreciated.

Thank you !!

**Comment by florentbr** [comment]
SeleniumWrapper is no longer supported.
SeleniumBasic is the successor with only the Selenium 2 API since Selenium 1 is deprecated:
https://github.com/florentbr/SeleniumBasic/releases

Here is a usage example with your test case:

    Sub macro1()
      Dim driver As New ChromeDriver
      Dim Keys As New Keys
      Dim By As New By
      
      driver.Get "http://www.amazon.com"
      driver.FindElementById("twotabsearchtextbox").Click
      driver.SendKeys "test"
      driver.SendKeys Keys.Enter
      driver.Wait 7000
      driver.SendKeys Keys.End
      
      If driver.IsElementPresent(By.Id("noResultsTitle")) Then
        Call next_keyword
      End If
    End Sub

**Comment by nikhil410** [comment]
Hi,

I have install the new version of the driver and edited the code as advised by you but even then the first macro works fine, but when it calls the second macro i am getting the same error message. Please advise.

**Comment by florentbr** [comment]
I couldn't reproduce the issue you are describing.
Please, provide your OS and office version and attach a workbook that reproduce your issue.

**Comment by nikhil410** [comment]
OS : Windows 7 Enterprise
Office : Professional Plus 2013

Sub US_crawler()

    Dim Driver As New ChromeDriver
    Dim key As New Keys
    Dim by As New by
    Dim search As String
    Dim Asin As String
    
    
    ActiveWorkbook.ActiveSheet.Activate
    
    Worksheets("Result").Select
    Range("A1").Select
    
    Worksheets("Keyword").Select
    Range("B2").Select
    
    
    Driver.Start "chrome", "https://www.amazon.com"
    Driver.Get "http://www.amazon.com"
    Driver.Wait (7000)
    
    Driver.findElementById("twotabsearchtextbox").Click
    Driver.SendKeys (ActiveCell.Value)
    Driver.SendKeys key.Enter
    Driver.Wait (7000)
    Driver.SendKeys key.End
    
    
    If Driver.IsElementPresent(by.ID("noResultsTitle")) Then
    Worksheets("Keyword").Select
    Range("B" & ActiveCell.Row + 1).Select
    If ActiveCell.Value <> vbNullString Then
    'Call next_keyword
    
13  Worksheets("Keyword").Select
    Range("B" & ActiveCell.Row).Select
    Driver.Open "http://www.amazon.com"
    Driver.Wait (7000)
    
    Driver.findElementById("twotabsearchtextbox").Click
    Driver.SendKeys (ActiveCell.Value)
    Driver.SendKeys key.Enter
    Driver.Wait (7000)
    Driver.SendKeys key.End
    
    If Driver.IsElementPresent(by.ID("noResultsTitle")) Then
    Worksheets("Keyword").Select
    Range("B" & ActiveCell.Row + 1).Select
    If ActiveCell.Value <> vbNullString Then
    GoTo 13
    Else
    Exit Sub
    End If
    End If
    
    Max = Mid(Driver.findElementById("s-result-count").Text, 9, 2)
    
    If Max = " f" Then
    Max = Left(Driver.findElementById("s-result-count").Text, 1)
    Else
    If Max = "ts" Then
    Max = Left(Driver.findElementById("s-result-count").Text, 2)
    End If
    End If
    
    If Max > 19 Then
    'Call twenty_results
    
    ar = ActiveCell.Row
    R = Max + ar
    np = ar + 16
    
    search = Driver.URL
    
    s = 0
    Driver.FindElementByCss("#result_" & s & " > div > div > div > div.a-fixed-left-grid-col.a-col-right > div.a-row.a-spacing-small > a").Click
    Driver.Wait (7000)
    
    Worksheets("Result").Select
    Range("A" & ActiveCell.Row + 1).Select
    Asin = Driver.URL
    ActiveCell.Value = Asin
    
    Worksheets("Keyword").Select
    ActiveCell.Offset(0, 1).Select
    
10  If ActiveCell.MergeCells = True Then
    Call Merge
    Else
    If Left(ActiveCell.Value, 1) = "-" Then
    Call exclude
    Else
    Call Normal
    End If
    End If
    
11  Worksheets("Keyword").Select
    ActiveCell.Offset(0, 1).Select
    If ActiveCell.Value <> vbNullString Then
    GoTo 10
    Else
    Call classification
    Worksheets("Keyword").Select
    Range("C" & ActiveCell.Row).Select
    
    Worksheets("Result").Select
    If ActiveCell.Row = np Then
    Driver.Wait (7000)
    Driver.Open search
    Driver.Wait (7000)
    Driver.SendKeys key.End
    Driver.findElementById("pagnNextLink").Click
    Driver.Wait (7000)
    search = Driver.URL
    s = 0
    GoTo 14
    If ActiveCell.Row = R Then
    Worksheets("Keyword").Select
    Range("B" & ActiveCell.Row + 1).Select
    If ActiveCell.Value <> vbNullString Then
    Call next_keyword
    Exit Sub
    Else
    Exit Sub
    End If
    End If
    Driver.Wait (4000)
    Driver.Open search
    Driver.Wait (7000)
    Driver.SendKeys key.End
14  s = s + 1
    If s = 50 Then
    Exit Sub
    End If
    On Error GoTo -1
    On Error GoTo 13
    Driver.FindElementByCss("#result_" & s & " > div > div > div > div.a-fixed-left-grid-col.a-col-right > div.a-row.a-spacing-small > a").Click
    Driver.Wait (7000)
    
    Worksheets("Result").Select
    Range("A" & ActiveCell.Row + 1).Select
    Asin = Driver.URL
    ActiveCell.Value = Asin
    
    Worksheets("Keyword").Select
    
    GoTo 10
    End If
    End If
    
    'Call twenty_results


    Else
    If Max > 16 Then
    Call twopage_results
    Else
    Call onepage_results
    End If
    End If
    Exit Sub
    
    'Call next_keyword end
    
    Else
    Exit Sub
    End If
    End If
    
    Max = Mid(Driver.findElementById("s-result-count").Text, 9, 2)
    
    If Max = " f" Then
    Max = Left(Driver.findElementById("s-result-count").Text, 1)
    Else
    If Max = "ts" Then
    Max = Left(Driver.findElementById("s-result-count").Text, 2)
    End If
    End If
    
    If Max > 19 Then
    Call twenty_results
    Else
    If Max > 16 Then
    Call twopage_results
    Else
    Call onepage_results
    End If
    End If
End Sub

Sub twenty_results()

    Dim Driver As New ChromeDriver
    Dim key As New Keys
    Dim by As New by
    Dim search As String
    Dim Asin As String
    
    ar = ActiveCell.Row
    R = Max + ar
    np = ar + 16
    
    search = Driver.URL
    
    s = 0
    Driver.FindElementByCss("#result_" & s & " > div > div > div > div.a-fixed-left-grid-col.a-col-right > div.a-row.a-spacing-small > a").Click
    Driver.Wait (7000)
    
    Worksheets("Result").Select
    Range("A" & ActiveCell.Row + 1).Select
    Asin = Driver.URL
    ActiveCell.Value = Asin
    
    Worksheets("Keyword").Select
    ActiveCell.Offset(0, 1).Select
    
10  If ActiveCell.MergeCells = True Then
    Call Merge
    Else
    If Left(ActiveCell.Value, 1) = "-" Then
    Call exclude
    Else
    Call Normal
    End If
    End If
    
11  Worksheets("Keyword").Select
    ActiveCell.Offset(0, 1).Select
    If ActiveCell.Value <> vbNullString Then
    GoTo 10
    Else
    Call classification
    Worksheets("Keyword").Select
    Range("C" & ActiveCell.Row).Select
    'call the next ASIN here
    
    Worksheets("Result").Select
    If ActiveCell.Row = np Then
    Driver.Wait (7000)
    Driver.Open search
    Driver.Wait (7000)
    Driver.SendKeys key.End
    Driver.findElementById("pagnNextLink").Click
    Driver.Wait (7000)
    search = Driver.URL
    s = 0
    GoTo 14
    If ActiveCell.Row = R Then
    Worksheets("Keyword").Select
    Range("B" & ActiveCell.Row + 1).Select
    If ActiveCell.Value <> vbNullString Then
    Call next_keyword
    Exit Sub
    Else
    Exit Sub
    End If
    End If
    Driver.Wait (4000)
    Driver.Open search
    Driver.Wait (7000)
    Driver.SendKeys key.End
14  s = s + 1
    If s = 50 Then
    Exit Sub
    End If
    On Error GoTo -1
    On Error GoTo 13
    Driver.FindElementByCss("#result_" & s & " > div > div > div > div.a-fixed-left-grid-col.a-col-right > div.a-row.a-spacing-small > a").Click
    Driver.Wait (7000)
    
    Worksheets("Result").Select
    Range("A" & ActiveCell.Row + 1).Select
    Asin = Driver.URL
    ActiveCell.Value = Asin
    
    Worksheets("Keyword").Select
    
    GoTo 10
    End If
    End If

End Sub

Sorry, I could not attach the workbook. I have pasted the codes here for your perusal.

Please let me know if you need any further information.

**Comment by florentbr** [comment]
Could you also tell if your Office is 32 or 64bits?
To expect some support, you'll have to provide a **concise** example with what you expect and what is failing at which step. Your example is not runnable as it is since it is linked to some worksheets not provided. Moreover, it contains a lot of code that is not related to this issue.

**Comment by nikhil410** [comment]
please find below a concise example

Sub test1()
    Dim driver As New ChromeDriver
    Dim key As New Keys
    
    driver.Start "chrome", "https://www.amazon.com"
    driver.Get "http://www.amazon.com"
    
    Call test2
    
End Sub

Sub test2()
    Dim driver As New ChromeDriver
    Dim key As New Keys
    
    driver.FindElementById("twotabsearchtextbox").Click
    driver.SendKeys ("working")

End Sub

test1() works fine and opens amazon.com and then calls test2() to click on the search bar but i get an error message on the first line of test2(). The error message is as follows

![capture](https://cloud.githubusercontent.com/assets/15649073/11057527/cccc84b2-87b1-11e5-8a45-7627f0b76fd4.PNG)

**Comment by dornech** [comment]
May I step in here to support florentbr.

The error is not cause by any error within SeleniumBasic but caused by incorrect programming.
The driver object in test2 is NOT identical to the driver object from the calling routine and in particular not linked to a browser session (i. e. no start-method invoked for driver object in test2 before trying to access data in a browser session) .
Pass the driver object by reference from the calling routine to test2 and it will work. 

You may refer to
https://github.com/florentbr/SeleniumBasic/issues/7
as well.

**Comment by florentbr** [comment]
It's like @dornech said, the "driver" from test1 and test2 are 2 different objects.
Have a look here for more information:
https://support.microsoft.com/en-gb/kb/141693

You can either use a global variable:

    Dim driver As WebDriver

    Sub test1()
        Set driver = New ChromeDriver
        driver.Get "http://www.amazon.com"
        Call test2
        driver.Quit
        Set driver = Nothing
    End Sub

    Sub test2()
        driver.FindElementById("twotabsearchtextbox").Click
        driver.SendKeys "working"
    End Sub

Or you can pass the driver as argument:

    Sub test1()
      Dim driver As New ChromeDriver
      driver.Get "http://www.amazon.com"
      Call test2(driver)
      driver.Quit
    End Sub

    Sub test2(driver As WebDriver)
      driver.FindElementById("twotabsearchtextbox").Click
      driver.SendKeys "working"
    End Sub

Here is an example with Amazon:
    
    Public Sub Search()
      Dim driver As New ChromeDriver
      SearchAmazon driver, "drum carrot"
    End Sub
    
    Private Sub SearchAmazon(driver As WebDriver, words)
      ' open the page, type in the field and submit
      driver.Get "http://www.amazon.com/s"
      driver.FindElementByCss("#twotabsearchtextbox").SendKeys(words).Submit
        
      Dim By As New By
      Do
        ' wait for the loading bar to disapear
        driver.WaitNotElement By.Css("#centerBelowPlusspacer"), timeout:=7000
        
        ' Print all titles
        For Each ele In driver.FindElementsByCss("#s-results-list-atf a.s-access-detail-page")
          Debug.Print ele.Text
        Next
        
        ' click next page or exit the loop if the link is not present
        Set bt_next = driver.FindElementByCss("#pagnNextLink #pagnNextString", timeout:=0, raise:=False)
        If bt_next Is Nothing Then Exit Do
        bt_next.Click
      Loop
    End Sub

**Comment by nikhil410** [comment]
@florentbr, @dornech Its working perfectly now. Thank you so much for the help and support. You guys are the best :)
