### ISSUE TITLE
Firefox alert dissappeared when continuing VBA code

### ISSUE THREAD

**Issue by longpants** [florentbr/SeleniumBasic#35]
Hi Florent,

Another question.
When I read the driver and findElement with Xpath ("//button") the page shows an browser alert (popup).
Afther this I like to continue and create a screenshot.

To pass this I try to read by xpath the "//body", in case error, I switch to Alert and create screenshot (so for all other actions without error the macro is not slowed down when looking for the alert window)
For Chrome this works fine, but Firefox and IE seem to hide the Alert popup.

Do you recognize this and know why, and can I solve this somehow?

(I'm using the late binding with the CreateObject2 as your provided xlsm without registration.)

**Comment by florentbr** [comment]
For issues please provide a concise reproducible test case and describe what results you are seeing and what results you expect.

**Comment by longpants** [comment]
Hi Florent, I was hoping that you recogized this problem, but I created a mockup from my xls tool (extracted the most important stuff)

Lets say a default alert from html page:
```<!DOCTYPE html>
<html>
<body>

<p>Click the button to display an alert box:</p>

<button onclick="myFunction()">Try it</button>

<script>
function myFunction() {
    alert("I am an alert box!");
}
</script>

</body>
</html>
```

And the vba code:
```
'
' Function to directly call a .Net Dll without registration
'
' Edit the NETDLL function to make it return the Selenium.dll library
'
' Include these references if Office 32bits:
' c:\Windows\Microsoft.NET\Framework\v2.0.50727\mscoree.tlb
' c:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.tlb
'
' Include these references if Office 64bits:
' C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscoree.tlb
' C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorlib.tlb
'
Const selPath As String = "C:\Users\Langebroekt\AppData\Local\SeleniumBasic"
Public driver As WebDriver
Public sStep As String
Private Function NETDLL() As String
    'NETDLL = Environ("USERPROFILE") & "\AppData\Local\SeleniumBasic\Selenium.dll"
    NETDLL = selPath & "\Selenium.dll"
End Function

Function CreateObject2(typeName As String) As Object
On Error GoTo exitFunction
    Static domain As mscorlib.AppDomain
    If domain Is Nothing Then
        Dim host As New mscoree.CorRuntimeHost
        host.Start
        host.GetDefaultDomain domain
    End If
    Set CreateObject2 = domain.CreateInstanceFrom(NETDLL, typeName).Unwrap

Exit Function

exitFunction:
If blDebug Then
    Stop
    Resume
End If
End Function
Sub run()
'Const sBrowser As String = "firefox"
Const sBrowser As String = "chrome"
Debug.Print "start"
Select Case sBrowser
Case "chrome"
    Set driver = CreateObject2("Selenium.ChromeDriver")
    driver.SetBinary "C:\Users\Langebroekt\AppData\Local\Microsoft\AppV\Client\Integration\850316DA-8A41-46C6-BCE8-06C221F449F0\Root\VFS\ProgramFilesX86\chrome\chrome.exe"

Case "firefox"
    Set driver = CreateObject2("Selenium.FirefoxDriver")
    driver.SetBinary "C:\Users\myUser\AppData\Local\Microsoft\AppV\Client\Integration\A2382923-160A-41CF-AA2E-85129C65D9CC\Root\VFS\ProgramFilesX86\Mozilla Firefox\firefox.exe"

Case "ie"
    Set driver = CreateObject2("Selenium.IEDriver")
    'driver.SetBinary "C:\Users\myUser\AppData\Local\Microsoft\AppV\Client\Integration\A2382923-160A-41CF-AA2E-85129C65D9CC\Root\VFS\ProgramFilesX86\Mozilla Firefox\firefox.exe"


End Select
driver.Start

driver.get "c:\temp\testalert.html"


On Error GoTo TestNOK:

sStep = "step1"
If driver.FindElementByXPath("//p").Text = "Click the button to display an alert box:" Then doResult True

sStep = "step2"
driver.FindElementByXPath("//button").Click
doResult True


exitSub:
driver.Quit

Exit Sub

TestNOK:
doResult False
GoTo exitSub
End Sub
Function doResult(blTestOK As Boolean)
On Error GoTo errFunction
If isAlertPresent Then
    Debug.Print driver.SwitchToAlert.Text
    'create screenshot from alert
    blTestOK = False
Else
    'create screenshot from page
End If

If blTestOK Then
    Debug.Print sStep & " Test OK"
Else
    Debug.Print sStep & " Test NOK"
End If

Exit Function

errFunction:
Debug.Print "error in alert recognision"
End Function
Function isAlertPresent() As Boolean
Dim e As WebElement

On Error GoTo errFunction:

Set e = driver.FindElementByXPath("//body")

Exit Function

errFunction:
If Err.Number = 26 Then
    isAlertPresent = True
End If
End Function
```

When I change the constant to "chrome" my debug reads:
```start
step1 Test OK
I am an alert box!
step2 Test NOK
```

When I change the constant to "firefox" my debug reads:
```start
step1 Test OK
error in alert recognision
```

Note: Since my business laptop works with somekind 'browser pack' I needed to set de binairy.

**Comment by longpants** [comment]
My output when I run "chrome", "firefox" or "ie":

```
run
start chrome
step1 Test OK
I am an alert box!
step2 Test NOK

start firefox
step1 Test OK
error in alert recognision

start ie
32: InvalidSelectorError
The xpath expression '//p' cannot be evaluated or does notresult in a WebElement
step1 Test NOK
```

**Comment by florentbr** [comment]
Your issue is related to the "unexpectedAlertBehaviour" capability:
https://code.google.com/p/selenium/wiki/DesiredCapabilities

The default value for chrome seems to be "ignore" while it is "accept" for firefox and IE.
You can overcome this behaviour by setting the capability at the beginning:

    Private Sub TestAlert()
      Dim Assert As New Assert
      Dim driver As New WebDriver
      driver.SetCapability "unexpectedAlertBehaviour", "ignore"
      
      For Each browser In Array("chrome", "ie", "firefox")
        driver.Start browser
        driver.Get "http://the-internet.herokuapp.com/javascript_alerts"

        driver.FindElementByCss("button").Click
        If IsDialogPresent(driver) Then
          Set dlg = driver.SwitchToAlert()
          Assert.Equals "I am a JS Alert", dlg.Text
          dlg.Accept
          driver.TakeScreenshot.SaveAs "screenshot.png"
        End If
        
        driver.Quit
      Next
    End Sub

    Function IsDialogPresent(driver As WebDriver) As Boolean
      On Error Resume Next
      t = driver.Title
      IsDialogPresent = Err.Number = 26
    End Function

> start ie
> 32: InvalidSelectorError
> The xpath expression '//p' cannot be evaluated or does notresult in a WebElement
> step1 Test NOK

In your example you are using a local file (driver.Get  "c:\temp\testalert.html").
By default Internet explorer disable Javascript for local files which is required for Selenium to work.
To work with a local html files, you can either use a local server or you can disable the restriction by setting this option in the Advanced tab in IE :
"Allow Active Content to run in files in my computer"

**Comment by longpants** [comment]
Great (I knew it should be something like that), thanks a lot, again!

**Comment by WebtestingIO** [comment]
Hi,

Great job on this project. I recently started to use the CreateObject2 approach, and it worked great for a few days, but now I am getting the the following error when the driver.get command is called: 

System.ComponentModel.Win32Exception
Line 0 in 
The system cannot find the file specified

The FireFox Driver sttil works, but he ChromeDriver and IEDriver are now not working. Any ideas?

Thanks,
Marc
