### ISSUE TITLE
how to select multiple links / element ids

### ISSUE THREAD

**Issue by bleeet** [florentbr/SeleniumBasic#36]
hi 

I am trying to select multiple links / element ids. But in order to select more than one manually I have to hold the control button on my keyboard then select the next  link / element id in order for them both to be highlighted. How can I do this on selenium?

here is part of the code to select one option

<code>
chromex.findElementById("ctl00_ContentPlaceHolder1_PgCntrl_CreateUserWizard_AvailableRoles_LBI0T0").click

</code>

here another link/element id 

<code>

chromex.findElementById("ctl00_ContentPlaceHolder1_PgCntrl_CreateUserWizard_AvailableRoles_LBI1T0").Click

</code>

I tired putting <code> chromex.Keyboard.Keys.Control </code> in between those two links but I get the error "invalid use of property"

thanks

**Comment by florentbr** [comment]
Here is an example:

    Private Sub Handle_Multi_Select()
      Dim driver As New FirefoxDriver, Keys As New Keys
      driver.Get "http://odyniec.net/articles/multiple-select-fields"
      
      Dim ele As WebElement
      For Each ele In driver.FindElementsByXPath("//select[@name='ingredients[]']/option")
        ele.Click Keys.Control
      Next
      
      driver.Quit
    End Sub
