### ISSUE TITLE
additional question to how to select multiple links / element ids 

### ISSUE THREAD

**Issue by bleeet** [florentbr/SeleniumBasic#37]
hi florentbr,

thanks so much for the help and sorry I have a lot of questions due to me trying to figure out how to code in selenium 2,0.  I ask you a question you you prvided a code

<code>Private Sub Handle_Multi_Select()
  Dim driver As New FirefoxDriver, Keys As New Keys
  driver.Get "http://odyniec.net/articles/multiple-select-fields"

  Dim ele As WebElement
  For Each ele In driver.FindElementsByXPath("//select[@name='ingredients[]']/option")
    ele.Click Keys.Control
  Next

  driver.Quit
End Sub</code>

I don't want to to loop through the table so I am trying to click and then hold control after clicking the link to keep the option highlighted

I tried this 

<code>
Dim driver As New ChromeDriver, keys As New keys

driver.findElementById("ctl00_ContentPlaceHolder1_PgCntrl_CreateUserWizard_AvailableRoles_LBI0T0").Click

driver.keys.Control
</code>

I am getting an error  "Invalid use of property". What am i doing wrong? I am guessing I have to use the <code>keys As New keys</code> in order to use the keyboard function right?

**Comment by bleeet** [comment]
correction: click the link and keep the option highlighted in order to select the another link for multiple selection

**Comment by florentbr** [comment]
The property keys.Control returns the Control character and doesn't do anything. In your case, it is standing on a single line and therefore raises the error "Invalid use of property". The Click method can take an option argument named "modifiers". So in your case, to click while holding the control key would be:

    driver.FindElementById("ctl00_ContentPlaceHolder1_PgCntrl_CreateUserWizard_AvailableRoles_LBI0T0").Click driver.Keys.Control
