### ISSUE TITLE
Get attributes of webelement / get xPath (or CSS selector)

### ISSUE THREAD

**Issue by longpants** [florentbr/SeleniumBasic#38]
Hi Florent,

New question. Is there a way to get all the attributes of a webelement?
If I dimension e as Webelement I can check the attributes: IsDisplayed, IsEnabled, IsSelected, tagname
within the control pane.
Of course, I can retrieve attributes with e.attribute, but I need to name the attribute.

I'm trying to help my users with creating an xpath / css selector. So if there is a way to retrieve an xpath location or css from the webelement, that's even better. (as input to locate the elements:)

Funcion getElements(searchString as String)
dim e as Webelement
dim driver as Webdriver
For each e in driver.FindElementsByXPath("//*[contains(text(),'" & searchString & "')]")
       listbox1.add e.text '&  "  " & e.xpath

Next 

Thanks!

**Comment by florentbr** [comment]
> New question. Is there a way to get all the attributes of a webelement?

Yes, here is an example:

    Const JS_LIST_ATTRIBUTES As String = _
      "var d={}, a=this.attributes;  " & _
      "for(var i=0; i<a.length; i++) " & _
      "  d[a[i].name]=a[i].value;    " & _
      "return d;                     "
    
    Sub ListAttributes()
      Dim driver As New FirefoxDriver
      driver.Get "https://en.wikipedia.org/wiki/Main_Page"
      Set elt = driver.FindElementById("mw-content-text")
      Set atts = elt.ExecuteScript(JS_LIST_ATTRIBUTES)
      For Each att In atts
        Debug.Print att.Key & "  " & att.Value
      Next
      driver.Quit
    End Sub
    
> I'm trying to help my users with creating an xpath / css selector. So if there is a way to retrieve an xpath location or css from the webelement, that's even better. (as input to locate the elements:)

The only way I know is by running some JavaScript:

    Const JS_BUILD_CSS As String = _
      "var e=this,p=[],h=function(a,s){if(!a||!s)return 0;for(var i=0,l=a.length;i<l;i" & _
      "++){if(s.indexOf(a[i])==-1)return 0};return 1;};for(;e&&e.nodeType==1;e=e.paren" & _
      "tNode){if(e.id){p.unshift('#'+e.id);break;}var i=1,u=1,t=e.localName,c=e.classN" & _
      "ame&&e.className.split(/[\s,]+/g);for(var s=e.previousSibling;s;s=s.previousSib" & _
      "ling){if(s.nodeType!=10&&s.nodeName==e.nodeName){if(h(c,s.className))c=null;u=0" & _
      ";++i;}}for(var s=e.nextSibling;s;s=s.nextSibling){if(s.nodeName==e.nodeName){if" & _
      "(h(c,s.className))c=null;u=0;}}p.unshift(u?t:(t+(c?'.'+c.join('.'):':nth-child(" & _
      "'+i+')')));}return p.join(' > ');"

    Const JS_BUILD_XPATH As String = _
      "var e=this,p=[];for(;e&&e.nodeType==1;e=e.parentNode){if(e.id){p.unshift('*[@id" & _
      "=\''+e.id+'\']');break;}var i=1,u=1,t=e.localName,c=e.className;for(var s=e.pre" & _
      "viousSibling;s;s=s.previousSibling){if(s.nodeType!=10&&s.nodeName==e.nodeName){" & _
      "if(c==s.className)c=null;u=0;++i;}}for(var s=e.nextSibling;s;s=s.nextSibling){i" & _
      "f(s.nodeName==e.nodeName){if(c==s.className)c=null;u=0;}}p.unshift(u?t:(t+(c?'[" & _
      "@class=\''+c+'\']':'['+i+']')));}return '//'+p.join('/');"

    Sub BuildLocators()
      Dim driver As New FirefoxDriver
      driver.Get "https://en.wikipedia.org/wiki/Main_Page"
      
      Set elements = driver.FindElementsByCss(".hlist")
      
      Set list_css = elements.ExecuteScript(JS_BUILD_CSS)
      For Each txt In list_css
        Debug.Print txt
      Next
      
      Set list_xpath = elements.ExecuteScript(JS_BUILD_XPATH)
      For Each txt In list_xpath
        Debug.Print txt
      Next
      
      driver.Quit
    End Sub


A better way would be to use the browser inspector to copy the selector.
You could also use a plugin:
https://chrome.google.com/webstore/search/selector?_category=extensions
https://addons.mozilla.org/fr/firefox/addon/firepath/?src=search
