### ISSUE TITLE
Problem with waiter.until<T> Method in VB6 (How to declare Delegate Functions in VB6)

### ISSUE THREAD

**Issue by zaka786khan** [florentbr/SeleniumBasic#39]
Hi florentbr! 
  Your work is really impressive! You make us possible to work with Selenium C# based to VBA, and Old versions of VisualBasic VB5, VB6 etc. 

I am confusing using waiter.until method in VB6. As in help file it says it Waits for delegate function to return not null or true. But in VB6 how do we declare such delegate function and pass it to waiter.until method?

Private driver As Selenium.WebDriver
Private waiter As Selenium.waiter
Private Assert As Selenium.Assert

Public Function allIFramesLoaded() As Boolean
    driver.SwitchToNextWindow
    Assert.Equals "New Window", driver.Title
    
    'Switch to the previous activated window
    driver.SwitchToPreviousWindow
    Assert.NotEquals "New Window", driver.Title
    allIFramesLoaded = True
End Function

Private Sub takeTest_Click()
    Set driver = New FirefoxDriver
    Set waiter = New Selenium.waiter
    Set Assert = New Selenium.Assert
    driver.get "http://the-internet.herokuapp.com/windows"
    ' code to check if all IFRames as loaded
    driver.FindElementByCss(".example a").Click
    waiter.Until allIFramesLoaded, 1
    Debug.Print "Website is loaded completely"
End Sub

![waiter-class-error](https://cloud.githubusercontent.com/assets/7099671/11523829/6998661c-98e7-11e5-8a00-c81cdb3aca33.png)

The command waiter.Until allIFramesLoaded, 1 returns error and says "Invalid argument at position 0. A function is expected.".

Please help me understand about how to use waiter.until method and how to declare such delegate function in VB6. Does VB6 supports delegate functions/actions if yes then how can we accomplish this. Thanks.

**Comment by florentbr** [comment]
In VBA a delegate function requires addressOf in front of the name:

    Function WaitDeleg1()
      WaitDeleg1 = True
    End Function
    
    Function WaitDeleg2(driver As WebDriver)
      WaitDeleg2 = True
    End Function
    
    Private Sub Main()
      Dim Waiter As New Waiter
      Dim driver As New FirefoxDriver
      
      ' without delegate
      While Waiter.Not(WaitDeleg1(), timeout:=2000): Wend
      While Waiter.Not(WaitDeleg2(driver), timeout:=2000): Wend
      
      ' with delegate
      driver.Until AddressOf WaitDeleg1, timeout:=2000
      Waiter.Until AddressOf WaitDeleg1, driver, timeout:=2000
      Waiter.Until AddressOf WaitDeleg2, timeout:=2000
    End Sub
