### ISSUE TITLE
PhantomJS driver Browser window.resize in VBA/VB6

### ISSUE THREAD

**Issue by zaka786khan** [florentbr/SeleniumBasic#40]
Dear florentbr!

Please help me know about how to resize phantomjs driver window size. I have tried all of the bellow: 

1) driver.manage.window.maximize 
2) driver.executeScript("window.resizeTo(1024, 768);"
3) driver.setCapability "screen-resolution", "1280x1024"

None of the above is working. I am using SeleniumBasic 2.0.6.

**Comment by florentbr** [comment]
To set the size:

    driver.Window.SetSize 800, 600

To maximize:

    driver.Window.Maximize
