### ISSUE TITLE
Check for compatibility of installed Firefox version with webdriver version used by SeleniumBasic

### ISSUE THREAD

**Issue by dornech** [florentbr/SeleniumBasic#41]
I wonder if there is an easy method to check without having Firefox started. Starting an incompatible Version ends in the calling VBA Programm stopping due to a timeout error or looping endless. Both is not really favourable :-)

**Comment by zaka786khan** [comment]
They are understood. I don't think Programmatically it is possible to know which firefox version is/can be supporting which webdriver version. You must hard-code your application in such way which SeleniumBasic version you are using in your application and which firefox version(s) are compatible in regards with your SeleniumBasic version. 

Dear dornech! if you have experience using SeleniumBasic please help me about how do I resize my browser window. I am using phantomjs with SeleniumBasic 2.0.6. Also possibly you may find any solution but I could not until now. Thanks.

**Comment by florentbr** [comment]
There's no easy way, but it should be compatible with all the latest versions of Firefox.
Do you have a specific falling version?

**Comment by dornech** [comment]
I thought I had a problem with Firefox 42 Portable. Same program running on the one machine with installed FF41 does not connect to FF on another machine with FF42 portable. i am quite sure that my routine for settign the binary capability works correct, it is well tested. From an internet source I understood that a new minor version of webdrive ris available / required to support FF42.

**Comment by dornech** [comment]
Others seem to have problems using sSelenium with FF 42 as well.
http://stackoverflow.com/questions/33706711/selenium-2-48-2-firefox-42-browser-not-getting-instantiated

**Comment by florentbr** [comment]
It works for me with Firefox 42 on Windows 8.1 x64:
https://download.mozilla.org/?product=firefox-42.0-SSL&os=win&lang=en-GB

Have you been able to reproduce this issue on a specific environment with a specific version of Firefox?
I can't fix something I can't reproduce.

**Comment by florentbr** [comment]
Closed due to inactivity
