### ISSUE TITLE
Can we add flash player plugin or support to SeleniumBasic2 with phamtomjs Ghost Driver

### ISSUE THREAD

**Issue by zaka786khan** [florentbr/SeleniumBasic#42]
I am working in SeleniumBasic2.0.6 with Ghost/Phantomjs driver. Doesn't it support Flash Player if i want to perform tests on video sites such as YouTube or any other site which needs Flash Player to be installed to play video. 

Please help me about can we add using capabilities of phantomjs or what is the best solution of it?

**Comment by florentbr** [comment]
It seems that the Phantomjs driver doesn't support plugins:
http://phantomjs.org/supported-web-standards.html
