### ISSUE TITLE
How to override PhantomJS onInitialized Global callback to run specific tasks every time new webpage is created but before a URL is loaded

### ISSUE THREAD

**Issue by zaka786khan** [florentbr/SeleniumBasic#44]
Hi Dear florentbr!

Thanks allot for replying last issues which I submitted due to being newbie. As I come to know that PhantomJS driver offers onInitialized callback is invoked after the web page is created but before a URL is loaded. The callback may be used to change global objects. 

I want to know how can we override this object to let our source/piece of code to be run every time once a new webpage object is created before the URL is loaded. I want to add some methods/functions to be run on webpage is created. 

for example clicking on a[_blank] link cause open new page but before created the new page my code may be run once.

As described at http://phantomjs.org/api/webpage/handler/on-initialized.html
var webPage = require('webpage');
var page = webPage.create();

page.onInitialized = function() {
  page.evaluate(function() {
    document.addEventListener('DOMContentLoaded', function() {
      console.log('DOM content has loaded.');
    }, false);
  });
};

But how do I add some code to be run once the webpage instance is initialized in SeleniumBasic 2.0.6 using VBA or VB6. 

Thanks

**Comment by florentbr** [comment]
The PhantomJS driver doesn't provide such capabilities with the Selenium API: 
http://stackoverflow.com/questions/24515944/phantomjs-through-selenium-in-python
