### ISSUE TITLE
keys.Enter not working anymore

### ISSUE THREAD

**Issue by martinoclaudio** [florentbr/SeleniumBasic#45]
Hello Florent,
I am a frequent user of your great tool and appreciate all the work you are doing.
With the new Version v2.0.6.0 of SeleniumBasic I am facing problems with my VBA code that was running just fíne with v2.0.5.0.
it seems to be that SendKeys (keys.Enter)is not recognized anymore.
Here is an excerpt of my code:

Public driver As New Selenium.FirefoxDriver
Public By As New By, Assert As New Selenium.Assert, Verify As New Selenium.Verify
Public Waiter As New Selenium.Waiter
Public Utils As New Selenium.Utils
Public keys As New Selenium.keys

driver.FindElementById("identifier", 3000).SendKeys (keys.Enter)

The code in the last line leads to an error.
Is there a bug in the new Version or am I doing something wrong in the code?

Thanks
Martin

**Comment by florentbr** [comment]
Could you provide:
 The version of your OS and browser.
 A reproducible example on a public website.
 The description of the error.

And please markdown any block of code to automatically format it.
Either add a 4 spaces indention or fence it with "\`\`\`vba" on the first line and "\`\`\`" on the last line.

**Comment by martinoclaudio** [comment]
Hi Florent,
Thanks for your quick reply!
I already found the cause. 
The binding 
```
Public keys As New Selenium.keys
```
did not work after the update. So keys.Enter did not work.
After deleting and retyping the binding VBA did the binding and now the program runs as before.

**Comment by florentbr** [comment]
The workbook stores the compiled VBA code in its file.
To force the workbook to compile the code again, you can either dereference and reference again the library or you can modify some code like your did.
