### ISSUE TITLE
Question: Does the webdriver provide means to highlight webelements in screenshot?

### ISSUE THREAD

**Issue by longpants** [florentbr/SeleniumBasic#48]
Hi Florent,

New question....
Suppose I run some assertion by the webdriver and assertion failes. Then I create a screenshot.
So far so good.

But since the X,Y and Width and Height parameters can be retrieved from the Webelement, is there a way to highlight this element within the screenshot by some (build-in) function?
(Either drawing a red rectangle or highlighting with yellow marker)

Kind regards,

Tom

**Comment by florentbr** [comment]
You could apply a style on the targeted element before taking the screenshot:
```vba
Dim drv As New FirefoxDriver
drv.Get "https://en.wikipedia.org/wiki/Eurytios_Krater"

Set ele = drv.FindElementById("searchInput")

' Apply a yellow outline
ele.ExecuteScript "window._so_=this.style.outline;this.style.outline='#FFFF00 solid 5px';"
' Take the screenshot
drv.TakeScreenshot().SaveAs ThisWorkbook.path & "\sc.png"
' Remove the outline
ele.ExecuteScript "this.style.outline=window._so_;"

drv.Quit
```

**Comment by longpants** [comment]
Perfect, I'll try that.
Thanks.
