### ISSUE TITLE
Default Unexpected Alert Behaviour Capability How to set for different webBrowsers in SeleniumBasic

### ISSUE THREAD

**Issue by zaka786khan** [florentbr/SeleniumBasic#49]
Hi Dear florentbr!

I have a problem in Selenium ver.2.0.6 probably being newbie. I don't know about how can we set default behavior for unexpected Alerts on websites/webpages. How can we set the default behavior for such unexpected behaviors i.e. For Firefox, I want to accept all unexpected alerts or dismiss all unexpected alerts. For Phantomjs etc. How to set such capabilities.

Also please It might be better for us If we can know all possible capabilities/preferences strings with possible values or value types. So, that We can search before submitting issue that does it can be solved by capabilities or not.

Thanks.

**Comment by florentbr** [comment]
To define the behaviour of alerts:
```vb
driver.SetCapability "unexpectedAlertBehaviour", "ignore"  ' other: accept, dismiss
```
I don't think PhantomJS supports alert dialog. You may have to override the function:
```vb
driver.ExecuteScript "window.confirm = function(){return true;}"
```
