### ISSUE TITLE
ChromeOptions

### ISSUE THREAD

**Issue by kappa10j** [florentbr/SeleniumBasic#5]
I currently use a .NET implementation to access a cef grid as follows:
ChromeOptions options = new ChromeOptions();
options.DebuggerAddress = "127.0.0.1:4000";
ChromeDriver driver = new ChromeDriver(options);

Is there a way to pass in options or will it be created?

**Comment by pmehrsam** [comment]
<b>Run-time error '429': ActiveX component can't create object</b>

I have the following setup in my Excel:
Tools -> References -> SeleniumWrapper Type Library

Here is the Excel code I'm running:
Option Explicit

Public Sub SeleniumTest()
Dim driver As New WebDriver
Set driver = CreateObject("WebDriver")
driver.Start "IE", "https://www.google.com/"

End Sub

I get this error on the "Set driver = CreateObject("WebDriver")" statement:  Run-time error '429': ActiveX component can't create object

I first "repaired" my installation of Excel from control panel.  Then I un-installed and re-installed Excel from control panel.  I'm still getting the error.

I don't have the admin rights or experience to manually edit my registry and DLL files.  Is there a way to fix this without getting too low level?

Thanks, Paul

**Comment by florentbr** [comment]
With a grid node:

    Dim driver As New ChromeDriver
    driver.StartRemotely "http://127.0.0.1:4444/wd/hub"
    driver.Get "https://www.google.co.uk"
    ...
    driver.Quit

or with a Chrome debug address :

    Dim driver As New ChromeDriver
    driver.SetCapability "debuggerAddress", "127.0.0.1:9333"
    driver.Get "https://www.google.co.uk"
    ...
    driver.Quit

Note that these examples will only work with the later version (v2.0.3.0)
