### ISSUE TITLE
Timeout.PageLoad doesn't work with Get method.

### ISSUE THREAD

**Issue by buruss** [florentbr/SeleniumBasic#50]
Hi, florentbr
Thank you for your hard work. 
I'm using SeleniumBasic v2.0.6.0. and 
When I call WebDriver.get("http://too_slow_webpage", 5000) with timeouts.PageLoad set to 5000,
It returns in 5 seconds as I expected, but Chrome dosn't stop loading the page.
So When I call another method or property of WebDriver again while Chrome is still loading that page,
my application gets blocked at this second call. 
Below is my code. 

Set Driver = New Selenium.ChromeDriver
With Driver.Timeouts
	.ImplicitWait = 3000
	.PageLoad = 5000
	.script = 5000
	.Server = 5000
End With
Call Driver.Start("chrome")
Driver.get("http://too_slow_webpage", 5000)

**Comment by florentbr** [comment]
> It returns in 5 seconds as I expected, but Chrome dosn't stop loading the page.

This is the expected behaviour since someone may want to wait for something while the page is still loading. To achieve this behaviour, you could stop the loading when the timeout is reached:

```vb
Dim drv As New ChromeDriver
drv.Timeouts.PageLoad = 1000
If Not drv.Get("file:///C:/pages/delayed.html", Raise:=False) Then _
	drv.ExecuteScript "window.stop();"

Debug.Assert 0
drv.Quit
```
