### ISSUE TITLE
Appium - Android Hybrid - unable to switch context to WebView using Selenium VB wrapper

### ISSUE THREAD

**Issue by bipo1980** [florentbr/SeleniumBasic#51]
Hello Florentbr:

This is my first communication with you and take this opportunity to Thank You for this wonderful tool.

I am currently using version 2.0.5.0. 
I used it for automating websites and also Android mobile apps using Appium.

Currently, i face a problem automating the WEBVIEW of an Android Hybrid App.
Appium tells me to switch context to the webview eg in other languages: driver.switch_to.context('WEBVIEW'). However - using the VB wrapper i dont know which method to use to perform this context switch. I have tried driver.SwitchToWindowByName etc... without results. 

Please help. 

thanks,
Bipo

**Comment by florentbr** [comment]
> Appium tells me to switch context to the webview eg in other languages: driver.switch_to.context('WEBVIEW'). However - using the VB wrapper i dont know which method to use to perform this context switch. I have tried driver.SwitchToWindowByName etc... without results.

The context command is specific to appium and not defined in the Selenium API:
https://github.com/appium/appium/blob/88e67ce987d78ce44de252219e07dc176a3511c2/docs/en/advanced-concepts/hybrid.md
http://www.w3.org/TR/webdriver/


You could try the "autoWebview" capabilty:

    driver.SetCapability "autoWebview", True
	
I'll see to add a generic method to send a command in the next release. It should look like this:

	driver.Send "POST", "/context", "name", "WEBVIEW"

**Comment by bipo1980** [comment]
@florentbr 
Thank you for the insight. For now will use the hard http post to achieve the switch.

Really looking forward to the generic method. From the sample command you have shown, it is also probably going to support all verbs and will return the response.

Many thanks again,
Bip

**Comment by florentbr** [comment]
The ability to send a customized command was added in release v2.0.7.0
Example:
```vb
driver.Send "POST", "/context", "name", "WEBVIEW"
```

**Comment by bipo1980** [comment]
Thank You once again @florentbr. It has been very helpful as usual.

Slipping in a question on the same to ask if i could use the same for making soap requests. If yes, can you provide an sample example how it should be like?
