### ISSUE TITLE
Adding Custom Referer Request Header for Chrome and Firefox using SeleniumBasic

### ISSUE THREAD

**Issue by zaka786khan** [florentbr/SeleniumBasic#52]
Hi! Dear Florentbr!
I just want to override or add referer request header. I searched a-lot for how to set custom referer with Firefox driver but I could not find any solution. However, for Phantomjs the working solution is as under.

driver.SetCapability "phantomjs.page.customHeaders.Referer", "$referer"

Please can we set custom referer request header for firfox, chrome or Internet Explorer web drivers using SeleniumBasic 2.0.6.
Thanks.

**Comment by florentbr** [comment]
You'll have to consider using an extension for that mater:
https://addons.mozilla.org/en-GB/firefox/search/?q=referer+request

To use an extension:
```vb
Dim driver As New FirefoxDriver
driver.AddExtension "c:\my-extension.xpi"
driver.SetPreference "my-extension.option", "whatever"
driver.Get "http://..."
```

**Comment by zaka786khan** [comment]
and what for Chrome please to override referer? Does this also needs to add extension in chrome please.
Also, how to apply chrome capabilities? or firefox capabilities in seleniumbasic please.

**Comment by zaka786khan** [comment]
furthermore, can we detect browser name from Selenium WebDriver object? I mean through get browser name from capabilities? I did not find any driver.Capabilities object?

**Comment by florentbr** [comment]
> and what for Chrome please to override referer? Does this also needs to add extension in chrome please.

Yes

> Also, how to apply chrome capabilities?

With the SetCapability method:
```vb
Dim driver As New ChromeDriver
driver.AddExtension "c:\my-extension.crx"
driver.SetCapability "key", value
driver.SetPreference "key", value
driver.Get "http://www..."
```

> furthermore, can we detect browser name from Selenium WebDriver object?

Yes:
```vb
Dim driver As New ChromeDriver
driver.Get "about:blank"
Debug.Print driver.Manage.Capabilities("browserName")
```

>Please your issue #19 is not enough descriptive about adding chrome extension.

I invite you to have a look in Examples.xlsm for a concrete example.

**Comment by zaka786khan** [comment]
First of All Thank you very much florentbr for replying. I checked Examples.xlsm. New examples have been added. It seems that all problems which we asked have been solved with examples in Examples.xlsm. Amazon Test Suite was also very helpful especially when you used WaitNotElement for us knowing best aproach to know how an element disappears.

I know that the question I am going to ask is not related to selenium issues but I have a question about some preferences. 
In firefox about:config has a list of all available options/settings/capabilites which we can set using selenium using the same name which shows in firefox. Firefox extensions use settings which shows in about:config.
In chrome there is no alternative of about:config however, it has some other settings pages like chrome:about chrome:flags etc. but which does not show the actual capabilites of the extensions to set.

For example, I used RefControl Firefox Extension to override referer. RefControl has uses refcontrol.actions capability to be set like @DEFAULT=http://customreferer. I was able to set RefControl default custom referer. the following command works fine in firefox.
driver.SetCapability "refcontrol.actions", "@DEFAULT=http://customreferer"

But in chrome, when I used Extension Referer Control. I was unable to know which capability does it use and I need to set through selenium to apply override referer. The question is how can we know the exactly capability name to set for a specific chrome extension however, in firefox we can watch change in about:config.

Thanks alot for solving problems, I will be more thankful if I have reply.

**Comment by florentbr** [comment]
The settings from a Chrome extension are stored in the local storage.
You can easily manage them with the Developper Tools in Chrome:
Developper Tools > Resources > Local Storage > chrome-extension://...

Unlike with Firefox it not possible to preset these settings with the SetCapability or SetPreference.
However, you can update them with a javascript call:
```vb
Dim driver As New ChromeDriver
driver.AddExtension "C:\Referer-Control_v1.16.crx"
driver.Get "chrome-extension://hnkcfpcejkafcihlgbojoidoihckciin/chrome/content/background.html"
driver.ExecuteScript "localStorage.setItem('key', 'value');"
```
