### ISSUE TITLE
Unable to run scripts which been running on previous day

### ISSUE THREAD

**Issue by devperera** [florentbr/SeleniumBasic#53]
Hi,

   My scripts was running without an issue but now its cant run and display an error.
   (I already off firewall and McAfee off)   

   Run-time error '-2146233078 (8013150a)':

   The source was not found, but some or all event logs could not be searched. Inaccessible logs:       Security.
   
..........
Thanks
Dev

**Comment by zaka786khan** [comment]
Did you uninstalled .Net Framework 3. It must be present weather you have installed .Net Framework 4.0 but you also need .Net Framework 3.5 to let Selenium runnable. I am not sure but I think this is the error number which it shows Run-time error '2146233078 (8013150a)' Automation Error and When I install .Net Framework it gonna work.

**Comment by devperera** [comment]
Hello,
        No I didn't uninstall the Framework 3.5 and its been already installed. Still dint know what happen.

...........
Thanks
Dev

**Comment by zaka786khan** [comment]
Hello devperera! 
Probably you should run your test with Administrator Privileges. Same problem solution I find at http://stackoverflow.com/questions/9564420/the-source-was-not-found-but-some-or-all-event-logs-could-not-be-searched. 

You can do this by right click and run as administrator.

**Comment by devperera** [comment]
Hello,
        When I set to run as admin, its show following error, opening the Excel file.
        There was a problem sending the command to the program.

.................
Thanks
Dev

**Comment by devperera** [comment]
Hello, 
        When I ran the Excel as administrator its gave following error message;
                  Run-time error '429':
                  ActiveX component can't create object
       VB Code is as below;
                 Sub Test()
                        Dim driver As New WebDriver
  
                       driver.Start "chrome", "https://www.google.com/"
                       driver.Window.Maximize
                       driver.Get "https://www.google.com/"
                       driver.Wait "1000"
    
                End Sub

....................
Thanks
Dev

**Comment by zaka786khan** [comment]
You must create object by using Set VB command. Probably you should code as follows also noticed you are passing string value to driver.Wait you should pass numeric value. The code may be following.

Sub Test()
  Dim driver as New WebDriver
  Set driver = New ChromeDriver
  driver.Window.Maximize
  driver.Get "https://www.google.com"
  driver. Wait 1000
End If

**Comment by devperera** [comment]
Hello Zaka,
                 Thanks for the reply but I still get the same error message with your code too. When i click debug option its shows
driver = <object veriable or with block veriable not set>

...............
Thanks
Dev

**Comment by zaka786khan** [comment]
Please ensure that you have added the reference to Selenium 2.0.6 and more clearly try as follows after adding reference to VBA or VB.

Sub Test()
 Dim driver as New Selenium.WebDriver
 Set driver = New Selenium.ChromeDriver
 driver.Window.Maximize 
 driver.Get "https://www.google.com"
 driver. Wait 1000
End If

**Comment by devperera** [comment]
Hi Zaka786khan,
                            Thanks you for your support. I have resolve the issue, I think browser had some malware's. I have done the Chrome browser configuration according to following site
http://www.malwareremovalguides.info/how-to-remove-adware-from-google-chrome/
Also I download and ran the below application which also mention on that site.
https://toolslib.net/downloads/viewdownload/1-adwcleaner/
So now my scripts are running as previously.

...................
Thanks
Dev

**Comment by florentbr** [comment]
@devperera:
The best way to get ride of malwares is to uninstall chrome completely and install it again. Using a third party tool usually install more crapware than it removes.

@Zaka786khan
Here is the correct way to instantiate the driver:

```vb
Dim driver As New Selenium.ChromeDriver
driver.Get "https://www.google.com"
```
Or:
```vb
Dim driver As Selenium.WebDriver
Set driver = New Selenium.ChromeDriver
driver.Get "https://www.google.com"
```
Or:
```vb
Dim driver As New Selenium.WebDriver
driver.Start "chrome"
driver.Get "https://www.google.com"
```

**Comment by rahul30m** [comment]
Hi...my name is Rahul,
I am also facing the same issues which Dev faced earlier. My Selenium Web automation VBA code worked just fine but all of a sudden it stopped working giving me weird errors..

1] ActiveX component can not be created
2] The source was not found but some or all logs could not be searched. Inaccessible logs: Security, State.

I have installed Office 365 and I have written following VBA Code in my Excel file.
I have also used Malware removal and it removed some applications installed by Dell for my Laptop maintenance and some other useless stuff, I have also reinstalled google chrome, but still the error persists. Kindly help me figure out where the  issue is.

I has .Net Framework 3.5 installed  earlier but its been replaced by higher version of .Net Framework when I installed Microsoft Visual Studio 2019... is that the cause of this issue?


The code which I have written is as follows:
******************************************************************************************
Private Keys As New Selenium.Keys

Sub GetEquityData()
Dim bot As New WebDriver



Dim InstruType As SelectElement

Dim symbol As SelectElement

Dim year As SelectElement

Dim expiryDate As SelectElement

Dim dateRange As SelectElement

Dim getButton As SelectElement

Dim series As SelectElement

Dim dataType As SelectElement



Dim InstrumentCodes() As Variant

Dim StockCodes() As Variant

Dim IndexCodes() As Variant

Dim OptionTypes() As Variant



Dim NiftyStrikePriceStart As Integer

Dim NiftyStrikePriceIncrement As Integer

Dim NiftyStrikePriceEnd As Integer



Dim BankNiftyStrikePriceStart As Integer

Dim BankNiftyStrikePriceIncrement As Integer

Dim BankNiftyStrikePriceEnd As Integer



StockCodes = Array("ACC", "ADANIENT", "ADANIPORTS", "ADANIPOWER", "AMARAJABAT", "AMBUJACEM", "APOLLOHOSP", "APOLLOTYRE", "ASHOKLEY", "ASIANPAINT", "AUROPHARMA", _

"AXISBANK", "BAJAJ-AUTO", "BAJAJFINSV", "BAJFINANCE", "BALKRISIND", "BANKBARODA", "BATAINDIA", "BEL", "BERGEPAINT", "BHARATFORG", "BHARTIARTL", _

"BHEL", "BIOCON", "BOSCHLTD", "BPCL", "BRITANNIA", "CADILAHC", "CANBK", "CENTURYTEX", "CESC", "CHOLAFIN", "CIPLA", "COALINDIA", "COLPAL", "CONCOR", _

"CUMMINSIND", "DABUR", "DIVISLAB", "DLF", "DRREDDY", "EICHERMOT", "EQUITAS", "ESCORTS", "EXIDEIND", "FEDERALBNK", "GAIL", "GLENMARK", _

"GMRINFRA", "GODREJCP", "GRASIM", "HAVELLS", "HCLTECH", "HDFC", "HDFCBANK", "HEROMOTOCO", "HINDALCO", "HINDPETRO", "HINDUNILVR", "IBULHSGFIN", _

"ICICIBANK", "ICICIPRULI", "IDEA", "IDFCFIRSTB", "IGL", "INDIGO", "INDUSINDBK", "INFRATEL", "INFY", "IOC", "ITC", "JINDALSTEL", "JSWSTEEL", "JUBLFOOD", "JUSTDIAL", _

"KOTAKBANK", "L&TFH", "LICHSGFIN", "LT", "LUPIN", "M&M", "M&MFIN", "MANAPPURAM", "MARICO", "MARUTI", "MCDOWELL-N", "MFSL", "MGL", "MINDTREE", "MOTHERSUMI", _

"MRF", "MUTHOOTFIN", "NATIONALUM", "NCC", "NESTLEIND", "NIITTECH", "NMDC", "NTPC", "OIL", "ONGC", "PAGEIND", "PEL", "PETRONET", "PFC", "PIDILITIND", "PNB", _

"POWERGRID", "PVR", "RAMCOCEM", "RBLBANK", "RECLTD", "RELIANCE", "SAIL", "SBIN", "SHREECEM", "SIEMENS", "SRF", "SRTRANSFIN", "SUNPHARMA", "SUNTV", "TATACHEM", _

"TATAGLOBAL", "TATAMOTORS", "TATAPOWER", "TATASTEEL", "TCS", "TECHM", "TITAN", "TORNTPHARM", "TORNTPOWER", "TVSMOTOR", "UBL", "UJJIVAN", "ULTRACEMCO", "UPL", _

"VEDL", "VOLTAS", "WIPRO", "YESBANK", "ZEEL")





bot.Start "Chrome", "https://www.nseindia.com"



bot.Get "/products/content/equities/equities/eq_security.htm"

bot.Window.Maximize

'bot.Wait 1000

  For a = LBound(StockCodes) To UBound(StockCodes)

       

        Set dataType = bot.FindElementById("dataType").AsSelect

        dataType.SelectByText "Security-wise Price volume & Deliverable position data"

                           

        Set series = bot.FindElementById("series").AsSelect

        series.SelectByText "EQ"

       

        Set dateRange = bot.FindElementById("dateRange").AsSelect

'       dateRange.SelectByText "3 months"

        dateRange.SelectByText "24 Months"

       

        bot.FindElementById("symbol").Clear

        bot.FindElementById("symbol").SendKeys (StockCodes(a))

        bot.Wait 3000

                           

       ''bot.FindElementByClass("getdata-button").Submit

         bot.FindElementById("getdata-button").Click

       

        bot.Wait 3000

       

        On Error GoTo Jump

        bot.FindElementByClass("download-data-link").Click

       

Jump:

    Resume Next

   

    Next a

   

' Stop

'bot.Wait 1000

'("FUTSTK")



End Sub

**********************************************************************


Regards
Rahul Desai
