### ISSUE TITLE
Error:23 - NoSuchWindowError Window not found. While Testing with Firefox Driver

### ISSUE THREAD

**Issue by zaka786khan** [florentbr/SeleniumBasic#54]
Often Selenium Test fails suddenly saying Error:23 - NoSuchWindowError Window not found. error. It seems that firefox is disconnected or unlinked with selenium which was working fine. No command further executes. 

What is the problem. Why testing fails while it was running smoothly but suddenly it seems that driver does not handshake any more with selenium and is disconnected/unlinked from sleniumbasic commands and does not/could not listen from selenium anymore even driver.quit or driver.close also does not work to kill the running instance. 

What is the solution if test goes failure due to this reason. What is the best practice to continue performing tests or re-link or close existing driver. 
Thanks.

**Comment by florentbr** [comment]
Please provide a concise and reproducible case on a public website with the result you are observing and the result you are expecting. You also need to provide the version of your OS, browser and release of this project.

**Comment by zaka786khan** [comment]
Dear florentbr!
I run tests using firefox 43 with SeleniumBasic 2.0.6. My seleniumdriver is unlinked with original firefox browser instance which itself initialized when the following occures which noticed. 

1) When it fails close unexpected alerts although I use the unexpectedAlertBehaviour to be dismissed. It seems but not sure that when alert shows with delay it can not handle alerts although the following command was issued. 

  driver.SetCapability "unexpectedAlertBehaviour", "dismiss"
But It accepts alerts however I issued command the alerts should be dismissed. This is separate issue.

2) Selenium Driver unlinks firefox driver sometimes when we use loop to close the rest windows except the primary window the following code I used.

For x = 2 to driver.Windows.Count
   driver.Windows.RemoveAt x
Next

**Comment by florentbr** [comment]
I can't fix a bug that I can't reproduce. So again, you have to provide a reproducible test case on a public website if you wish some support on this issue.

**Comment by dornech** [comment]
I encounter the same problem with some websites. I use the window counter to discove rnewly opened windows:
     i_Windows = objSelenium.Windows.Count
     objSelenium.DOSOMETHING
     If (i_Windows < objSelenium.Windows.Count) Then
         DOESOMETHING i. e. close windows
    End If

However, regarding ads: why do you not use adblocker in your webdriver instance ?
Installing a downloaded copy of the the respective xpi / crx file during webdriver start is straight forward. I provided sample code earlier.

**Comment by zaka786khan** [comment]
I checked/tested two methods of closing rest windows instead of one primary window.

Method 01:
For x = 2 to objDriver.Windows.Count
  objDriver.Windows.RemoveAt x
Next

Method 02:
For x = 2 to objDriver.Windows.Count
  objDriver.SwtichToNextWindow
  objDriver.Close
  objDriver.SwitchToPreviousWindow
Next x

The second method works fine or more efficiently and less chances produce error. However, there are more chances the first method may produces such error of NoSuchWindow Error. I am now using Method 02 and my application is not producing errors much more likely. 

Now RemoveAt is always producing the following error. 
  Run-time error '-2147024809 (80070057)': 
  Source array was not long enough. Check srcIndex and length, and the array's lower bounds.

I tried the following commands:
  driver.Windows.RemoveAt 0 
  driver.Windows.RemoveAt 1 
  driver.Windows.RemoveAt 2 

When driver.Windows.Count was 2. I run the test on page http://www.htmlcodetutorial.com/linking/linking_famsupp_170.html and clicked on My Popup button to have two windows open.

Thanks in advance

**Comment by florentbr** [comment]
First, the RemoveAt method is a List method and is one based. It doesn't close a window. It only removes the value from the list at the provided index. The following example ends with a list containing [32, 16]:
```vb
Dim lst As New List
lst.Add 32
lst.Add 12
lst.Add 76
lst.RemoveAt 2
```

Second, you shouldn't assume that your main window is the first one in the list since there is no strict order. Here is an example to close all the windows except one:
```vb
Private Sub Close_Windows()
  Dim driver As New FirefoxDriver
  
  driver.Get "http://the-internet.herokuapp.com/windows"
  
  ' Save the main window
  Set winMain = driver.Window
  
  ' Open a new window
  driver.FindElementByCss(".example a").Click
  
  ' Close all the newly opened windows
  For Each win In driver.Windows
    If Not win Is winMain Then win.Close
  Next
  winMain.Activate
  
  'Stop the browser
  driver.Quit
End Sub
```
