### ISSUE TITLE
New Tab should open instead New Window through driver

### ISSUE THREAD

**Issue by zaka786khan** [florentbr/SeleniumBasic#56]
Dear florentbr!

First of all thank you, that you listen to my problem/issues and feel better solving problems instead of being angry. As my all problem are answered and I am satisfy with your answers.

Is there any possible solution opening new tab instead of opening new window. Some websites open pop-up advertisements which cause new window to be opened. Hence, visiting this website once more causes too many windows open. It should better if new tab may open instead of new window. 

Is there any Capability or Preference to be set through driver that new window type links [target=blank] or pop-up ads may open in new tab instead of new window please?

Thanks.

**Comment by florentbr** [comment]
The Firefox documentation points to this preference:
http://kb.mozillazine.org/Browser.link.open_newwindow

This might work, though I haven't tested it:
```vb
Dim driver As New Selenium.FirefoxDriver
driver.SetPreference "browser.link.open_newwindow", 3
driver.Get "https://www.google.co.uk"
...
```

**Comment by zaka786khan** [comment]
Thanks for great support and I appreciate your work again
