### ISSUE TITLE
excel example in source code please (excel 97)

### ISSUE THREAD

**Issue by picpic020960** [florentbr/SeleniumBasic#59]
Bonjour
is it possible that excel examples in source code downloaded ?
my excel 97 can't open xlsm format

but i thinks that source code compatible with excel 97

super boulot
PS : si tu pouvais faire la même chose (enregistreur/convertisseur de selenium vers VBA) 
        pour sketchup vers ruby...

**Comment by florentbr** [comment]
Examples files are available in xls in the installation folder if your windows has an old version of Excel: %LOCALAPPDATA%\SeleniumBasic\Examples
