### ISSUE TITLE
command OK in selenium KO in VBA : workaround ?

### ISSUE THREAD

**Issue by picpic020960** [florentbr/SeleniumBasic#60]
Bonjour

this command is OK in selenium IDE with firefox
clickAndWait	

//img[@onclick="javascript:if (verifChampsObliNonSalarie() && verifDateModifNnSalarie('16/01/2017'))validerModificationNonSalarie('N');"]

but in excel VBA this message : 
'erreur d'exécution '32' '
InvalidSelectorError
Unable to locate an element with the xpath

command in VBA : 
' reference
'    driver.FindElementByXPath("//img[@onclick='javascript:if (verifChampsObliNonSalarie() && verifDateModifNnSalarie('16/01/2017'))validerModificationNonSalarie('N');']").Click

exists workaround ?

source screen : 

		<tr><td colspan="4" style="text-align:center;"><img src="img/btn_valider.gif" onclick="javascript:if (verifChampsObliNonSalarie() && verifDateModifNnSalarie('16/01/2017'))validerModificationNonSalarie('N');" /></td></tr>

thanks for help and work

Edit : 20.01.2016
----------------------

in example found usage_other in modules.bas and used Build_XPath_Locators()
then found my 'button'
and use driver.FindElementByXPath

**Comment by florentbr** [comment]
Not sure it's a good idea to locate an element based on the value of the @onclick attribute.
Anyway it makes sense that it doesn't work since your xpath from SeleniumIDE is different from the one in VBA:

```patch
- //img[@onclick="javascript:if (verifChampsObliNonSalarie() && verifDateModifNnSalarie('16/01/2017'))validerModificationNonSalarie('N');"]
+ //img[@onclick='javascript:if (verifChampsObliNonSalarie() && verifDateModifNnSalarie('16/01/2017'))validerModificationNonSalarie('N');']
```
The first one is using double quotes while the second one is using single quotes.
In VBA you need to add twice the double quote to escape it.
