### ISSUE TITLE
Assertion response KO, is this configurable?

### ISSUE THREAD

**Issue by longpants** [florentbr/SeleniumBasic#62]
Hi Florent,

Thanks again for your great work!
I'm getting more familiair with working XLS-SeleniumBasic-Webdriver. Great opportunities for my work as tester, I'm creating a small framework to integrate a few things (a mixup from Cucumbe/BDD framework, Excel and SeleniumBasic)

For the failed assertion response, is it possible to change the default 'KO' to 'NOK'?

**Comment by florentbr** [comment]
The KO and OK are constants from the Selenium.Verify object. They are not customisable as it is but you could easily wrap it in a VBA Class module to override the result. You could also write your own Verify object since it is not related to the drivers. All it does is basic comparison and messaging.

Is there any practical reason for this request?

**Comment by longpants** [comment]
Alright.
How can I wrap it in a Class? Create a Verify2 as you have shown CreateObject2?

The idea behind this is that I use the result message to inform the tester that step was OK or NOK. The practical thing is that I use the full return message from Verify, i.e.: "OK", ok "KO expected: xxxx actual: xxx", which is very confenient for logging. Only "KO" is a bit odd

**Comment by florentbr** [comment]
Insert a new Class Module named Verify and paste the code below:

```vb
Option Explicit

Dim ver As Selenium.Verify

Private Sub Class_Initialize()
  Set ver = New Selenium.verify
End Sub

Public Function Equals(expected, current) As String
  Equals = ver.Equals(expected, current)
  If Left(Equals, 2) = "KO" Then Equals = "NOK" & Mid(Equals, 3)
End Function
```

Then the usage remain the same:
```vb
Dim Verify As New Verify
Debug.Print Verify.Equals(1, 4)
```

I'll see to make the change since NOK seems to be way more common than KO.

**Comment by longpants** [comment]
Great! Works fine (although I created the object with CreateObject2, so creating a new instance of Verfiy needed a tweak to use the new Verify class)

But I think if you are able to change it, that would be nice indeed
