### ISSUE TITLE
Err.32: The result of the xpath expression .... is: [object Text]. It should be an element

### ISSUE THREAD

**Issue by longpants** [florentbr/SeleniumBasic#67]
Hi Florent,

Can you help me with this one?

Consider the following source code:
`<div>some text<span>something in between</span>other text</div>`

Using this xpath:
```
dim e as Webelement
dim driver as chromedriver
set e = driver.findElementByXpath("//div[contains(text(),'some text')]/text()[last()]")

```

Results in the following error (32):

InvalidSelectorError
invalid selector: The result of the xpath expression "////div[contains(text(),'some text')]/text()[last()]" is: [object Text]. It should be an element.
  (Session info: chrome=40.0.2214.111)
  (Driver info: chromedriver=2.12.301325 (962dea43ddd90e7e4224a03fa3c36a421281abb7),platform=Windows NT 6.1 SP1 x86_64)

Question:
How can I retrieve this last piece of text with purpose to Verify the text = 'other text'

**Comment by florentbr** [comment]
I would do that with a JavaScript call on the returned element:

```vb
txt = drv.FindElementByXPath("//div[contains(text(),'some text')]") _
         .ExecuteScript("return this.lastChild.textContent")
```

Or with an XPath in Javascript:

```vb
txt = drv.ExecuteScript("return document.evaluate(""" & _
           "//div[contains(text(),'some text')]/text()[last()]" & _
           """,document.body,null,2,null).stringValue")
```

Or with a regex:

```vb
  txt = drv.ExecuteScript("return document.body.innerHTML.match(" & _
                          "/some text<span>[^>]+.([^<]+)/g)[1]")
```

**Comment by dornech** [comment]
I wonder why you should not be able to use the standard XPath function 
last()

For reference see here:
http://www.w3schools.com/xsl/xsl_functions.asp

**Comment by longpants** [comment]
Although not able to as webelement: Good solution, thanks. 
@dornech : I'm able to use the last() function, but this doesn't return an Webelement, but String

**Comment by dornech** [comment]
Sorry, I did not read carefully enough.

While I like florentbr's first script solution I would have checked the 
rightmost part of findElementByXpath("//div[contains(text(),'some 
text')]").text
But yes, this would imply to check if any web element is found first and 
is much less elegant compared to florentbr's first script solution
