### ISSUE TITLE
Selenium VBA How to scroll down on a web page/ How to scroll till object get visible?

### ISSUE THREAD

**Issue by devperera** [florentbr/SeleniumBasic#68]
Hi,
    How to scroll down on a web page, or how to scroll down till web element get visible?

......................
Thanks
Dev

**Comment by florentbr** [comment]
Try with ScrollIntoView:
```vb
Dim drv As New FirefoxDriver
drv.Get "https://www.google.co.uk/search?q=snow"
drv.FindElementById("footcnt").ScrollIntoView

Debug.Assert 0
drv.Quit
```

**Comment by devperera** [comment]
Hi florentbr,

                 Thanks for the reply and I tried with that, on following line its gives an error.
                 drv.FindElementById("footcnt").ScrollIntoView
                  
                 Error is;
                 Run-time error '438':
                 Object doesn't support this property or method

                 Its seem that cannot find the ScrollIntoView method.
                 I am using SeleniumBasic-2.0.6.0.

......................
Thanks
Dev

**Comment by devperera** [comment]
Hello,

       Sorry I have to use latest version only that include above methods.

....................
Thanks
Dev
