### ISSUE TITLE
Selenium VBA; How to wait for web page to fully load

### ISSUE THREAD

**Issue by devperera** [florentbr/SeleniumBasic#69]
Hi,

   How to wait for web page to fully load, currently i am using "Wait" command which is not enough and sometime its get failed due to response time out.
  
.....................
Thanks 
Dev

**Comment by florentbr** [comment]
Please provide a concise and reproducible example and describe what results you are seeing and what results you expect. The driver already waits for completed status, so "fully loaded" is highly subjective for a dynamic page.

**Comment by devperera** [comment]
Hi Florentbr,

This is my example.

Dim driver As New WebDriver

  driver.Start 'chrome", "www.test.com"
  driver.Window.Maximize
  driver.Get "www.test.com"
  driver.Wait "1000"

  driver.FindElementById("myobject").Clear
  driver.FindElementById("myobject").SendKeys "this is testing"
  driver.Wait "1000"

Sometime my scripts get fail due to server response time out. How i need handle this issue.

................
Thanks
Dev

**Comment by florentbr** [comment]
Which line is throwing the error and what is the exact message?

**Comment by devperera** [comment]
Hi,

In following line
driver.Start 'chrome", "www.test.com"
I think some time server take more than time than expected.

................
Thanks
Dev

**Comment by florentbr** [comment]
You can try to increase the server timeout (60sec by default):

```vb
driver.Timeouts.Server = 120000  ' 2mins
```

Or you could set a timeout on the page loading:

```vb
driver.Timeouts.PageLoad = 20000           ' 20sec
driver.Get "www.test.com", raise:=false     ' set raise to false to avoid a timeout error
```

Moreover, you shouldn't use .Wait, it a bad practice. Try to wait for an element instead:
```vb
driver.FindElementById("myobject", timeout:=10000).Clear  '  implicit wait of 10sec
```

**Comment by devperera** [comment]
Hi Florentbr,
                    Thanks for the reply.

.....................
Thanks
Dev

**Comment by Ahmad9292** [comment]
Hi Florentbr,

I have 4 excel file where running by instance for 24 hour to check on the website by using selenium chrome. The excel frequently hang in backround where it hang on Start "Chrome".

I have try other way as well driver.get (url) but issue still persists.

Upon checked, once the drive start, sometime i can see a chromedriver running while chrome.exe not (usually should come out in the task manager as well). I have try disable plugins, unfortunately still the same issue occured.

My question, is there anyway to setup timeout or error handler for start chrome? ie: when start"chrome" taking longer time, hang or even chromedriver running without open chrome.exe?

Looking forward to your advise.

Thank you.

Regards
Ahmad

**Comment by Jmrumer** [comment]
I was having issues with timeouts when using .wait in my code. I switched to using the timeout method described above, but it broke my loop. Would the page load timeouts prevent excel from being able to move to the next "i" value? or cause the same block of code in my loop to trigger multiple times in a row without iteration? I ended up sending an email to the same contact 10 times before the debugger stopped progress but the only change I made was turning off the .waits and using timeout.

'''VBA
'loop through excel file and find each invoice then send emails
For i = 2 To lrow
    'set invoice number based on excel row
    invoiceNumber = Sheets("Invoice Report").Range("A" & i).Value
    
   'submit invoice number to webpage
    driver.Timeouts.PageLoad = 20000           ' 20sec
    driver.Get "https://[somewebsite]/#/EditInvoice/" & invoiceNumber, , False
    'Application.Wait Now + TimeValue("00:00:02")
    
   'click email icon
    driver.FindElementByClass("icon-envelope", timeout:=20000).Click
    'Application.Wait Now + TimeValue("00:00:02")
    'Ensure email is selected if it is not click on it
    If driver.FindElementByXPath("/html/body/div[6]/div[8]/div/div/div/form/div[2]/div/label[1]/input", timeout:=20000).IsSelected <> True Then
        driver.FindElementByXPath("/html/body/div[6]/div[8]/div/div/div/form/div[2]/div/label[1]/input", timeout:=20000).Click
        'Application.Wait Now + TimeValue("00:00:02")
    Else
        'click send for email already selected
        driver.FindElementByXPath("/html/body/div[6]/div[8]/div/div/div/form/div[8]/button", timeout:=20000).Click
        'Application.Wait Now + TimeValue("00:00:02")
    End If
    
    'send email after clicking 1st email option
    driver.FindElementByXPath("/html/body/div[6]/div[8]/div/div/div/form/div[8]/button", timeout:=20000).Click
    'Application.Wait Now + TimeValue("00:00:02")
    
Next i

driver.Quit
End Sub
'''

Thanks,
Jay
