### ISSUE TITLE
Issue with the StartBrowser sub in the 'Selenium.xlsm' example

### ISSUE THREAD

**Issue by nevokron** [florentbr/SeleniumBasic#7]
Hi!
Playing around with the example file "Selenium.xlsm' in order to learn using SeleniumBasic, I encountered the following issue. In the module "SeleniumScripts", I substituted the line 'Dim driver As New FirefoxDriver' with a call to the sub StartBrowser (present in the module "SeleniumBrowsing"). But when I run the macro, I get the error "Object required". What can be the problem? Thanks!
Nev

**Comment by florentbr** [comment]
The problem is that you removed the line "Dim driver As New FirefoxDriver"
This line creates the FirefoxDriver object.

This code:

    Dim driver As New FirefoxDriver
    driver.Get "http://www..."

Is equal to:

    Dim driver As FirefoxDriver
    Set driver = New FirefoxDriver
    driver.Get "http://www..."

**Comment by nevokron** [comment]
Thanks for the answer!
Yes, I removed the line "Dim driver As New FirefoxDriver", BUT it is contained in the sub StartBrowser, so why it should not work? What are the subs contained in the module "SeleniumBrowsing" then for?
In any case, my final intention is to reuse the same browser session across the script, but, while it was possible with the old "Selenium-vba", it doesn't seem to work with this new Selenium Basic. Could you maybe provide an example where the same browser session is used within different subs in an excel vba script?
Thanks!
Nev

**Comment by nevokron** [comment]
For example, I was modifying the code like this, in order to reuse the firefox session (created when  pressing the button "Verify Titles") in the sub "List Links":

    Public Sub VerifyTitles()

    Dim Table As New Table, Verify As New Verify
    Set driver = CreateObject("Selenium.FirefoxDriver")
   
    Dim row
    For Each row In Table.From([Sheet1!A1]).Where("Id > 0")
        'open the page with the link in column "Link"
        driver.Get row("Link")
        
        'Verify the title and set the result in column "Result"
        row("Result") = Verify.Equals(row("ExpectedTitle"), driver.Title)
    Next
 
    End Sub


    Public Sub ListLinks()

    Dim driver As FirefoxDriver
    Set driver = GetObject("Selenium.WebDriver")
    'open the page with the URL in Sheet2 in cell A2
    driver.Get [Sheet2!A2]
    
    'get all the href attributes
    Dim links As List
    Set links = driver.FindElementsByTagName("a").Attribute("href")
    
    'writes the href values in a worksheet
    links.ToExcel [Sheet2!A5]
       
    End Sub

But when I press "List links" I get the following error, on the line "driver.Get [Sheet2!A2]": 

Run-Time error '0':
WebRequestError:
Unable to connect to the remote server 

What's going wrong? Many thanks!
Nev

**Comment by dornech** [comment]
I do not see quite well why using a global Selenium Webdriver object across multiple subs/functions should not work if properly called "ByRef". Beacause I do exactly this :-)
However, you must not define the WebDriver object multiple times with "As New".

Regarding your Problem "driver.Get [Sheet2!A2]":
I think this is not a SeleniumBasic Issue but a General VBA syntax issue. 
I'd expect that driver.get worksheets("Sheet2").cells(2,2) works.

**Comment by nevokron** [comment]
> I do not see quite well why using a global Selenium Webdriver object across multiple subs/functions should not work if properly called "ByRef". Beacause I do exactly this :-)

May you please paste a simple working example? (maybe a modification of the above reported example). Thanks!

>Regarding your Problem "driver.Get [Sheet2!A2]":
>I think this is not a SeleniumBasic Issue but a General VBA syntax issue.
>I'd expect that driver.get worksheets("Sheet2").cells(2,2) works.

No, it is not a general VBA syntax issue, as in the original version (where it opens a new browser window) it works. I even try to replace the  line with the one you suggested (by the way, it would be '...cells(2,1)' ), but I get the same error... So it has to be something more subtle (or so huge that I cannot realize it :) ).

Thanks,
Nev

**Comment by florentbr** [comment]
You are getting this error because the driver has been disposed.
The previous version was taking advantage of a leak that is now fixed since version v2.0.3.0
The driver is now disposed as soon as its variable is no longer used or set to Nothing.

In your example, the variable driver is only used in the procedure and is therefore disposed when the execution exists the procedure.
To keep the driver alive between calls, the variable must be declared outside of the procedure:

    Private driver As WebDriver
    
    Public Sub NavigateToURL1()
        If driver Is Nothing Then _
            Set driver = New FirefoxDriver
        
        driver.Get "http://stackoverflow.com"
    End Sub
    
    Public Sub NavigateToURL2()
        If driver Is Nothing Then _
            Set driver = New FirefoxDriver
            
        driver.Get "https://m.facebook.com"
    End Sub
    
    Public Sub DisposeDriver()
        If Not driver Is Nothing Then Exit Sub
        driver.Quit
        Set driver = Nothing
    End Sub


Another way is to start the browser with one of the provided VBScript (StartFirefox.vbs) and retrieve the instance with GetObject.
This way the driver stays alive even if excel is closed and reopen.

To start an individual instance :
  Run the file StartFirefox.vbs

To use the instance in Excel:

Public Sub OpenURL()
    Dim driver As WebDriver
    Set driver = GetObject("Selenium.WebDriver")
    driver.Get "https://www.google.co.uk"
End Sub

**Comment by nevokron** [comment]
> Private driver As WebDriver

Yes, that was it!

Many thanks for the explanation and for the clarifications on the other possibility!

P.S.: Out of curiosity, what is the difference between 

  driver.Quit
  Set driver = Nothing

and

  driver.Close

?

**Comment by florentbr** [comment]
driver.Quit

Terminates the process of the driver and the process of the browser and deletes the temporary profile.

    Set driver = Nothing

Setting a variable to Nothing decrements the reference count on the object that was assigned to it.
Once the reference count reaches 0, the object is set for garbage collection.
It's an explicit way of disposing of an object. It should only be used on global/static variables.

    driver.Close

Closes the current window or tab. Should only be used to close a second window or tab

**Comment by dornech** [comment]
I am afraid I am a little bit behiond schedule to expand on my comment regarding using a (global) Selenium Webdriver object across multiple subs/functions.

I was used to remotly control IE via MSHTML library but switched to Selenium recently. I use th mechanism to download data from the internet directly into EXCEL or to download PDFs form the internet. For using Selenium I  developed a module doing some initialization stuff like determining the binary location, loading of extensions or setting params (i. e. direct PDF download).

the module looks like this:

Option Explicit



'------------------------------------------------------------------------------------
' constant definitions
'------------------------------------------------------------------------------------


' constants for checking location of browser binaries

Const _
   s_RegKey_AppPaths = "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths", _
   s_RegKey_BrowserBinary_Chrome = "chrome.exe", _
   s_RegKey_BrowserBinary_Firefox = "firefox.exe"



'------------------------------------------------------------------------------------
' determine and set browser binary location
'------------------------------------------------------------------------------------


' check/determine location for browser binary via checking registry keys
' - HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\firefox.exe
' - HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe
Function checkBrowserBinaryLocation(ByVal s_WebDriver_Browser As String) As Boolean

   Dim _
      s_RegKey_BrowserBinary As String, _
      s_RegValue_BrowserBinary As String, _
      b_FileExists As Boolean

   If (s_WebDriver_Browser = "chrome") Then
      s_RegKey_BrowserBinary = "chrome.exe"
   ElseIf (s_WebDriver_Browser = "firefox") Then
      s_RegKey_BrowserBinary = "firefox.exe"
   Else
      Call MsgBox("Currently only Chrome and Firefox are supported.", vbOKOnly)
   End If

   s_RegValue_BrowserBinary = RegReadWSShell(s_RegKey_AppPaths & "\" & s_RegKey_BrowserBinary & "\")

   b_FileExists = False
   If (s_RegValue_BrowserBinary <> vbNullString) Then
      b_FileExists = FileExists(s_RegValue_BrowserBinary)
      If Not b_FileExists Then
         Call MsgBox("Browser binary not found at location defined in registry.", vbOKOnly)
      End If
   End If

   checkBrowserBinaryLocation = (s_RegValue_BrowserBinary <> vbNullString) And b_FileExists

End Function


' determine location of browser binary for portable installation
Sub determineBrowserBinaryLocation(ByRef objSelenium As Selenium.WebDriver, ByVal s_WebDriver_Browser As String, Optional ByVal s_StartSearch_BrowserBinary As String)

   Dim _
      s_BrowserBinary_EXE As String, _
      s_BrowserBinary_Path As String

'  check if requested browser is installed, if not search for portable installation
   If Not checkBrowserBinaryLocation(s_WebDriver_Browser) Then

'     define binary filename to look for
      If (s_WebDriver_Browser = "chrome") Then
         s_BrowserBinary_EXE = "chrome.exe"
      ElseIf (s_WebDriver_Browser = "firefox") Then
         s_BrowserBinary_EXE = "firefox.exe"
      End If

'     search for browser binary
      s_BrowserBinary_Path = findPath(s_BrowserBinary_EXE, s_StartSearch_BrowserBinary, True)
      If Not FileExists(s_BrowserBinary_Path & "\" & s_BrowserBinary_EXE) Then
         Call MsgBox(s_BrowserBinary_EXE & " not found. Programm stopped.")
         Stop
      End If

'     set binary capability
      objSelenium.SetBinary s_BrowserBinary_Path & "\" & s_BrowserBinary_EXE

   End If

End Sub



'------------------------------------------------------------------------------------
' routine to start Selenium Driver
'------------------------------------------------------------------------------------

Sub initializeSeleniumDriver(ByRef objSelenium As Selenium.WebDriver, ByVal s_WebDriver_Browser As String, Optional ByVal s_URL As String, Optional ByVal s_BrowserExtensions As Variant, Optional ByVal s_BrowserPrefs As Variant)

   Dim _
      i_Idx As Integer, _
      s_BrowserExtensionFile As String

'  determine location of browser binary
   Call determineBrowserBinaryLocation(objSelenium, s_WebDriver_Browser)

'  install requested browser extensions
'  used to install f. e. AdblockPlus
   If IsArray(s_BrowserExtensions) Then
      For i_Idx = LBound(s_BrowserExtensions) To UBound(s_BrowserExtensions)
         s_BrowserExtensionFile = determineBrowserExtensionFile(s_WebDriver_Browser, s_BrowserExtensions(i_Idx))
         If (s_BrowserExtensionFile <> vbNullString) Then
            If FileExists(s_BrowserExtensionFile) Then
               objSelenium.AddExtension s_BrowserExtensionFile
            End If
         End If
      Next
   End If

'  set requested browser preferences
   If IsArray(s_BrowserPrefs) Then
      For i_Idx = LBound(s_BrowserPrefs) To UBound(s_BrowserPrefs)
         If (s_BrowserPrefs(i_Idx)(0) <> vbNullString) Then
            objSelenium.SetPreference s_BrowserPrefs(i_Idx)(0), s_BrowserPrefs(i_Idx)(1)
         End If
      Next
   End If

'  start WebDriver ...
   objSelenium.Start s_WebDriver_Browser, "about:blank"
'  ... close additional windows opened by browser extensions loaded ...
   While (objSelenium.Windows.Count > 1)
      objSelenium.Window(objSelenium.Windows.Count).Close
   Wend
'  ... and go to start URL
   If (s_URL <> vbNullString) Then
      objSelenium.get s_URL
'     objSelenium.get "/"
   End If

End Sub


' determine file for browser extension depending on webbrowser
Function determineBrowserExtensionFile(ByVal s_WebDriver_Browser As String, ByVal s_BrowserExtension As String, Optional ByVal s_StartSearch_BrowserExtension As String) As String

   Dim _
      s_Path As String, _
      s_Filename As String, _
      s_Name As String, _
      s_Extension As String

   determineBrowserExtensionFile = vbNullString

   If FileExists(s_BrowserExtension) Then

      determineBrowserExtensionFile = s_BrowserExtension

   Else

      Call Split_FullFilename(s_BrowserExtension, s_Path, s_Filename)
      Call Split_Filename(s_Filename, s_Name, s_Extension)

      If (s_WebDriver_Browser = "chrome") Then
         s_Extension = "crx"
      ElseIf (s_WebDriver_Browser = "firefox") Then
         s_Extension = "xpi"
      Else
         Call MsgBox("Currently only Chrome and Firefox are supported.", vbOKOnly)
      End If
      s_Filename = s_Name & "." & s_Extension

      If (s_Path <> vbNullString) Then
         s_Path = findPath(s_Filename, s_Path, False)
      End If
      If (s_Path <> vbNullString) Then
         determineBrowserExtensionFile = s_Path & "\" & s_Filename
      Else
         If (s_StartSearch_BrowserExtension = vbNullString) Then s_StartSearch_BrowserExtension = TempDir()
         s_Path = findPath(s_Filename, s_StartSearch_BrowserExtension, True)
         If (s_Path <> vbNullString) Then
            determineBrowserExtensionFile = s_Path & "\" & s_Filename
         End If
      End If

   End If

End Function



'------------------------------------------------------------------------------------
' set browser parameters for direct download
'------------------------------------------------------------------------------------


' generate array-constant with necessary browser parameters -> for new Selenium WebDriver starter
Function BrowserPrefs_directDownload(ByVal s_WebDriver_Browser As String, ByRef s_Path As String) As Variant

'  check/determine path for direct download
   If (s_Path = vbNullString) Or Not DirExists(s_Path) Then
      s_Path = TempDir()
   End If

   If (s_WebDriver_Browser = "chrome") Then
      BrowserPrefs_directDownload = Array( _
         Array("download.default_directory", s_Path), _
         Array("download.prompt_for_download", False), _
         Array("plugins.plugins_disabled", Array("Chrome PDF Viewer")) _
      )
   ElseIf (s_WebDriver_Browser = "firefox") Then
      BrowserPrefs_directDownload = Array( _
         Array("browser.download.folderList", 2), _
         Array("browser.download.dir", s_Path), _
         Array("browser.helperApps.neverAsk.saveToDisk", "application/pdf"), _
         Array("pdfjs.disabled", True) _
      )
   End If

End Function


' set browser parameters in WebDriver object
Sub setBrowserProfile_directDownload(ByRef objSelenium As Selenium.WebDriver, ByVal s_WebDriver_Browser As String, ByRef s_Path As String)

'  check/determine path for direct download
   If (s_Path = vbNullString) Or Not DirExists(s_Path) Then
      s_Path = TempDir()
   End If

'  set browser parameters
   If (s_WebDriver_Browser = "chrome") Then
      objSelenium.SetPreference "download.default_directory", s_Path
      objSelenium.SetPreference "download.prompt_for_download", False
      objSelenium.SetPreference "plugins.plugins_disabled", Array("Chrome PDF Viewer")
   ElseIf (s_WebDriver_Browser = "firefox") Then
      objSelenium.SetPreference "browser.download.folderList", 2
      objSelenium.SetPreference "browser.download.dir", s_Path
      objSelenium.SetPreference "browser.helperApps.neverAsk.saveToDisk", "application/pdf"
      objSelenium.SetPreference "pdfjs.disabled", True
   End If

End Sub


' deactivate internal Chrome-PDF-Viewer (if Chrome was started already)
' -> note dependency on a) XPath and brwoser language
Sub deactivatePDFinternal_Chrome(ByRef objSelenium As Selenium.WebDriver, ByRef objSeleniumBy As Selenium.By)

   Dim _
      s_URL As String

   s_URL = objSelenium.url
   objSelenium.get "chrome://plugins"

   If objSelenium.IsElementPresent(objSeleniumBy.XPath("//td[div[@class='plugin-text']/div/span[.='Chrome PDF Viewer']]/div[@class='plugin-actions']/span/a[.='Deaktivieren']")) Then
      objSelenium.FindElementByXPath("//td[div[@class='plugin-text']/div/span[.='Chrome PDF Viewer']]/div[@class='plugin-actions']/span/a[.='Deaktivieren']").Click
   End If

   objSelenium.get s_URL

End Sub

The calling routine looks like this:

Sub callingsomething

   Dim _
      objSelenium As New Selenium.WebDriver, _
      objSeleniumBy As New Selenium.By, _
      ...

     Call initializeSeleniumDriver(objSelenium, s_WebDriver_Browser, s_URL, Array("adblockplus"))

...

End Sub

You may noted that the driver object from the calling routine is pasey by reference to the sub initializeSeleniumDriver. This works without problem (as it should)
