### ISSUE TITLE
waitForElementPresent for element by xpath position

### ISSUE THREAD

**Issue by ItamarBranovate** [florentbr/SeleniumBasic#70]
Hi,
I'm try to use xpath selector to find elements by position using the waitForElementPresent function
and i get error that element not found.
if i try to "click" the element it success
and the selector work in chrome-dev-tool very well.
the error occured only in waitForElementPresent  function.

i'm using chrome driver and the code in vba.
xpath example:
(//div[@class='test'])[4]     - (in chrome dev tool no need the brackets)
anyone can help me please?
thanks.

**Comment by dornech** [comment]
Do you use a By-object as argument for waitForElementPresent ?

BTW: detailled code and screenshot of error would be helpful.

**Comment by ItamarBranovate** [comment]
Hi,
I'm not using the By object.
that how i call the function:
driver.waitForElementPresent ("(//td/a[text()='" & end_day & "'])[2]")
this is the error that i get

![waitforelemntpresent](https://cloud.githubusercontent.com/assets/16069886/12917054/b3ef648e-cf3f-11e5-9b48-86000ee3e2de.jpg)

thanks for help.

**Comment by florentbr** [comment]
The waitForElementPresent method belongs to the old project "selenium-vba" which is deprecated and no longer supported.

In this project, there is an implicit wait time of 3 seconds by default when trying to find elements:
    
    Set ele = driver.FindElementByXPath("xpath expression")

To adjust the waiting time individually:
    
    Set ele = driver.FindElementByXPath("xpath expression", timeout:=10000) ' 10 sec

To adjust the waiting time globally:
    
    driver.Timeouts.ImplicitWait = 5000  ' 5 sec


To just wait for the presence of an element:
    
    driver.FindElementByXPath "xpath expression", timeout:=10000

To just wait for the non presence of an element:
    
    driver.WaitNotElement By.XPath("xpath expression"), timeout:=10000
