### ISSUE TITLE
VBA SeleniumWrapper error

### ISSUE THREAD

**Issue by arhellman** [florentbr/SeleniumBasic#72]
Hello, 

I did the full install of your latest version of Selenium Basic, and am using the latest Firefoxplugin Format IDE VBA  and Selenium IDE 2.9.1.

Thanks for the great program. I think I have however found a small bug on the VBA side of the COM. 
When you add the reference in VBA (Excel/Access) it is now called Selenium Type Library. And not SeleniumWrapper Type Library.

I noticed some of the functionality from the examples and the IDE format plugin are now gone, so the VBA will throw an error on .click or .open for example. 

So if you have:
Dim selenium As New Selenium.WebDriver  (SeleniumWrapper does not exist)

   selenium.start "ie", "http://www.google.com/"
   selenium.open "/"
   selenium.type "name=q", "Eiffel tower"
   selenium.click "name=btnG"

It will throw the error immediately on .open because that functionality is not there and it will create a blank page.

This could very well just be ignorance on my part. I'm reading through the API documentation now and have been able to get it to work by grabbing the webelements. I was previously just trying to copy and paste the VBA from the source tab on the IDE plugin when running the web macro/script with the IDE 2.9.1.

**Comment by florentbr** [comment]
The driver.open, driver.click and driver.type commands are from the old Selenium 1 API and this project only implements the Selenium 2.0 API.
Here is your example with the Selenium 2 API :

```vb
Dim driver As New Selenium.IEDriver
driver.Get "http://www.google.com/"
driver.FindElementByName("q").SendKeys "Eiffel tower"
driver.FindElementByName("btnG").Click
```
