### ISSUE TITLE
Sometimes RemoteServer.SendRequest hangs.

### ISSUE THREAD

**Issue by buruss** [florentbr/SeleniumBasic#75]
Sometimes code stops infinitly at "response = (HttpWebResponse)request.EndGetResponse(asyncResult);" in RemoteServer.SendRequest.

It might be an error from chromedriver. but I think it wouldn't be harmful to cope with this situation.

I found out that this problem occurs only when "asyncResult.AsyncWaitHandle.WaitOne(timeout)" code returns "false" by timeout. I tested "WaitOne" with "timeout" argument.

I think throwing an error at this situation might be helpful. 
Thank you for your hard work.

**Comment by florentbr** [comment]
I found out that the timeout defined on the request has no effect when the request is handled asynchronously.
I'll fix it for the next release.

**Comment by florentbr** [comment]
Fixed in v2.0.9.0
