### ISSUE TITLE
Dictionary method of Selenium.Application returns a List

### ISSUE THREAD

**Issue by zoobab2701** [florentbr/SeleniumBasic#76]
When using Application object in VBA to create Dictionary, the method returnd wrong type : "List" instead of "Dictionary"
![capture](https://cloud.githubusercontent.com/assets/17180331/12980847/81729fc6-d0de-11e5-9d6b-398113b3b391.PNG)

**Comment by florentbr** [comment]
Fixed in v2.0.9.0
