### ISSUE TITLE
Assistance with SeleniumBasic commands

### ISSUE THREAD

**Issue by sdp1019** [florentbr/SeleniumBasic#78]
Thanks again for your response! I am now using the newest SeleniumBasic. However, I still have a few questions. How do I do the equivalent of driver.openWindow, and how would i tell it to clickandwait? 

What I am really trying to do is to open a new tab, and then work in that tab, and then continue to the next tab until all the tabs are loaded with the right data from excel. I have no need to move back to the parent tab.

It also closes the window at the end of my code even though I have no driver.quit in the code.

`Sub Macro6()
'
' Macro6 Macro
'
    Dim driver As New selenium.IEDriver, Keys As New selenium.Keys
    
    
        driver.Get "https://simcontrolcenter.wireless.att.com/provision/ui/terminals/sims/sims.html"
        driver.FindElementByName("j_username").SendKeys "spalmer"
        driver.FindElementByName("j_password").SendKeys "ticktock"
        driver.FindElementByXPath("//input[@type='submit']").Submit
    
    For i = 1 To 3
      
        driver.Get "https://simcontrolcenter.wireless.att.com/provision/ui/terminals/sims/sims.html", 0
        driver.FindElementByName("oneBox").SendKeys (Worksheets("Sheet1").Cells(i + 1, 2).Value)
        driver.FindElementById("button-1101-btnEl").Click
        
        
       i = i + 1
      
    Next i

End Sub`

**Comment by florentbr** [comment]
> how do I do the equivalent of driver.openWindow

Either hold the control key while clicking:
```vb
driver.FindElementByLinkText("Dropdown").Click Keys.Control
driver.SwitchToNextWindow
```
Or with some Javascript:
```vb
driver.ExecuteScript "window.open()"
driver.SwitchToNextWindow
```


> how would i tell it to clickandwait?

There is no need. The driver automatically waits for the page to be loaded.
Moreover the driver tries to locate the targeted element during 3sec before raising an error.
To adjust the timeout globally:
```vb
driver.Timeouts.ImplicitWait = 4000  ' 4 sec '
```
To adjust the timeout locally:
```vb
driver.FindElementById("id", timeout:=4000).Click
```


> It also closes the window at the end of my code even though I have no driver.quit in the code.

The driver quits when its variable is no longer used. So to keep it running, you'll have to declare it globally:
```vb
Private driver As New Selenium.FirefoxDriver
Private Assert As New Selenium.Assert
Private Verify As New Selenium.Verify
Private Waiter As New Selenium.Waiter
Private Utils As New Selenium.Utils
Private Keys As New Selenium.Keys
Private By As New Selenium.By

Public Sub Main()
  driver.Get "..."
End Sub

Public Sub QuitDriver()
  driver.Quit
  Set driver = Nothing
End Sub

```
