### ISSUE TITLE
AddExtension does not work with FireFox

### ISSUE THREAD

**Issue by dornech** [florentbr/SeleniumBasic#8]
I tried to use the addExtension method to install extensions for the webdriver firefox instance. Does not work. xpi-file is stored locally.

**Comment by florentbr** [comment]
Could you provide an example with a specific extension to reproduce?
I've fixed some issues on the last release (v2.0.3.0) regarding the usage of extensions.
It may be related.

Here is a usage example with firebug:

    Dim driver As New FirefoxDriver
    driver.AddExtension "C:\Users\florent\Downloads\firebug-2.0.11-fx.xpi"
    driver.Get "https://www.google.co.uk"
    driver.Quit

**Comment by dornech** [comment]
solved with update. great work. thanks!
