### ISSUE TITLE
syntax for is isElementPresent

### ISSUE THREAD

**Issue by bleeet** [florentbr/SeleniumBasic#80]
Hi 

I am trying to make a if statement with isElementPresent but I am getting the syntax wrong. I am wondering what is the correct syntax?

here is what I have

`If chromex.isElementPresent ("ID = ctl00_ContentPlaceHolder1_PgCntrl_CreateUserWizard") Then`

thanks

**Comment by longpants** [comment]
Hi Bleet,
You need to tweak it like this:
`If webDriver.IsElementPresent(by, timeout) Then`

In which by can be and Id, like your example: `By.Id(id as String)`

So to conclude:
`If webDriver.IsElementPresent(By.Id("ctl00_ContentPlaceHolder1_PgCntrl_CreateUserWizard", timeout) Then`

And therefore you need to initialize webDriver and By:
`Dim webDriver as ChromeDriver`
`Dim by as By`

**Comment by longpants** [comment]
Or check also [](https://github.com/florentbr/SeleniumBasic/issues/78)

**Comment by florentbr** [comment]
Either:

```vb
Dim drv As New FirefoxDriver
drv.Get "https://www.google.co.uk"

Dim ele As WebElement
Set ele = drv.FindElementByCss("#id", timeout:=0, raise:=False)
If ele Is Nothing Then
  Debug.Print "not present"
Else
  Debug.Print "present"
End If
```

Or:

```vb
Dim drv As New FirefoxDriver, By As New By
drv.Get "https://www.google.co.uk"

If drv.IsElementPresent(By.Css("#id")) Then
  Debug.Print "present"
Else
  Debug.Print "not present"
End If
```
