### ISSUE TITLE
KeyDown disrupts other commands in chain of Actions

### ISSUE THREAD

**Issue by mhenson1** [florentbr/SeleniumBasic#81]
I have an object in my cef application that I want to perform a drag operation on twice while holding the shift key down. If I use this line the drag is successful
selenium.Actions.DragAndDropByOffset(myObj, 200, 0).DragAndDropByOffset(myObj, 0, 200).Perform
It drags the object to the right and then down. When I insert the KeyDown event nothing happens
selenium.Actions.KeyDown(seleniumKeys.Shift).DragAndDropByOffset(myObj, 200, 0).DragAndDropByOffset(myObj, 0, 200).Perform

A couple of other potentially slightly related things I noticed when browsing through the wrapper to try figuring out what was going on.
In the Keyboard and Actions classes you have the constants for Alt and Control backwards, at least compared to how you have them declared in the Keys class.
This is probably intentional but I was trying to mess around with the Keyboard class and I was unable to create a com object for that or the mouse class. If I tried calling this then I got an activex error.
Set seleniumKeyboard = CreateObject("Selenium.Keyboard")

Thanks as always for your great work.

**Comment by longpants** [comment]
Hi Florent, as in line with this question:
Is it possible to disable user entry during running actions on the webdriver? 
Reason for this is when I'm running actions on webdriver, any other key entry in Excel will affect the driver. (or can I run, without focussing on the driver?)
I was trying to create a Keyboard Class, but as mhenson1 mentioned, Keybord cannot be created from DLL:

```
Option Explicit
Dim kb As Object 'Selenium.Keyboard

Private Sub Class_Initialize()
    Set kb = CreateObject2("Selenium.Keyboard")
End Sub

Public Function SendKeys(keysOrModifiers As String, Optional Keys As String) As Keyboard
    kb = kb.SendKeys(keysOrModifiers, Keys)
End Function
```

> Kan type WebDriver.Keyboard niet laden vanuit assembly Selenium, Version=2.0.8.0, Culture=neutral, PublicKeyToken=d499ab7f7ba4d827.

**Comment by florentbr** [comment]
> When I insert the KeyDown event nothing happens

I couldn't reproduce your issue with Chrome:

```vb
  Dim drv As New ChromeDriver
  drv.Get "http://fiddle.jshell.net/ybztuj97/3/show/light"
  drv.Get "http://fiddle.jshell.net/ybztuj97/3/show/light"
  
  Dim src As WebElement, tgt As WebElement
  Set src = drv.FindElementById("draggable")
  Set tgt = drv.FindElementById("droppable")
  
  drv.Actions _
    .KeyDown(Keys.Shift) _
    .DragAndDropByOffset(src, 50, 0) _
    .DragAndDropByOffset(src, 0, 50) _
    .Perform
    
  Debug.Assert 0
  drv.Quit
```

Can you provide a reproductible example?


> In the Keyboard and Actions classes you have the constants for Alt and Control backwards, at least compared to how you have them declared in the Keys class.

This is an error in the code.


> This is probably intentional but I was trying to mess around with the Keyboard class and I was unable to create a com object for that or the mouse class. If I tried calling this then I got an activex error.
Set seleniumKeyboard = CreateObject("Selenium.Keyboard")

The Keyboard object rely on a driver and therfore can not be created alone.
To access it:

```vb
  driver.Keyboard.KeyDown Keys.Shift
```
