### ISSUE TITLE
Firefox and Chrome profiles won't load

### ISSUE THREAD

**Issue by psko** [florentbr/SeleniumBasic#82]
Firefox: The code "driver.SetProfile "C:\ProfileFolder"" does not load any profile, Firefox tries to load a profile from "C:\Users\Username\AppData\Local\Temp\Selenium\ff-96a4ec00" (this last folder name is random);

Chrome: The code "driver.SetProfile "C:\ProfileFolder"" loads a profile from "C:\ProfileFolder\Default".

I managed to fix the last bug by manually moving all the contents from the ProfileFolder to ProfileFolder\Default.

Thanks for the great work!

**Comment by florentbr** [comment]
> Firefox: The code "driver.SetProfile "C:\ProfileFolder"" does not load any profile, Firefox tries to load a profile from "C:\Users\Username\AppData\Local\Temp\Selenium\ff-96a4ec00" (this last folder name is random);

If persistent is false, the driver works with a copy of the provided folder to TEMP/Selenium.
The folder C:\ProfileFolder probably contains an incorrect profile.

> Chrome: The code "driver.SetProfile "C:\ProfileFolder"" loads a profile from "C:\ProfileFolder\Default".

The path needs to be the parent folder of the Default folder.

Here are some usage examples:

```vb
Private Sub Use_Chrome_With_Custom_profile_name()
  ' Profiles folder : %APPDATA%\Google\Chrome\Profiles
  ' Note that with Chrome the profile is always persistant
  
  Dim driver As New ChromeDriver
  driver.SetProfile "Selenium"
  
  driver.Get "https://www.google.co.uk"
  driver.Quit
End Sub

Private Sub Use_Chrome_With_Custom_profile_path()
  ' Default profile : %LOCALAPPDATA%\Google\Chrome\User Data
  ' Profiles folder : %APPDATA%\Google\Chrome\Profiles
  ' Note that with Chrome the profile is always persistant
  
  Dim driver As New ChromeDriver
  driver.SetProfile "%LOCALAPPDATA%\Google\Chrome\User Data"
  
  driver.Get "https://www.google.co.uk"
  driver.Quit
End Sub


Private Sub Use_Firefox_With_Custom_profile_name()
  ' To manage firefox profiles: firefox -p
  ' Profiles folder: %APPDATA%\Mozilla\Firefox\Profiles
  ' When persistant is False, the driver works with a copy in the Temp folder.
  
  Dim driver As New FirefoxDriver
  driver.SetProfile "Selenium", persistant:=True
  
  driver.Get "https://www.google.co.uk"
  driver.Quit
End Sub

Private Sub Use_Firefox_With_Custom_profile_path()
  ' To manage the profiles: firefox -p
  ' Profiles folder: %APPDATA%\Mozilla\Firefox\Profiles
  ' When persistant is False, the driver works with a copy in the Temp folder.
  
  Dim driver As New FirefoxDriver
  driver.SetProfile "%APPDATA%\Mozilla\Firefox\Profiles\kfvj49h4.Selenium", persistant:=True
  
  driver.Get "https://www.google.co.uk"
  driver.Quit
End Sub
```
