### ISSUE TITLE
TouchAction / TouchScreen : scroll into view --> to center view

### ISSUE THREAD

**Issue by longpants** [florentbr/SeleniumBasic#83]
Hi Florent,

I'm struggeling with scrolling an element into center view.
Currently the following works fine, but the view is scrolled with element at bottom (or top, when used `ScrollIntoView True`)
```
Set s = driver.FindElementByXPath("//some xpath")
s.ScrollIntoView
```

But I'd like to scroll the element into center of the view, or with some offset to bottom/top of page to have a better overview when creating screenshots.
Currently I'm looking at TouchActions/TouchScreen, but cannot seem to get it working:
```
With driver.TouchActions
            .ScrollFrom s, 0, 200
            .Perform
End With
```
At perform VBE reports error: (In Dutch, so I translated):
> Error -2146233078 (8013150a) on runtime:
> Cannot locate soure, but some logfiles cannot be searched. Not available logfile: Security

When I try to create the TouchAction or TouchScreen object:
```
Dim ts As Object
Set ts = CreateObject2("Selenium.TouchScreen")
```
> Error -2146233069 (80131513) on runtime:
> Constructor for type Selenium.TouchScreen not found

Do you have any ideas/solution?

Thanks

**Comment by florentbr** [comment]
Touch commands are for touch drivers/devices only.
The best way would be with some Javascript:

```vb
Private Sub Scroll_Element_To_Center()
  Dim drv As New FirefoxDriver
  drv.Get "https://en.wikipedia.org/wiki/Main_Page"
  
  drv.FindElementByCss("#mp-other").ExecuteScript _
    "this.scrollIntoView(true);" & _
    "window.scrollBy(0, -(window.innerHeight - this.clientHeight) / 2);"
  
  Debug.Assert 0
  drv.Quit
End Sub
```

**Comment by longpants** [comment]
Ok, this should work as well, but it doesn't. Somehow my page doesn't scroll.
I've attached the example html and used:
`driver.FindElementByXPath("//*[text()[contains(.,'*WerkImpulz')] and (contains(@class,'xa') or contains(@class,'x7')) and contains(@class,'ff2')]
[6326179_28034660_Pakketvoorblad.txt](https://github.com/florentbr/SeleniumBasic/files/153004/6326179_28034660_Pakketvoorblad.txt)

').ExecuteScript ("this.scrollIntoView(true);window.scrollBy(0, -(window.innerHeight - this.clientHeight) / 2);")`

**Comment by florentbr** [comment]
It's not working in your case because the scrollbar is not on the page but on a container.
So to make it work, you need to call scrollBy on that specific container:

```vb
drv.FindElementByXPath("//*[...").ExecuteScript _
  "this.scrollIntoView(true);" & _
  "var container=document.getElementById('page-container');" & _
  "container.scrollBy(0, -(window.innerHeight - this.clientHeight) / 2);"
```

**Comment by longpants** [comment]
Hi Florent, thanks for helping into that direction.
Unfortunately I needed to have the 'page-container' dynamic. So created this javascript to loop from the found element (this) to the node that enables the scroll.
It seems to work quite nice :-)

```
var s = r(this);
function r(element) {
  var e = el;
  var p;
  var s;
  var eTop = e.scrollHeight;
  //console.log(e.innerHTML + ' ' + eTop + ' ' + e.offsetTop + ' ' + window.innerHeight);
  if (eTop < window.innerHeight) {
    p = e;//.parentNode;
    e.scrollIntoView(true);
    eTop=e.scrollTop;
    console.log('1' + + '' eTop + '' e.scrollTop + p.tagName.toUpperCase() ) ;
    while (p.tagName.toUpperCase() != 'HTML' && e.scrollTop == eTop) {   
      p=p.parentNode;
      //console.log('2' + p.tagName  + ' ' p.id + ' ' + p.scrollHeight );
      if (p.scrollHeight > window.innerHeight) {
        s = p;
        p.scrollTop -= ((window.innerHeight - e.clientHeight) / 2);
        eTop=e.scrollTop+p.scrollTop;
        console.log('2a' + p.tagName  + ' ' p.id+ ' ' + eTop);
      }
      else {
        console.log('2b' + p.tagName  + ' ' p.id);
      }
    }
  } else {
    //e.scrollIntoView(true);
    console.log('');
    s = e;
  }
  console.log('4');
  return s.tagName + s.className + s.id;
}
```

**Comment by florentbr** [comment]
You should make it generic by scrolling all the containers as well as the main window until the element is centered:

```js
  this.scrollIntoView(true);
  var y = (window.innerHeight - this.offsetHeight) / 2;
  if (y > 0) {
    for (var e=this; e; e=e.parentElement) {
      if (e.scrollTop) {
        var yy = Math.min(e.scrollTop, y);
        e.scrollTop -= yy;
        if ((y -= yy) < 1)
          return;
      }
    }
    window.scrollBy(0, -y);
  }
```

**Comment by longpants** [comment]
Even better than mine, thanks!
