### ISSUE TITLE
Element not clickable at .Click action

### ISSUE THREAD

**Issue by longpants** [florentbr/SeleniumBasic#85]
Hi Florent,

Do you happen to have a robust solution for the following?

> 13: UnknownError
> unknown error: Element is not clickable at point (466, 55). Other element would receive the click: <div class="blockUI blockOverlay" style="z-index: 1000; border: none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; opacity: 0; cursor: default; position: fixed; background-color: rgb(0, 0, 0);"></div>
>   (Session info: chrome=40.0.2214.111)
>   (Driver info: chromedriver=2.12.301325 (962dea43ddd90e7e4224a03fa3c36a421281abb7),platform=Windows NT 6.1 SP1 x86_64)

So by testobject has an overlay, so the selected item cannot be clicked, although present.
Do you have any soloution without seperate waiting loops. Or direct reference to this overlay object/element.
More something like: isClickable... etc. Or is it better to implement a Javascript to execute the click action untill no error, or untill timout has reached?

**Comment by florentbr** [comment]
Many things can lead from an unclickable state to a clickable state. It really depends on how the page was developed.
It may be related to:
 A delay
 A foreign event (loading completion)
 A scrolling position
 A keyboard event
 A mouse event

That's why it is not natively handled by the Selenium framework.
Now to resolve this, you need to place yourself as a real user and find which action triggers this change of state.
Can you provide a reproducible example?

**Comment by longpants** [comment]
Oh, sorry I that a part of the message was not copied to the qoute:
`. Other element would receive the click: <div class="blockUI blockOverlay" style="z-index: 1000; border: none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; opacity: 0; cursor: default; position: fixed; background-color: rgb(0, 0, 0);"></div>`

1) So it's the `blockUI blockOverlay` element that is present on the page untill the page is fully loaded.
It this case "A foreign event" is what I'm facing.

As other questions: I'd like to have the automation dynamic, not aiming at specific classes etc.

2) There is also an exception: I have a next button that's located a little bit behind a banner, so this banner is also blocking my Click action, but in this case I use Action to sendkeys an Enter/Space.

Question remains: how can the driver know whether something is present (and will go away) or will be visible all the time.

I was also thinking about a JS in which moving the cursor around within the boundaries of the needed element and click again (resolving the issue 2). And since this there might have a small (timing) loop, this will resolve issue 1 as well?

**Comment by florentbr** [comment]
I will add the WaitForClickable method to handle timing issues. However it may be tricky for elements that are partially overlayed since some drivers only try to click in the center of the element.
In the meantime, here is an example to wait for a clickable element:

``` vb
  Const JS_WAIT_CLICKABLE = _
    "var target = this, endtime = Date.now() + arguments[0];" & _
    "(function check_clickable() {" & _
    "  var r = target.getBoundingClientRect(), x = r.left+r.width/2, y = r.top+r.height/2;" & _
    "  for (var e = document.elementFromPoint(x , y); e; e = e.parentElement)" & _
    "    if (e === target){ callback(target); return; }" & _
    "  if (Date.now() > endtime) { callback(target); return; }" & _
    "  setTimeout(check_clickable, 60);" & _
    "})();"

  driver.FindElementById("id") _
        .ExecuteAsyncScript(JS_WAIT_CLICKABLE, 3000) _
        .Click
```

To know if an element is clickable, the driver checks that the top element at the clicking point is the element in question or a child. So if you only need to test it:

``` vb
  Const JS_IS_CLICKABLE = _
    "var r = this.getBoundingClientRect(), x = r.left+r.width/2, y = r.top+r.height/2;" & _
    "for (var e = document.elementFromPoint(x , y); e; e = e.parentElement)" & _
    " if (e === this) return true;" & _
    "return false;"

  If driver.FindElementById("id").ExecuteScript(JS_IS_CLICKABLE) Then
    Debug.Print "Clickable"
  Else
    Debug.Print "Not clickable"
  End If
```

By default the driver calls scrollIntoView which sends the element at the bottom of the screen.
This is why you are getting the button a little bit behind a banner.
To solve it, try call scrollIntoView with True as argument to send it to the top first:

``` vb
driver.FindElementById("id").ScrollIntoView(True).Click
```

I'll see to implement the scrolling into the centre of the screen in case the Click fails the first time.

**Comment by longpants** [comment]
Thanks for your input. I tried to insert it, but struggled with the following:

```
driver.FindElementByXPath("//input[@value='Aanmelden']") _
                    .ExecuteScript(JS_WAIT_CLICKABLE, 3000) _
                    .Click
```

Resulted in: 

> 458: Variabele using automationtype not supported by Visual Basic

But the test on Clickable works quite well (thanks). I implemented it like the following:

```
If s.ExecuteScript(JS_IS_CLICKABLE) Then
      s.Click
Else
      With testObject.Actions
            .MoveToElement s
            .Wait Timing.step 'a 100 ms
            .Perform
            s.SendKeys testObject.Keys.Space
      End With
End If
```

About the 'not clickable element behind banner':

> By default the driver calls scrollIntoView which sends the element at the bottom of the screen.
> This is why you are getting the button a little bit behind a banner.
> To solve it, try call scrollIntoView with True as argument to send it to the top first:

Since the button (Next) is at bottom of page, the `scrollIntoView with True` won't work.
I 'solved' this with the `.SendKeys testObject.Keys.Space`, but I think it's better to run a JS that tries to click the element within the boundaries of the element. What's your opinion on this?

**Comment by florentbr** [comment]
You need to use ExecuteAsyncScript instead of ExecuteScript:

```
driver.FindElementByXPath("//input[@value='Aanmelden']") _
      .ExecuteAsyncScript(JS_WAIT_CLICKABLE, 3000) _
      .Click
```

**Comment by longpants** [comment]
Sorry, I did try the `ExecuteAsyncScript` as well, but same error. Using v2.0.8.0

**Comment by florentbr** [comment]
ExecuteAsyncScript was introduced with the release 2.0.9.0

**Comment by longpants** [comment]
ah... sorry. I should have checked that.
Does the dll provide a function to check the verion number (to check compatibility)?

Can it be caused since I'm using Chrome 40 (and corresponding Webdriver 2.12.301325) (my project/office doesn't allow to update)?
