### ISSUE TITLE
Second launch

### ISSUE THREAD

**Issue by uzhas-sovka** [florentbr/SeleniumBasic#86]
First step

```
Private browser As New Selenium.ChromeDriver

Public Sub Runner()
   browser.Get "http://mail.yahoo.com"
end sub
```

Browser keeps on running after finishing the script, everything is OK. I do some job in browser manually, then close browser.

Second step
Next launch, same script, same IDE session, error "Selenium error, Chrome not reachable, session info and driver info". Press OK, then re-launch. everything OK.

I noticed that chromedriver.exe process keeps on running between launches. But if you kill it between first launch and second launch, VBA script stops during second launch with error "Unable to connect to remote server". That's strange, because it seems that the only difference between "fresh launch" and second launch is running chromedriver.exe

Thank you!

**Comment by florentbr** [comment]
> Browser keeps on running after finishing the script, everything is OK. I do some job in browser manually, then close browser.

Closing the browser manually doesn't terminate the current session since you've declared it in a global variable. To terminate a session you need to either:
- Click on Stop/Reset in the VBA editor
- Or explicitly call driver.Quit
- Or close Excel 

Here is an example of a static driver with a QuitDriver procedure:

```
Private driver As New Selenium.FirefoxDriver

Public Sub Main()
  driver.Get "http://..."
End Sub

Public Sub QuitDriver()
  driver.Quit
  Set driver = Nothing
End Sub
```

Another way is to work with a break point and then click continue once you have finished with the browser:

```
Private driver As Selenium.FirefoxDriver

Public Sub Main()
  Set driver = New Selenium.FirefoxDriver
  driver.Get "http://..."

  Debug.Assert 0
  driver.Quit
End Sub
```

**Comment by uzhas-sovka** [comment]
Thank you! First method was not obvious to me. I'm running script not from VBA editor but from "button" on Excel panel, so it seems that script is completely finished...

**Comment by uzhas-sovka** [comment]
I must confess it's extremely annoying to keep VBA open during usual rounds, so I've found another solution.

```
While ChromeRunning
  DoEvents
  Sleep (100)
Wend

Call QuitDriver
```

where Sleep() is

`Declare Sub Sleep Lib "kernel32" (ByVal dwMilliseconds As Long)`

And ChromeRunning is something like

```
Function ChromeRunning() As Boolean
    ChromeRunning = False
    strComputer = "."
    strProcsToWatch = "chrome.exe"
    Set wbemObjectSet = GetObject("winmgmts://" & strComputer).InstancesOf("Win32_Process")
    For Each wbemObject In wbemObjectSet
        If LCase(wbemObject.Name) = strProcsToWatch Then ChromeRunning = True
    Next
End Function
```

So the script stops/quits in a proper way after the absence of chrome.exe is detected.

**Comment by florentbr** [comment]
A timer would be better for this task:

``` vb
Private driver As New Selenium.ChromeDriver

Private Sub Use_Chrome()
  driver.Get "https://www.google.co.uk"

  Call QuitDriverOnChromeExit
End Sub


Sub QuitDriverOnChromeExit()
  Const cmd = "Select * from Win32_Process Where Name='chrome.exe'"
  If driver Is Nothing Then Exit Sub
  If GetObject("winmgmts:").ExecQuery(cmd).Count Then
    Application.OnTime Now + 2 / 86400, "QuitDriverOnChromeExit" 'try again in 2sec
  Else
    driver.Quit
    Set driver = Nothing
  End If
End Sub
```

**Comment by uzhas-sovka** [comment]
You are right. My example was rough-and-ready snippet from SO.
