### ISSUE TITLE
Edge Browser - Private Mode

### ISSUE THREAD

**Issue by meluvalli** [florentbr/SeleniumBasic#89]
This is more a question than an issue.  Sorry if this is the wrong place to ask this...  But, is there anyway to start Edge in Private Mode through VBA?   If not, is there at least a way to put it in private mode after it launches through VBA?

Thanks for an awesome program!!! :)

**Comment by florentbr** [comment]
It doesn't seem possible with a command line argument, but it can be achived this way:

``` vb
Dim driver As New EdgeDriver
driver.Get "about:InPrivate"
driver.Get "https://www.google.com"


Debug.Assert 0
driver.Quit
```
