### ISSUE TITLE
Porting setImplicitWait method

### ISSUE THREAD

**Issue by kawaihk** [florentbr/SeleniumBasic#9]
Hello!
I am porting from SeleniumVBA to SeleniumBasic.

I used "setImplicitWait" method in SeleniumVBA when web page was loaded.
I can't use this method in SeleniumBasic, because "ImpliciitWait" changes method to property.
   (driver.setImplicitWait -> driver.Timeouts.ImplicitWait)

So Would you tell me how can I do porting  from SeleniumVBA to SeleniumBasic about below sample code?

((SeleniumVBA))

Dim driver as SeleniumWrapper.WebDriver
Set driver = New SeleniumWrapper.WebDriver

driver.Start "firefox", "https://www.google.co.uk"
driver.setImplicitWait
driver.Open "/maps/"
driver.setImplicitWait

((SeleniumBasic))

Dim driver as FirefoxDriver
Set driver = New FirefoxDriver

driver.Start "https://www.google.co.uk"
driver.Get "/maps/"

Thanks.

**Comment by florentbr** [comment]
> So Would you tell me how can I do porting from SeleniumVBA to SeleniumBasic about below sample code?

Setting driver.Timeouts.ImplicitWait is not necessary as Implicit waiting is now activated by default.
So your example would be:

    Dim driver as New FirefoxDriver
    driver.Get "https://www.google.co.uk/maps/"
    driver.Quit

Or

    Dim driver as New WebDriver
    driver.Start "firefox",  "https://www.google.co.uk"
    driver.Get "/maps"
    driver.Quit

You should have a look at the examples in the installation folder.
