### ISSUE TITLE
Not able to click button?

### ISSUE THREAD

**Issue by meluvalli** [florentbr/SeleniumBasic#92]
Is there anyway to click a button that doesn't have an ID/Name associated to it?

webpage: https://www.cox.com/cbaccount/home.cox?onsuccess=%24SM%24HTTP%3A%2F%2Fmyaccount.coxbusiness.com%2Fweblogic%2Fbillpay.ms

I normally use:
`Selenium.FindElementByName("Sign In").Click`
However, since there is no button name, I can't click it :(

**Comment by longpants** [comment]
You can use firefox Selenium IDE to identify your element.
But SeleniumBasic provides other locators then `FindElementByName`, 
ie:
`FindElementByCSS("li.form-submit > button[type='submit']")`
`FindElementByxPath("//button[@type='submit'])[2]")`

**Comment by florentbr** [comment]
The best way to get a CSS or XPath expression would be thought the browser:
- Right click on the target element
- Click inspect
- Right click on the highlighted node
- Click Copy XPath or Selector

To use an XPath expression to click an element:

   driver.FindElementByXPath("XPath expression").Click

And to use a CSS expression to click an element:

   driver.FindElementByCSS("CSS expression").Click

**Comment by meluvalli** [comment]
I don't have a "Copy XPath" or "Selector".  I am using Edge browser.  Maybe this is why?  Buy, the line it highlights just says
`<span>Sign In</span>`

So I must be missing something?

**Comment by florentbr** [comment]
Try this:

```
driver.FindElementByXpath("//span[text()='Sign In']").Click
```

Or this one if it's inside a link:

```
driver.FindElementByLinkText("Sign In").Click
```
