### ISSUE TITLE
unable to count class

### ISSUE THREAD

**Issue by saadamiens** [florentbr/SeleniumBasic#93]
Hello, 

I currently get the following error when counting a class 

here is the code 

driver.FindElementsByClass("listing__link listing__link--visit").Count

here is the error 

run time error 32

invalid selector: compound class names not permitted 
session info; chrome 

could you please tell me what I should do

second question 

Is there a possibility to count the first li tag, here is what i mean:

ul
*\* li**
   span
      li
      li
*\* li**
   span
      li
      li
      li
      li
*\* li**
   span
      li
      li
/ul

here the result should be 3

Thanks

**Comment by florentbr** [comment]
Spaces are illegal in a class name.

You should use a Css selector instead:

```
driver.FindElementsByCss("css selector").Count
```

Or an XPath:

```
driver.FindElementsByCss("xpath").Count
```

To get the XPath or Css expression, right click on a node in you browser.
