### ISSUE TITLE
Element not found within iFrame?

### ISSUE THREAD

**Issue by meluvalli** [florentbr/SeleniumBasic#94]
I am trying to enter data in a field using XPath, but not able to locate the element...

Code Used:
`driver.FindElementByXPath("//*[@id='userId']").SendKeys "My Name"`

Page example: https://www.csu.org

Any way to put data into field through the iFrame?

**Comment by florentbr** [comment]
You need to set the context to the frame:
driver.SwitchToFrame(identifier)
