### ISSUE TITLE
Reading an existing PDF file

### ISSUE THREAD

**Issue by bipo1980** [florentbr/SeleniumBasic#97]
Hello @florentbr ,

is there a way to read from an existing pdf file in case i have only adobe reader installed?

thanks,
B.

**Comment by florentbr** [comment]
Yes, have a look to the module "usage_pdf" in Examples.xlsm

**Comment by longpants** [comment]
Hi B., 

Depends on what you're up to check within the pdf,  but I'm using pdf2htmlex to convert the pdf to html (command line), which can be tested by webdriver. 
Great thing is that it's browser independent. Downside is it's only working for text recognition. Or if you're into base64 images it will also work. 

https://www.google.nl/url?sa=t&source=web&rct=j&url=https://github.com/coolwanglu/pdf2htmlEX&ved=0ahUKEwiQ4LeSy8zLAhVG7w4KHS4-BpoQFggbMAA&usg=AFQjCNH8--inc8FsmIepcBFGjdRwYyn5Xw&sig2=eplQEP9DZhIleHBvBR95Rg
